### ISSUE TITLE
Access custom electron events (e.g., login)

### ISSUE THREAD

**Issue by carsonfarmer** [asticode/go-astilectron#101]
I'd like to be able to access custom electron events such as a login (https://electronjs.org/docs/api/app#event-login) for working with content that requires basic auth. Is it possible to create listeners for arbitrary electron events? Is there a better way to achieve what I'm trying to do (automatically supply credentials for basic auth)?

**Comment by asticode** [comment]
@carsonfarmer right now there's no method to listen to an arbitrary electron events and receive all information in GO. And  I don't see any easy or clean solution to do that.

Nonetheless, here's what I have in mind:
- use the `WebContents` [login event](https://electronjs.org/docs/api/web-contents#event-login) instead since that way we know the window it's attached to
- in `js`, add a listener on `login` on `WebContents` when creating a window that will send a message to GO with the `request` and `authInfo` information. This will then wait for the response from GO with the `username` and `password`
- in `go`, the developer will have to use a new `OnLogin` method to the window. This new method will provide the `request` and `authInfo` information and will send a specific message to the `js` containing the `username` and `password`.

What do you think?

**Comment by carsonfarmer** [comment]
I think this might be exactly what I need! I’ll report back here with my progress 👍

**Comment by asticode** [comment]
@carsonfarmer I think the best would be to integrate it in the library directly and therefore update both [astilectron](https://github.com/asticode/astilectron) and [go-astilectron](https://github.com/asticode/go-astilectron). Would you be up for it? I'd be happy to review a PR.

If not, I may have some time to add it.

**Comment by carsonfarmer** [comment]
Given that I'm working with the bootstrap, am I right in assuming that adding the following to the head of my `Homepage` should work for subscribing to login on webContents:

```
    <script>
        const win = require('electron').remote.getCurrentWindow();
        win.webContents.on('login', function(event, request, authInfo, callback) {
            event.preventDefault();
            console.log("login!");
        })
    </script>
```

Or do I have to put it in astilectron-ready callback? Apologies for the noob questions, I'm still learning electron and go...

**Comment by asticode** [comment]
@carsonfarmer no worries about the questions, there are no noob questions :)

Here's what I have in mind:

## In [astilectron](https://github.com/asticode/astilectron)

- add a listener to the `WebContents`'s`login` event when creating a `Window` in [this function](https://github.com/asticode/astilectron/blob/master/main.js#L362)
- this listener will increment some kind of counter, write a `window.cmd.login` message containing this counter and save the `callback` of the electron event in a map indexed by this counter
- in the [big switch](https://github.com/asticode/astilectron/blob/master/main.js#L64) that parses the message coming from GO, it should listen to a new message `window.event.login` that will contain the username, password and counter. This will let it find the callback thanks to the counter, and execute it with the username + password coming from GO

## In [go-astilectron](https://github.com/asticode/go-astilectron)

- add an `OnLogin(fn func() (username, password string))` method to the `Window` object
- this method will listen to `window.cmd.login` events, get the username/password from the `fn` func and send back a `window.event.login` with the username + password + counter.

Does that make sense?

If you feel it's too complex of a change, I can handle it, no worries.

Let me know.
Cheers

**Comment by carsonfarmer** [comment]
Wow, thanks @asticode. So we ended up trying a different route in order to avoid touching astilectron internals, however, I _think_ we might be running up against a similar issue? If you think these are related (see below), we might take a stab at your proposed solution in the next week or two?

Some context:
On the go side, we have a local https server serving up images for display in the main app window. However, since we're using a self-signed cert, 'electron' doesn't want to allow it over https. [This fix](https://electronjs.org/docs/api/app#event-certificate-error) should work, but doesn't seem to, and I suspect its because astilectron doesn't know what to do with the callback?

```
const remote = require('electron').remote;
const app = remote.app;
// SSL/TSL: this is the self signed certificate support
app.on('certificate-error', (event, webContents, url, error, certificate, callback) => {
    event.preventDefault();
    console.log("cert-error")
    callback(true);
});
```

Is this the case? The event _does_ fire (cert-error does get logged to the console), but then right afterwards, we get: `Failed to load resource: net::ERR_INSECURE_RESPONSE` when requesting (say) an image via an image tag. If these aren't related should I open a separate issue?

**Comment by carsonfarmer** [comment]
Oh this would be great @asticode. We're keep to contribute to the project, so a nice example like that would be killer!

**Comment by asticode** [comment]
@carsonfarmer I've just added the handling of the `login` event. 

You can check out the doc [here](https://github.com/asticode/go-astilectron#basic-auth).

Also:
- check out the commit in [astilectron](https://github.com/asticode/astilectron/commit/34ad957edf4cf05c2b3046df520e98bc5c56f977). If you want to add the handling of another similar event, I've added `registerCallback` and `executeCallback` methods for easier use.
- check out the commit int [go-astilectron](https://github.com/asticode/go-astilectron/commit/7cf2a077ce9f502cfc07af03b14dcb9cdd115223)

Does that fix your issue?

**Comment by asticode** [comment]
@carsonfarmer I'll close the issue for now but feel free to reopen it if you're facing any problem
