### ISSUE TITLE
'astilectron-bundler' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by calibar** [asticode/go-astilectron#102]
Hi, I was trying to run the demo, however, I got "'astilectron-bundler' is not recognized as an internal or external command,operable program or batch file." when I was running command "astilectron-bundler -v". I have already checked the Path, $GOPATH path is already in it. I am using win10.

**Comment by asticode** [comment]
@calibar I think you forgot to `go get` the bundler which should have installed the bundler. Please refer to [this step](https://github.com/asticode/go-astilectron-demo#step-2-install-the-bundler) and more importantly this command: `go get -u github.com/asticode/go-astilectron-bundler/...`.

This should do the trick.

**Comment by calibar** [comment]
I have run the command "go get -u github.com/asticode/go-astilectron-bundler/...", however, it still doesn't work, then I tried @Noofbiz 's method. It works, but I got this back: {"level":"fatal","msg":"opening file C:\\Users\\liumengxuan\\bundler.json failed: open C:\\Users\\liumengxuan\\bundler.json: The system cannot find the file specified.","time":"2018-04-21T09:04:31-06:00"}. Thank you for all your help.

**Comment by asticode** [comment]
In order to use `astilectron-bundler` without specifying the [input path](https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go#L48) you need to `cd` in your project directory first. Then you can execute your command and the bundler will execute its steps on the current directory. 

Does that fix your issue?

**Comment by calibar** [comment]
Yes, It works right now, I forgot to cd to the folder, hahahah, thank you for all your help.

**Comment by asticode** [comment]
Cheers
