### ISSUE TITLE
app.commandLine flags?

### ISSUE THREAD

**Issue by carsonfarmer** [asticode/go-astilectron#104]
Is it possible to apply chromium command line flags when starting up an astilectron app? If not, I'd be interested in enabling this type of feature, but would your thoughts on how best to approach this? In 'vanilla' electron this might look something like:

```
app.commandLine.appendSwitch('ignore-certificate-errors', 'true');
```

Related to recent update on #101 .

**Comment by asticode** [comment]
@carsonfarmer you can already use electron switches through the [ElectronSwitches](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L75) attribute. In your example you would have to set it to `[]string{"ignore-certificate-errors","true"}`.

Does that fix your issue?

**Comment by carsonfarmer** [comment]
Yes, I'm sorry for the noise! Very impressive project by the way!
