### ISSUE TITLE
Extremely slow debugging

### ISSUE THREAD

**Issue by midona-rhel** [asticode/go-astilectron#105]
go version: 1.10.1
OS: macos 10.13.4

Hi there, while trying to debug with delve I have noticed extremely slow execution time with calls coming through the messagehandler of the bootstrap when a breakpoint is added, talking about minutes between lines. I went and google'd quite a bit and have found nothing describing anything remotely similar to my experience which leads me to believe this _might_ have something to do with go-astilectron or the bootstrap. This is beyond me and I was wondering if this is known about? (other programs debugged behave at a reasonable speed)

**Comment by midona-rhel** [comment]
After messing around with it for a bit I am sure it happens [at this point](https://github.com/asticode/go-astilectron/blob/master/helper.go#L161), after this it becomes a complete trudge, seems a bit arbitrary, but I might just open this as an issue with the delve developers with a relatively clean project ready if it needs testing.

**Comment by asticode** [comment]
@midona-rhel your best shot is to update the methods like this:
```go
func synchronousEvent(c *asticontext.Canceller, l listenable, w *writer, i Event, eventNameDone string) (o Event, err error) {
        astilog.Debugf("In synchronousEvent for event %+v", i)
	o = synchronousFunc(c, l, func() {
		if err = w.write(i); err != nil {
			err = errors.Wrapf(err, "writing %+v event failed", i)
			return
		}
		return
	}, eventNameDone)
	return
}
```
and
```go
func synchronousFunc(c *asticontext.Canceller, l listenable, fn func(), eventNameDone string) (e Event) {
	var ctx, cancel = c.NewContext()
	defer cancel()
	l.On(eventNameDone, func(i Event) (deleteListener bool) {
		e = i
		cancel()
		return true
	})
	fn()
        astilog.Debugf("Waiting for event name %s", eventNameDone)
	<-ctx.Done()
	return
}
```
I've just added 2 lines that log the type of events that are handled.
Then at the top of your `main` function, make sure `astilog` is set up by adding:
```go
flag.Parse()
astilog.FlagInit()
```
Finally run your command with the `-v` flag to enable debug logs and paste the logs here.
We should be able to see which events is blocking and why.

**Comment by midona-rhel** [comment]
Sorry I have been busy, I think I have nailed down when it happens and as soon as the electron app is launched execution speed is counted in seconds per line of code. Its not a specific event blocking or adding overhead but rather it just seems like it is more or less too much for delve to handle. The electron part still runs fine but golang is just dead, guess I have to rely on prints for the time being. Thanks for the help, and on a bit of an unrelated note do you know if you can get astilectron to play nice with node?

**Comment by asticode** [comment]
Thing is astilectron basically spawns a TCP server, runs an electron app and communicates with it through the TCP server. Therefore I don't really see a way to optimize the node interaction. I'd still be interested in seeing the logs I've proposed if you have time.

**Comment by asticode** [comment]
@midona-rhel closing this issue. I'm still interested in the logs I've proposed if you have time though.
