### ISSUE TITLE
MaxListenersExceededWarning occurs when executing astilectron.sendMessage() too quickly 

### ISSUE THREAD

**Issue by rcholic** [asticode/go-astilectron#106]
My app has multiple menu items, each of which triggers `astilectron.sendMessage()` to send messages to the backend/Go code for handling the messages. Some message handling may take longer time than others to process. 

When I click between these menu items, before I see the message callback is triggered, I sometimes see errors in the app developer console:

>MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ipc.cmd.message.callback listeners added. use emitter.setMaxListeners() to increase the limit.

Does that mean the solution will simply be increase the limit here?

**Comment by asticode** [comment]
@rcholic I've checked the reasons of this error and there's definitely something wrong in **astilectron** that I should fix. In the meantime you can increase the limit but this is not a viable solution.

I'll keep you posted.

**Comment by asticode** [comment]
@rcholic I've pushed some changes to **astilectron**. Can you:

- fetch changes to **go-astilectron**
- run `go install github.com/asticode/go-astilectron-bundler/astilectron-bundler`
- try again and let me know if you're still experiencing issues?

**Comment by rcholic** [comment]
@asticode 

Thanks so much for the fix. I just tried my app with the fix, it looks like the issue is no more reproducible. That is awesome 👍 

I'll leave this to you to close :)

**Comment by asticode** [comment]
Cheers
