### ISSUE TITLE
Get native window id

### ISSUE THREAD

**Issue by pwhelan** [asticode/go-astilectron#108]
Is it possible to get the native window id? As far as I can tell electron has a getNativeWindowHandle on the window object that is able to retrieve the native window handle. How would I go about calling it from go?

**Comment by asticode** [comment]
@pwhelan for now you can't retrieve the native window id. I could add such a thing, but I don't think having the native window id will help you in your use case. What are you trying to achieve in details?

**Comment by pwhelan** [comment]
I intend on creating a web browser similar to surf. I already have the most basic parts working but now I am working on getting XEmbed to work so I can embed it into tabbed. From what I can tell I'll pretty much have to rewrite or extend main.js anyways.

**Comment by asticode** [comment]
@pwhelan in that case I'm not entirely sure `go-astilectron` is the correct project for you. I think you're better off manipulating `electron` directly without the GO overhead
