### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by lylib** [asticode/go-astilectron#109]
High version macOS generation application, low version macOS incompatible operation.

**Comment by asticode** [comment]
@lylib I don't understand what you're saying. Is it a question? If so could paste some logs so that I understand what you're saying exactly?

**Comment by lylib** [comment]
this is a question
![wx20180503-160800](https://user-images.githubusercontent.com/27846062/39565869-2e3e6a7c-4eec-11e8-8b2c-f77cc1555ae6.png)

**Comment by asticode** [comment]
@lylib unfortunately I don't read this alphabet :( Could you translate in english ?

**Comment by lylib** [comment]
@asticode 
Error message:
This version of the application "XXX" cannot be used with this version of macOS configuration
You are using macOS 10.12.5 You should use the program that requires macOS 10.13 or later

**Comment by xuzhiping7** [comment]
Hi , i met this question too.

On MacOS, the released application can only running on the higher version MacOS, when running on the lower version of MacOS ,it would alert the error information (like above).

Hope this bug can be fixed as soon as possible . 

Thanks.

**Comment by asticode** [comment]
@xuzhiping7 is the behavior the same whether the app is built on the lower or the higher version of MacOS? Are you experiencing the issue with the same versions as @lylib (10.12.5 | 10.13) ?

**Comment by sam-kamerer** [comment]
It's can be fixed by set up the minimum MacOS version in the **bundler.json**:
```
{
  "app_name": "Best app",
  "environments": [
    {
      "arch": "amd64",
      "os": "darwin",
      "env": {
        "CGO_ENABLED": "1",
        "CGO_CFLAGS": "-mmacosx-version-min=10.11",
        "CGO_LDFLAGS": "-mmacosx-version-min=10.11"
      }
    }
  ]
}
```

**Comment by lylib** [comment]
@sam-kamerer 
Everything works now.
Thanks for the help!

**Comment by lylib** [comment]
@sam-kamerer
