### ISSUE TITLE
GOARCH=386 support

### ISSUE THREAD

**Issue by mikkoseppanen** [asticode/go-astilectron#11]
Hi,

I recently got a project going where I'm able to nicely build a single binary program using go-astilectron, for 64bit linux & windows. I then got to work trying to build for `GOARCH=386` (I have the toolchain built) and get a successful build with `GOARCH=386 build -a`, but when I try to run it I get an marshaling error when I guess astilectron is starting up.

Error I get is:
`{"level": "error","msg":"json:cannot unmarshal number 2528732444 into Go struct field DisplayOptions.id of type int while unmarshaling {\"name\":\"app.event.ready\", ... snip ... \"displays\":{\"all\":[{\"id\":2528732444,\"bounds\" ... another snip ... }`

Exactly the same code, but built with `GOARCH=amd64`, is working wonderfully.

Is 32bit supported at all?

This is an amazing project, thank you for all your hard work so far!

**Comment by asticode** [comment]
32bit is supported but I've surely missed some places where I should have used `int64` instead of `int`. I've made some changes that I've committed, does it fix things for you? (in your case, the problem was that the ID returned by Electron was an int64)

**Comment by asticode** [comment]
in fact I've thought of other things to change to support 32bit better, I'll see what I can do this week

**Comment by mikkoseppanen** [comment]
Thank you for the quick reply. 

The changes you made fixed the issues for me, everything is working now. I've tested this by cross-compiling to GOARCH=386 on a 64bit machine and running the binary on a native 32bit Windows.

Thanks a lot! You would like to keep this issue open for the rest of your fixes? I can close this one as my initial problem is now fixed.

**Comment by asticode** [comment]
the other thing I've thought about is using the 32bits version of Electron instead of forcing the 64bits one (which I should have done from the get go) and revert using `int`. This should fix your issue as Electron should stop sending int64 IDs. Do you mind testing it later this week when I have made the change?

**Comment by mikkoseppanen** [comment]
Yes sure, my aim is to have the correct Electron embedded in the final binary based on the OS and arch. I've downloaded electron separately and changed the `go:generate` to include correct electron version based on $GOOS now and plan to include $GOARCH checking soon. I can do this on my project and then test against your changes (when I know I don't have x64 electron for ia32 binary and vice versa).

**Comment by asticode** [comment]
sounds good, thanks a lot. I'll keep you posted in this issue when I've made the changes

**Comment by asticode** [comment]
@mikkoseppanen I've just made the changes and pushed them on `master`. You should get `ia32` binary if your `runtime.GOARCH` is `386` and `x64` binary if your `runtime.GOARCH` is `amd64`.

What logic have you implemented exactly? I've the feeling others are needing it or will need it so it may as well be part of this library if possible. What do you think?

**Comment by mikkoseppanen** [comment]
Great, I'll try building later today. 

What I've done is I'm using `astilectron.NewDisembedderProvisioner(...)` which means I need to have the astilectron and Electron .zip packages pre-downloaded, right? Because I actually have a few build steps required before being able to bundle the whole thing into a single executable, I've added a `Makefile` that compiles my UI sources into a asar package, builds another utility and depending on the target OS/Arch, downloads astilectron (if missing) and the correct electron (if missing). Finally `go generate` is ran and if ok, `go build` with the GOOS and GOARCH and other flags set based on target (like `-ldflags "-H windowsgui"` on windows to hide cmd.exe upon launch).

In the main.go, I have a `go:generate` that looks like this:
```go
//go:generate go-bindata -pkg $GOPACKAGE -o resources.go resources/ui/... resources/icons/... resources/runtime/astilectron-v0.5.0.zip resources/runtime/electron-v1.6.5-$GOOS-$GOARCH.zip
```

This'll then embed the correct Electron based on the env-settings given in the Makefile (or command line). 

And finally the provisioner is used like this:

```go
app.SetProvisioner(
		astilectron.NewDisembedderProvisioner(
			Asset,
			"resources/runtime/astilectron-v0.5.0.zip",
			fmt.Sprintf("resources/runtime/electron-v1.6.5-%s-%s.zip", runtime.GOOS, runtime.GOARCH),
		),
	)
```

Assuming all required tools are installed I can then just call `make myprog-linux-386` and get all project related depedencies downloaded and build and compiled into a single binary. If you want to have a closer look, it's all at [timekeep](https://github.com/mikkoseppanen/timekeep)

**Comment by mikkoseppanen** [comment]
Hey,

I got around to test building with the latest changes. Unfortunately the initial problem is back.

I tested the following:
- 64bit build on linux (works)
- 64bit build on Windows (works)
- 32bit build on Windows (crash on launch, marshaling error from the DisplayOptions.id)
  * tried running on a native 32bit host and a 64bit host, doesn't matter.

I've checked that the go:generated file contains correct version of Electron (-ia32.zip for GOARCH=386 and -x86.zip for GOARCH=amd64).

I also tried the 1.basic_window example, got same results. I see that the Provisioner downloads the correct -ia32.zip when built with GOARCH=386, but fails similarly wehn starting.

**Comment by asticode** [comment]
OK thanks a lot for testing this, I've reverted my revert so that **astilectron** uses `int64` now. Can you confirm this is working?

**Comment by mikkoseppanen** [comment]
Everything works now. 

Confirmed on Linux 64bit, Windows 32bit & 64bit.

Thank you very much :)

**Comment by mikkoseppanen** [comment]
I'm closing this as my original problem is now solved. Thank you for the solution.
