### ISSUE TITLE
ERRO[0000] accept tcp 127.0.0.1:37411: use of closed network connection while TCP accepting

### ISSUE THREAD

**Issue by codemental** [asticode/go-astilectron#111]
I am getting the following error whenever I try to start a bundled app (ex. go-astivid/output/linux-amd64/Astivid):

```
ERRO[0000] accept tcp 127.0.0.1:37411: use of closed network connection while TCP accepting 
FATA[0000] creating window failed: canceller.cancelled 
```

I have tried the **go-astilectron-demo** and **go-astivid**. I have repeated the installation following the instructions carefully and I always get this error.

Any ideas would be helpful.

OS: Ubuntu 18.04 Budgie
GO go1.10 linux/amd64

**Comment by asticode** [comment]
could you start the app with the `-v` flag and paste logs here? this will enable verbose logging and may give us more information about the problem.

**Comment by codemental** [comment]
Oh great! With **-v** I was able to find the problem:

`DEBU[0000] Stderr says: ~/.gvm/pkgsets/go1.10/global/src/github.com/asticode/go-astilectron-demo/output/linux-amd64/vendor/electron-linux-amd64/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory `

The solution was `sudo apt-get install libgconf-2-4`. This was an electron issue: https://github.com/electron/electron/issues/1518.

Thank you!

**Comment by asticode** [comment]
Cheers

**Comment by kkofler** [comment]
According to the comments on the AUR package:

> flying-sheep commented on 2020-01-06 19:20 
> Most of the packages that “require” it are actually Electron apps that copy&pasted their dependency lists from elsewhere or failed to update them: Chromium (and subsequently Electron) haven’t been dependent on this for years.

So if you still get pointed to this bug, it is probably a red herring.
