### ISSUE TITLE
run  asticode/go-astilectron-demo  failed, Plz help!

### ISSUE THREAD

**Issue by tfnick** [asticode/go-astilectron#113]
Go-Astilectron is a awsome project! But I run the demo with a minor question. Please help!
My env as follow: 

<hr/>

mac 10.12.5 
go 1.10.2
GO & GOPATH is worked
npm 6.1.0
Electron   2.0.2
Node       8.9.3
Chromium   61.0.3163.100

I follow the step in go-astilectron-demo. after step 3, I entry the target dir & use ./Astilectron\ demo to run it.

error as follow:

<hr/>

**FATA[0000]** running bootstrap failed: starting astilectron failed: provisioning failed: provisioning electron failed: unzipping /Users/nick/Documents/GoPath/src/github.com/asticode/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/MacOS/vendor/electron-darwin-amd64-v1.8.1.zip into /Users/nick/Documents/GoPath/src/github.com/asticode/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/MacOS/vendor/electron-darwin-amd64 failed: unzipping /Users/nick/Documents/GoPath/src/github.com/asticode/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/MacOS/vendor/electron-darwin-amd64-v1.8.1.zip into /Users/nick/Documents/GoPath/src/github.com/asticode/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/MacOS/vendor/electron-darwin-amd64 failed: astiarchive: opening overall zip reader on /Users/nick/Documents/GoPath/src/github.com/asticode/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/MacOS/vendor/electron-darwin-amd64-v1.8.1.zip failed: zip: not a valid zip file

**Comment by asticode** [comment]
@tfnick it seems there was a problem while bundling the app. Could you 

- run `astilectron-bundler cc`
- run `astilectron-bundler -v` and paste logs here
- run the app and tell me whether this is working?

Cheers

**Comment by tfnick** [comment]
```
V400:go-astilectron-demo nick$ astilectron-bundler -v
DEBU[0000] Creating /Users/nick/Documents/GoPath/src/github.com/asticode/go-astilectron-demo/output 
DEBU[0000] Bundling for environment darwin/amd64        
DEBU[0000] Binding data                                 
DEBU[0000] Removing /var/folders/ms/hwntz0mj1sjc9t18ywlzc3jc0000gp/T/astibundler/bind 
DEBU[0000] Creating /var/folders/ms/hwntz0mj1sjc9t18ywlzc3jc0000gp/T/astibundler/bind 
DEBU[0000] Creating /var/folders/ms/hwntz0mj1sjc9t18ywlzc3jc0000gp/T/astibundler/bind/vendor_astilectron_bundler 
DEBU[0000] Creating /var/folders/ms/hwntz0mj1sjc9t18ywlzc3jc0000gp/T/astibundler/cache 
DEBU[0000] Downloading https://github.com/asticode/astilectron/archive/v0.22.0.zip into /var/folders/ms/hwntz0mj1sjc9t18ywlzc3jc0000gp/T/astibundler/cache/astilectron-0.22.0.zip 
DEBU[0003] Copying /var/folders/ms/hwntz0mj1sjc9t18ywlzc3jc0000gp/T/astibundler/cache/astilectron-0.22.0.zip to /var/folders/ms/hwntz0mj1sjc9t18ywlzc3jc0000gp/T/astibundler/bind/vendor_astilectron_bundler/astilectron.zip 
DEBU[0003] Downloading https://github.com/electron/electron/releases/download/v1.8.1/electron-v1.8.1-darwin-x64.zip into /var/folders/ms/hwntz0mj1sjc9t18ywlzc3jc0000gp/T/astibundler/cache/electron-darwin-amd64-1.8.1.zip 
DEBU[0022] Copying /var/folders/ms/hwntz0mj1sjc9t18ywlzc3jc0000gp/T/astibundler/cache/electron-darwin-amd64-1.8.1.zip to /var/folders/ms/hwntz0mj1sjc9t18ywlzc3jc0000gp/T/astibundler/bind/vendor_astilectron_bundler/electron.zip 
DEBU[0022] Creating /var/folders/ms/hwntz0mj1sjc9t18ywlzc3jc0000gp/T/astibundler/bind/resources 
DEBU[0022] Copying /Users/nick/Documents/GoPath/src/github.com/asticode/go-astilectron-demo/resources to /var/folders/ms/hwntz0mj1sjc9t18ywlzc3jc0000gp/T/astibundler/bind/resources 
DEBU[0022] Generating /Users/nick/Documents/GoPath/src/github.com/asticode/go-astilectron-demo/bind_darwin_amd64.go 
DEBU[0025] Removing /Users/nick/Documents/GoPath/src/github.com/asticode/go-astilectron-demo/output/darwin-amd64 
DEBU[0025] Creating /Users/nick/Documents/GoPath/src/github.com/asticode/go-astilectron-demo/output/darwin-amd64 
DEBU[0025] Building for os darwin and arch amd64        
DEBU[0025] Executing go build -ldflags -s -X "main.AppName=Astilectron demo" -X "main.BuiltAt=2018-06-10 00:15:02.104675611 +0800 CST m=+25.431802850" -o /Users/nick/Documents/GoPath/src/github.com/asticode/go-astilectron-demo/output/darwin-amd64/binary github.com/asticode/go-astilectron-demo 
FATA[0033] bundling failed: bundling for environment darwin/amd64 failed: building failed: # github.com/asticode/go-astilectron-demo
./my_demo.go:9:6: main redeclared in this block
        previous declaration at ./main.go:27:6
: exit status 2 

```
