### ISSUE TITLE
An error occors at sample of "Create a window"

### ISSUE THREAD

**Issue by tinymouse** [asticode/go-astilectron#118]
I tried "Quick start" in "README.md"
And tried "Create a window" section.
An error occors at the line of "w.Create()"
Does it work without an error?

**Comment by asticode** [comment]
Can you share your code ?

I've tried the following and it's working:

```go
func main() {
	// Init logs
	flag.Parse()
	astilog.FlagInit()

	// Initialize astilectron
	var a, _ = astilectron.New(astilectron.Options{
		AppName:            "My app name",
		BaseDirectoryPath:  "vendor",
	})
	defer a.Close()

	// Start astilectron
	if err := a.Start(); err != nil {
		astilog.Error(err)
	}

	// Create a new window
	var w, _ = a.NewWindow("http://127.0.0.1:4000", &astilectron.WindowOptions{
		Center: astilectron.PtrBool(true),
		Height: astilectron.PtrInt(600),
		Width:  astilectron.PtrInt(600),
	})
	if err := w.Create(); err != nil {
		astilog.Error(err)
	}

	// Blocking pattern
	a.Wait()
}
```

**Comment by tinymouse** [comment]
Thank you for your sample code. 
I tried your code in my development environment.
An error occurs at the same point.
Strictly speaking, an error does not occur, 
the program stops  at "w.Create()" and debugger says "Failed to continue"
I found two points the program stops.
1) line 169 in helpler.go, in func synchronousEvent(), at "w.write(i)", because w is nil.
Func synchronouseEvent is called at line 253 in windows.go. The 3rd argument is "w.w" 
Object w is struct "Window" and it does not have member "w"
2) line 161 in helper.go, in func synchronousFunc(), at "<-ctx.Done()"
I wonder why your code is working in your environment but not working in mine.

**Comment by asticode** [comment]
Could you paste the logs when you run `go run *.go -v` of my sample code ?

**Comment by tinymouse** [comment]
I ran "go run *.go -v" and read the log...

```
DEBU[0000] Starting...
DEBU[0000] Provisioning...
DEBU[0000] Astilectron has already been provisioned to version 0.23.0, moving on...
DEBU[0000] Provisioning Electron...
DEBU[0000] Removing directory .../vendor/electron-darwin-amd64
DEBU[0000] Downloading https://github.com/electron/electron/releases/download/v1.8.1/electron-v1.8.1-darwin-x64.zip into .../vendor/electron-darwin-amd64-v1.8.1.zip
DEBU[0000] .../vendor/electron-darwin-amd64-v1.8.1.zip already exists, skipping download...
DEBU[0000] Creating directory .../vendor/electron-darwin-amd64
DEBU[0000] Unzipping .../vendor/electron-darwin-amd64-v1.8.1.zip into .../vendor/vendor/electron-darwin-amd64
DEBU[0000] Removing .../vendor/electron-darwin-amd64...
ERRO[0000] provisioning failed: provisioning electron failed: unzipping .../vendor/electron-darwin-amd64-v1.8.1.zip into .../vendor/electron-darwin-amd64 failed: unzipping .../vendor/vendor/electron-darwin-amd64-v1.8.1.zip into .../vendor/electron-darwin-amd64 failed: astiarchive: opening overall zip reader on .../vendor/electron-darwin-amd64-v1.8.1.zip failed: zip: not a valid zip file
```

I see!
I removed "electron-darwin-amd64-v1.8.1.zip" in folder "vendor"
and I ran again.
The program work!

Thank you for you advice!
I am glad to use Astilectron.

**Comment by asticode** [comment]
Cheers
