### ISSUE TITLE
Introduce a simpler way of adding Menu Listeners

### ISSUE THREAD

**Issue by veecue** [asticode/go-astilectron#12]
Hi,
in a menu, almost every item requires an onClick listener. Is it possible to add this straight to the MenuItemOptions struct, since building a menu by hand and adding all the listeners is pretty costly.
BTW: Great project, thanks a lot!

**Comment by asticode** [comment]
@veecue great idea! I've just added an `OnClick` attribute to the `MenuItemOptions` that takes a `Listener`. It will attach to the `EventNameMenuItemEventClicked` event.

Does that fit your need? If so, you can close this issue.
Cheers

**Comment by veecue** [comment]
That's exactly what I wanted, thanks a lot
