### ISSUE TITLE
Debug programs in BrowserWindow with VS Code

### ISSUE THREAD

**Issue by tinymouse** [asticode/go-astilectron#120]
I use VS Code to make and debug programs made with Electron.
And use the following tip to debug programs running on renderer process.

vscode-recipes/Electron at master · Microsoft/vscode-recipes
(https://github.com/Microsoft/vscode-recipes/tree/master/Electron)

I also use VS Code to make programs made with Astilectron.
Can I debug programs running in BrowserWindow in the similar way?

**Comment by asticode** [comment]
My guess is that it's going to be difficult since some of the code will be JS code that you won't be able to debug.

Maybe you could take a look at [this issue](https://github.com/asticode/go-astilectron/issues/105).

Does that answer your question?

**Comment by tinymouse** [comment]
Thank you for your comment.

I succeeded to debug programs running in BrowserWindow with VS Code.

First, edit "vendor/astilectron/main.js" and add the code after line 28.
```
app.commandLine.appendSwitch('remote-debugging-port', '9223')
```
And edit "launch.json" of VS Code.
```
    "configurations": [
        {
            "name": "Launch Program",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}",
        },
        {
            "name": "Attach Renderer Process",
            "type": "chrome",
            "request": "attach",
            "webRoot": "${workspaceRoot}",
            "port": 9223
        },
```

I hope Astilectron accepts the flag "--remote-debugging-port=9999" and throws it to Electron.

**Comment by asticode** [comment]
@tinymouse you don't have to edit the `main.js` file you can use the [ElectronSwitches option](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L75) instead when you declare `Astilectron`:

```go
a, _ := astilectron.New(astilectron.Options{
  ElectronSwitches: []string{
    "--remote-debugging-port",
    "9223",
  }
})
```

That way the command line switch will be sent to Electron and this is much simpler.

Does that fix your issue?

**Comment by tinymouse** [comment]
This is what I wanted to know! I'm grad to know that. 

Thank you for your answer. I'm sure to fix this issue.
