### ISSUE TITLE
the js callback，can you help me？

### ISSUE THREAD

**Issue by BeanWei** [asticode/go-astilectron#121]
the message from JS to Go, Go get the message and make the payload, then the js callback get the payload.

But why I can't see the callback 

`{"level":"debug","msg":"Astilectron says: {\"name\":\"window.event.message\",\"targetID\":\"1\",\"message\":{\"name\":\"Upload\",\"payload\":[{\"describe\":\"2\",\"tags\":\"3\",\"title\":\"1\"}]},\"callbackId\":\"1\"}","time":"2018-07-03T08:19:06+08:00"}
{"level":"debug","msg":"\u0026[{1 2 3 }]","time":"2018-07-03T08:19:06+08:00"}
{"level":"debug","msg":"Sending to Astilectron: {\"name\":\"window.cmd.message.callback\",\"targetID\":\"1\",\"callbackId\":\"1\",\"message\":{\"name\":\"Upload.callback\",\"payload\":\"I HAVE RECIVEID THIS MESSAGE\"}}","time":"2018-07-03T08:19:06+08:00"}
{"level":"debug","msg":"Astilectron says: {\"name\":\"window.event.blur\",\"targetID\":\"1\"}","time":"2018-07-03T08:19:08+08:00"}

`
in my js code , console.log(message), but nothing , i use the *.go -v

can you help me.

**Comment by asticode** [comment]
@BeanWei can you paste both your GO and JS code?

**Comment by BeanWei** [comment]
GO:
`// handleMessages handles messages
func handleMessages(a *astilectron.Astilectron, _ *astilectron.Window, m bootstrap.MessageIn) (payload interface{}, err error) {
	switch m.Name {
	case "Upload":
		{
			uploadinfo := &UploadInfo{}
			err := json.Unmarshal(m.Payload, uploadinfo)
			if err != nil {
				return err.Error(), nil
			}
			astilog.Debug(uploadinfo)
			return "I HAVE RECIVEID THIS MESSAGE", nil
		}
        
               ......
       return
`

JS:
`
astilectron.sendMessage({
          name: "Upload",
          payload:  uploadinfo
        },function(message){
          console.log("I have received:" + message)
          this.posts = message.payload
          console.log(this.posts)
        })
`
@asticode  , thanks your review! :+1:

**Comment by asticode** [comment]
where do you look for the `console.log` results ?

**Comment by BeanWei** [comment]
At the windows terminal（cmd）， I use the `go run main.go message.go ······ -v`

also, I had show the messageat in html, but nothing appear too.

**Comment by asticode** [comment]
@BeanWei when you use `console.log` in JS, this will display the message in the developer console of the Browser Window, not in your terminal. In order to see the message, you have to [open the window's dev tools](https://github.com/asticode/go-astilectron/blob/master/window.go#L381) and open the `Console` tab. You will see your message there.

Does that fix your issue?

**Comment by asticode** [comment]
Sounds like a good idea, will do.

Cheers
