### ISSUE TITLE
initDataDirectory  bug?

### ISSUE THREAD

**Issue by 107295472** [asticode/go-astilectron#125]
func (p *Paths) initDataDirectory(appName string) {
	// if v := os.Getenv("APPDATA"); len(v) > 0 {
	// 	p.dataDirectory = filepath.Join(v, appName)
	// 	return
	// }
	p.dataDirectory = p.baseDirectory
}
Always looking for this address     C:\Users\Administrator\AppData\Roaming

**Comment by asticode** [comment]
putting the data in the APPDATA folder is the expected behavior on windows
