### ISSUE TITLE
Run directly without bundling

### ISSUE THREAD

**Issue by lansi951** [asticode/go-astilectron#129]
I want to run like `electron .` command for testing app without bundling process.
I wish I could see index.html changed in real time.
What should i do?

**Comment by asticode** [comment]
are you using the bundler right now ?

**Comment by lansi951** [comment]
@asticode Yes. `astilectron-bundler` using now.

**Comment by asticode** [comment]
ok then you need to make sure the data is binded by running `astilectron-bundler bd -v` but then all you need to do is run `go run *.go -v` to run your app.

Does that answer your question?

**Comment by lansi951** [comment]
@asticode It is work(`go build; ./app.exe` on powershell).
But astilectron load index.html from `\AppData\Roaming\resources\app` and I cant modify it in real time.
Why no load file from `GOPATH\src\resources\app`?

**Comment by asticode** [comment]
@lansi951 I've added a `DataDirectoryPath` option in case you want to override the default `Windows` value which is in the `APPDATA` folder.

Doest that fix your issue?

**Comment by lansi951** [comment]
@asticode It works. but, if set `DataDirectoryPath: "D:\\go\\src\\demo\\resources"`, astilectron load `index.html` from `D:\\go\\src\\demo\\resources\\resources`(resource x 2).

**Comment by asticode** [comment]
@lansi951 sure because your data directory should be "D:\\go\\src\\demo" in your case since this directory will contain other suff than `resources` (`vendor` stuff for instance)

**Comment by asticode** [comment]
the `resources` folder will be created by `astilectron`.

Does that fix your issue?

**Comment by lansi951** [comment]
@asticode Thank you! I fixed this issue!

**Comment by adracea** [comment]
> @lansi951 I've added a `DataDirectoryPath` option in case you want to override the default `Windows` value which is in the `APPDATA` folder.
> 
> Doest that fix your issue?

@asticode I really think that some of these little things should be a bit more documented , I've had to run through the issues to find halves of my questions and quarters of answers that I then had to patch together :)) . Would you need some help with that ?

**Comment by asticode** [comment]
Sure!
