### ISSUE TITLE
Can we use Angular with go-astilectron for making the Desktop sofwares?

### ISSUE THREAD

**Issue by madhuni** [asticode/go-astilectron#131]
Hi...I want to use Angular for developing the Desktop software using go-astilectron. Can somebody having the experience with the same, define that how we can proceed with Angular and "go-astilectron"?

I also I want to do the real-time development to see the changes as we can do with electron without making build each and every time when I need to see something. Is that possible with "go-astilectron"?

**Comment by asticode** [comment]
@madhuni I haven't used Angular myself but I don't see why you couldn't.

Indeed, once you've created a window you tell it which .html page to open. This page can contain anything you want, including Angular. If you take a lookf at the [demo](https://github.com/asticode/go-astilectron-demo/blob/master/resources/app/index.html), you can see I've included custom scripts. You can do the same with Angular.

Regarding real-time development, if you're only updating your javascript/css code all you need to do is refresh the page you're on and it will be updated, no need to rebuild the app.

Does that answer your questions?

**Comment by damiandominella** [comment]
Just for information, Angular integration is quite simple but remember to set correctly the **base href** value in your index.html, changing it from its default value "/" to ".". 

If this is not done, any external resource (css, js) will be searched starting from C:\ (in a Windows environment), causing a NOT FOUND error.

```
<head>
  <title></title>
  <base href="." />
  <!-- relative sources -->
</head>
```

**Comment by asticode** [comment]
Thanks a lot for the information ! ❤️
