### ISSUE TITLE
App has crashed when I closed all window

### ISSUE THREAD

**Issue by Grayon** [asticode/go-astilectron#133]
> Event: 'window-all-closed'
> Emitted when all windows have been closed.
> 
> If you do not subscribe to this event and all windows are closed, the default behavior is to quit the app; however, if you subscribe, you control whether the app quits or not. If the user pressed Cmd + Q, or the developer called app.quit(), Electron will first try to close all the windows and then emit the will-quit event, and in this case the window-all-closed event would not be emitted.

I think it is because Electron's default event, and app quit.
But the log said `App has crashed`

**Comment by asticode** [comment]
@Grayon what should be the fix? that the log says `App has stopped` instead?

**Comment by Grayon** [comment]
I think it's not a crash, it's a close action.
And I want to know, how to run my electron code with astilectron?
like handle `window-all-closed` event myself, and call other methods.
I don't want to quit app when window all closed.

**Comment by asticode** [comment]
@Grayon you can't run electron code with astilectron. The goal of this project is to write GO code to handle electron, not JS code directly.

However what you're requesting makes sense and I could see a `DoNotQuitWhenAllWindowsClosed` attribute for [Astilectron](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L69) that listens to `window-all-closed` event, and `preventDefault` when the option is set to `true`.

Would that fix your issue?

**Comment by Grayon** [comment]
I find there is a `HideOnClose` in `WindowOptions` can do that, but I don't know how to show it again.

**Comment by asticode** [comment]
It depends what your workflow is, but for one of my project, the tray was the item that could show the window again. Does that make sense in your case?
