### ISSUE TITLE
Modules Compatibility

### ISSUE THREAD

**Issue by PeterBooker** [asticode/go-astilectron#134]
I am not sure this is an issue per say, especially given Modules (vgo) only been added in the current 1.11 beta2, but I wanted to see what you thought.

I came across two odd behaviours:

1) Modules by default imports the last tag (v0.5.0 as I write this), which contains an error (helper.go line 14 has a bad import name). It took me a while to work out that I could get round this by specifying `go get github.com/asticode/go-astilectron@master` to get the latest commit. This could be solved with new tag but familiarity with the Modules feature solves it too.

2) I tried starting off with the demo, which worked flawlessly inside GOPATH, but in its own directory (using the Modules feature) it errors after running `astilectron-bundler -v`, with the message:
`{"app_name":"","level":"fatal","msg":"bundling failed: bundling for environment windows/amd64 failed: building failed: go: cannot use modules with build cache disabled\n: exit status 1","time":"2018-08-01T20:28:18+01:00"}`

I do not understand why this happens (not familiar with go-astilectron at all), but wanted to document the experience in case it was useful to you.

**Comment by asticode** [comment]
@PeterBooker I didn't have the chance to try modules yet, so thanks for your feedback!

1. You're right, I should create tags along the way but unfortunately I forget. I'll try to remember but in the meantime this is a good thing you can specify `@master`.

2. The error seems to be happening in the [bundler](https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go#L342) when building the GO binary. If you scroll up a little bit in the logs you will see the command that is executed in a log starting with "Executing". If you run it manually, does it output the same error?

**Comment by PeterBooker** [comment]
Sure, the command was:
`go build -ldflags "-s -X \"main.AppName=Astilectron demo\" -X \"main.BuiltAt=2018-08-02 10:05:59.8390291 +0100 BST m=+6.041950001\" -H windowsgui -o D:\Projects\go\demo\output\windows-amd64\binary ."`

Running this manually gave the output:
```
go: finding github.com/asticode/go-astilectron-bootstrap latest
go: finding github.com/asticode/go-astichartjs latest
go: finding github.com/asticode/go-astilectron-bundler latest
go: finding github.com/asticode/go-bindata latest
go: finding github.com/akavel/rsrc/rsrc latest
go: finding github.com/akavel/rsrc latest
go: downloading github.com/akavel/rsrc v0.0.0-20170831122431-f6a15ece2cfd
go: downloading github.com/asticode/go-bindata v0.0.0-20151023091102-a0ff2567cfb7
go: finding github.com/asticode/go-astilectron v0.0.0-20180729165724-96af54c68dc6
# github.com/asticode/go-astilectron-demo
.\bind_windows_amd64.go:537:6: Asset redeclared in this block
        previous declaration at .\bind.go:3:34
.\bind_windows_amd64.go:623:6: AssetDir redeclared in this block
        previous declaration at .\bind.go:7:39
.\bind_windows_amd64.go:728:6: RestoreAssets redeclared in this block
        previous declaration at .\bind.go:11:38
```

**Comment by asticode** [comment]
@PeterBooker before being able to bundle the demo and as mentioned in the [first step of the readme](https://github.com/asticode/go-astilectron-demo#step-1-install-the-demo) you need to remove `bind.go`. Could you try again after having removed `bind.go`?

**Comment by PeterBooker** [comment]
Embarrassing, I had missed that step while going through the process again this morning. It now successfully runs the command:
`go build -ldflags "-s -X \"main.AppName=Astilectron demo\" -X \"main.BuiltAt=2018-08-02 10:05:59.8390291 +0100 BST m=+6.041950001\" -H windowsgui" -o D:\Projects\go\demo\output\windows-amd64\binary.exe .`

However, the command `astilectron-bundler -v` still fails at the same point and when I try to run the `\output\windows-amd64\binary.exe` file it gives this error:

```
Error launching app

Unable to find Electron app at C:\Users\mail\AppData\Roaming\Astilectrondemo\vendor\astilectron\main.js

Cannot find module 'C:\Users\mail\AppData\Roaming\Astilectrondemo\vendor\astilectron\main.js'
```

**Comment by asticode** [comment]
@PeterBooker I think I know what was happening. Could you fetch the last changes in the bundler, run `go install` on it (like mentioned in its README) and try again?

**Comment by PeterBooker** [comment]
I updated the bundler with the instructions from `https://github.com/asticode/go-astilectron-bundler`.

Re-running `astilectron-bundler -v` got the same output as before:
```
{"app_name":"","level":"debug","msg":"Executing go build -ldflags -X \"main.AppName=Astilectron demo\" -X \"main.BuiltAt=2018-08-02 13:19:24.6540057 +0100 BST m=+5.871952201\" -H windowsgui -s -o D:\\Projects\\go\\demo\\output\\windows-amd64\\binary .","time":"2018-08-02T13:19:24+01:00"}
{"app_name":"","level":"fatal","msg":"bundling failed: bundling for environment windows/amd64 failed: building failed: go: cannot use modules with build cache disabled\n: exit status 1","time":"2018-08-02T13:19:24+01:00"}
```

If there is anything else I can do to help just let me know.

**Comment by asticode** [comment]
Mmm I'm not familiar enough with that issue, if anyone else has an idea I'm all ears.

**Comment by PeterBooker** [comment]
Thank you for trying, I appreciate it. I did some more digging around the `GOCACHE` env var, which I saw from your commit.

It is set to `C:\Users\mail\AppData\Local\go-build` by default, but that does not seem to work. So I changed it to another drives temp directory and that now allows the bundler command to finish:

```
{"app_name":"","level":"debug","msg":"Executing go build -ldflags -s -X \"main.AppName=Astilectron demo\" -X \"main.BuiltAt=2018-08-02 13:57:25.2176428 +0100 BST m=+5.156962701\" -H windowsgui -o D:\\Projects\\go\\demo\\output\\windows-amd64\\binary .","time":"2018-08-02T13:57:25+01:00"}
{"app_name":"","level":"debug","msg":"Moving D:\\Projects\\go\\demo\\output\\windows-amd64\\binary to D:\\Projects\\go\\demo\\output\\windows-amd64\\Astilectron demo.exe","time":"2018-08-02T13:57:36+01:00"}
```

However, the binary which is created still shows the same errors as before (the missing `main.js`). I will keep digging and let you know if I manage to find the problem. I am starting to get to grips with how it works now.

**Comment by asticode** [comment]
I think that the fact that the bundler process finishes properly is very good news! 

Regarding the missing main.js, check that `go-astilectron` is up to date, then rebuild the bundler then retry. If that still doesn't work, please paste logs from both the bundler and the app with the `-v` flag.

**Comment by PeterBooker** [comment]
Sorry for the slow response. I wanted to dedicate some more time to debugging myself. The good news is that I have found a way to get it working, the down side is that I do not understand **why** it works.

If I try the `astilectron-bundler -v` after following the instructions I get the error:
```
{"app_name":"","level":"debug","msg":"Executing go build -ldflags -s -X \"main.AppName=Astilectron demo\" -X \"main.BuiltAt=2018-08-02 21:47:16.0048014 +0100 BST m=+17.090868001\" -H windowsgui -o D:\\Projects\\go\\demo\\output\\windows-amd64\\binary .","time":"2018-08-02T21:47:16+01:00"}
{"app_name":"","level":"fatal","msg":"bundling failed: bundling for environment windows/amd64 failed: building failed: go: cannot use modules with build cache disabled\n: exit status 1","time":"2018-08-02T21:47:16+01:00"}
```

However, if I set `GOCACHE` to the exact same value it already contains:
```
go env GOCACHE
C:\Users\mail\AppData\Local\go-build
set GOCACHE=C:\Users\mail\AppData\Local\go-build
```

The  `astilectron-bundler -v` command now successfully completes and the resulting binary works perfectly. Do you have any idea why that might happen? Perhaps this is an issue with my own local Go install, rather than astilectron?

**Comment by asticode** [comment]
@PeterBooker this is because of [this](https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go#L348).

If your environment variable is not set, when the `go build` command is executed in a child process, somehow `go env GOCACHE` will return nothing. However, if the environment variable is set, it will return something and process will run successfully.

This is definitely something that should be fixed in the `bundler` if possible.

However I don't know why the `go build` command executed in the child process loses the information about GOCACHE.

PS: the commit adding the GOCACHE in the `go env` commit can be found [here](https://groups.google.com/forum/#!topic/golang-checkins/3WDILAmX41o). Unfortunately this is not exported as it rests in an `internal` package.

**Comment by PeterBooker** [comment]
Ah, I see now. So the other `go` tools can get the default but anything external cannot. I had assumed `os.Getenv` would return the same as `go env GOCACHE` but now I see that `os.Getenv` always returns blank, as `GOCACHE` is not set locally.

I had assumed that as `go env GOCACHE` returned a value that the Go installer must have set the env var. I had not even considered checking to see, or that the go tools might just return a default. So really, this is a problem with my local Go setup.

I had a little play and cannot see a way to solve this from the bundler without reproducing the [defaultDir](https://github.com/golang/go/blob/master/src/cmd/go/internal/cache/default.go#L74) function. Perhaps a more blunt error message would help in the future instead, for those like me who do not know about GOCACHE (and how Go's caching works)?

Thank you for the time spent working through this with me, it is appreciated. I can continue helping my friend get into Go now (He is incredibly excited about being able to easily make an electron app). I will let you close the issue as you see fit, it seems primarily a problem with my local Go setup.

**Comment by asticode** [comment]
Cheers
