### ISSUE TITLE
support webview?

### ISSUE THREAD

**Issue by mofeiwo** [asticode/go-astilectron#135]
support webview?
I want to open some pages by different request headers.

**Comment by asticode** [comment]
@mofeiwo I think you're in luck, I've added [WindowLoadOptions](https://github.com/asticode/go-astilectron/blob/master/window.go#L133) recently. You should be able to add headers with the `ExtraHeaders` attribute. Check out the [electron doc](https://github.com/electron/electron/blob/v1.8.1/docs/api/browser-window.md#winloadurlurl-options).

Does it fix your issue?

**Comment by mofeiwo** [comment]
ok. I try it

**Comment by mofeiwo** [comment]
@asticode 
Support proxy IP？

**Comment by mofeiwo** [comment]
@asticode 
I try WindowLoadOptions today. 
When I used different Cookie to log in to the site，display the same account information.
Where am I wrong?
below part of my code

`
Windows: []*bootstrap.Window{{
			Homepage:       "https://www.a.com",
			Options: &astilectron.WindowOptions{
				BackgroundColor: astilectron.PtrStr("#333"),
				Center:          astilectron.PtrBool(true),
				Height:          astilectron.PtrInt(1280),
				Width:           astilectron.PtrInt(800),
				Frame:           astilectron.PtrBool(true),
				EnableLargerThanScreen:      astilectron.PtrBool(true),
				Load: &astilectron.WindowLoadOptions{
					ExtraHeaders: "Cookie: 123456",
					HTTPReferer:  "https://www.a.com/",
					UserAgent:    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36",
				},
			},
		},
		{
			Homepage:       "https://www.b.com",
			Options: &astilectron.WindowOptions{
				BackgroundColor: astilectron.PtrStr("#666"),
				Center:          astilectron.PtrBool(true),
				Height:          astilectron.PtrInt(1280),
				Width:           astilectron.PtrInt(800),
				Load: &astilectron.WindowLoadOptions{
					ExtraHeaders: "Cookie:7890123",
					HTTPReferer:  "https://www.b.com/",
					UserAgent:    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7",
				},
			},
		}},
`

**Comment by asticode** [comment]
Mmm I'm not sure the `Cookie` header is taken into account... Electron might have its own cookie you can't mess with... but that's only a guess...

**Comment by mofeiwo** [comment]
Through tools by Charles，custom Cookie is not included in the http request.

**Comment by asticode** [comment]
OK so that explains your last issue? 

May I close this issue?

**Comment by mofeiwo** [comment]
How to customize Cookie？

**Comment by asticode** [comment]
@mofeiwo it seems like a Charles issue, not an electron issue isn't it ?

**Comment by mofeiwo** [comment]
@asticode 
I want to know Whether to support customized Cookie  by  `go-astilectron` ?

**Comment by asticode** [comment]
`go-astilectron` supports customized Cookie through the `ExtraHeaders` attribute only

**Comment by mofeiwo** [comment]
I  try it . Unable to modify.

**Comment by asticode** [comment]
Isn't it because Charles is blocking the Cookie header?

**Comment by mofeiwo** [comment]
No. `Charles `  Used to test whether to modify.

I used customized `Cookie` , No change in page information.
