### ISSUE TITLE
How to make a hyperlink that opens default browser upon click?

### ISSUE THREAD

**Issue by rcholic** [asticode/go-astilectron#136]
I was wondering if there's a way to create a hyperlink that opens the browser?

**Comment by asticode** [comment]
Do you mean:

- you're in an external browser (like Chrome and Firefox)
- you click on this special link
- it opens up your app at the correct location

?

**Comment by gwangsd** [comment]
No I mean the opposite. A hyperlink in my app, when you click it, a new browser window opens

**Comment by rcholic** [comment]
I was asking if it is possible to open the default browser (e.g. Chrome) from inside of a go-astilectron based app when user clicks a hyperlink in the app UI.

**Comment by rcholic** [comment]
never mind, I found this solution: https://gist.github.com/hyg/9c4afcd91fe24316cbf0

**Comment by asticode** [comment]
Cheers
