### ISSUE TITLE
When closing app send message to js

### ISSUE THREAD

**Issue by awerffeli** [asticode/go-astilectron#138]
Hi
I have an application with a single window. When I close the window, I'd like to to trigger a logout in my js app. However when I click the close button on the window my Messages to the js sent via `window.SendMessage(...` are not received anymore by js as it seems the tcp connection has already been closed. Is there any solution to this? I have tried with the  `HideOnClose` and then closing the app in the callback, which worked but is not a viable solution because it close the app when i click on minimize window. Is there a better solution to this?

**Comment by awerffeli** [comment]
I found a solution by injecting electron into the new window. 
```
var w *astilectron.Window
		w, err = a.NewWindow(fmt.Sprintf("http://%s/", addr), &astilectron.WindowOptions{
			//inject electron into window
			Custom: &astilectron.WindowCustomOptions{
				Script: "const electron = require('electron');",
			},
		})
```

In the js part I did something like this
```
document.addEventListener('astilectron-ready', () => {

  if (typeof electron === 'object') {
    let electronApp = electron.remote.app

    electronApp.on('before-quit', () => {
        //do something before quit
    })
  }
})
```

**Comment by asticode** [comment]
@awerffeli I think you can add `const electron = require('electron')` at the top of your js directly, without injecting it with GO.

Does it work ?
