### ISSUE TITLE
Prevent launching multiple instances of go-astilectron app

### ISSUE THREAD

**Issue by cbairy** [asticode/go-astilectron#139]
Hi asticode,
Is there any way to prevent astilectron app from opening another instance when there is a current one running in the OS?
Thanks,
Chandrakanth.

**Comment by asticode** [comment]
@cbairy for now there's no method to do this in `go-astilectron`.

I won't have time to work on this anytime soon therefore I'm welcoming PRs.

Here is the way to do it:
- add a `SingleInstance` option to [Options](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L69)
- pass this value as an argument when [executing Electron](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L265)
- in [astilectron](https://github.com/asticode/astilectron/blob/master/main.js#L16), parse the arg value and implement the [Electron's callback](https://github.com/electron/electron/blob/v0.36.10/docs/api/app.md#appmakesingleinstancecallback) when value is `true`.

NOTE: do remember to increment the value of [idx](https://github.com/asticode/astilectron/blob/master/main.js#L16).

Cheers
