### ISSUE TITLE
about event handler

### ISSUE THREAD

**Issue by xiusin** [asticode/go-astilectron#142]
I want to clicking the close button does not close the program, how to do it?

**Comment by asticode** [comment]
@xiusin can you paste your code?

**Comment by asticode** [comment]
OK got it.

No need to add all those listeners, you can simply use [this attribute](https://github.com/asticode/go-astilectron/blob/master/window.go#L126) when creating a window.

Does this fix your issue?

**Comment by xiusin** [comment]
@asticode Yes, that can be solved. Thank you.

**Comment by akzhou** [comment]
hello @asticode！ close event work on windows 10,but not on mac 10.15.1.
how to do it?
```
//EventNameWindowEventMinimize work
Window.On(astilectron.EventNameWindowEventMinimize, func(e astilectron.Event) (deleteListener bool) {
		fmt.Println("EventNameWindowEventMinimize----------->>>>>>>>>>>>")
		return false
	})

////log
2020/02/26 13:46:01 Astilectron says: {"name":"window.event.minimize","targetID":"1"}
EventNameWindowEventMinimize----------->>>>>>>>>>>>

//close window not work 
Window.On(astilectron.EventNameWindowEventClosed, func(e astilectron.Event) (deleteListener bool) {
		fmt.Println("EventNameWindowEventClosed----------->>>>>>>>>>>>")
		return false
	})
	Window.On(astilectron.EventNameWindowCmdClose, func(e astilectron.Event) (deleteListener bool) {
		fmt.Println("EventNameWindowCmdClose----------->>>>>>>>>>>>")
		return false
	})
	Window.On(astilectron.EventNameAppClose, func(e astilectron.Event) (deleteListener bool) {
		fmt.Println("EventNameAppClose----------->>>>>>>>>>>>")
		return false
	})
	Window.On(astilectron.EventNameAppCmdQuit, func(e astilectron.Event) (deleteListener bool) {
		fmt.Println("EventNameAppCmdQuit----------->>>>>>>>>>>>")
		return false
	})
	Window.On(astilectron.EventNameAppCrash, func(e astilectron.Event) (deleteListener bool) {
		fmt.Println("EventNameAppCrash----------->>>>>>>>>>>>")
		return false
	})
//log
2020/02/26 13:46:21 Astilectron says: {"name":"app.cmd.quit","targetID":"app"}
2020/02/26 13:46:21 Stopping...
2020/02/26 13:46:21 astikit: stopping worker...
2020/02/26 13:46:21 Closing...

```

**Comment by asticode** [comment]
You're right, that is broken right now because of the use of go routines [here](https://github.com/asticode/go-astilectron/blob/master/executer.go#L24) and [here](https://github.com/asticode/go-astilectron/blob/master/dispatcher.go#L60).

I'll have to think about it a little bit. Unfortunately I won't have time anytime soon so I'm afraid it won't be fixed quickly.

**Comment by dreisel** [comment]
> OK got it.
> 
> No need to add all those listeners, you can simply use [this attribute](https://github.com/asticode/go-astilectron/blob/master/window.go#L126) when creating a window.
> 
> Does this fix your issue?

the attribute has moved...
its now [here](https://github.com/asticode/go-astilectron/blob/master/window.go#L141)
