### ISSUE TITLE
undefined: EventMessage

### ISSUE THREAD

**Issue by Incrementing** [asticode/go-astilectron#143]
Trying to use the following code from the README.md example:
```go
w.OnMessage(func(m *EventMessage) interface{} {
        var s string
        m.Unmarshal(&s)

        if s == "hello" {
                return "world"
        }
        return nil
})
```
But my IDE (GoLand) can't seem to find EventMessage

**Comment by asticode** [comment]
mmmm indeed, this should be `astilectron.EventMessage`.

Does it work when you update?

**Comment by Incrementing** [comment]
Yes, that fixed it right away. Probably should have tried something like that before opening an issue. Thanks for the help.

**Comment by asticode** [comment]
Nah you were right to create an issue, I will update the doc accordingly.

Cheers
