### ISSUE TITLE
Visible Artifacting on Linux

### ISSUE THREAD

**Issue by JujharSingh** [asticode/go-astilectron#145]
![image](https://user-images.githubusercontent.com/9494428/46891742-69953500-cec7-11e8-9411-06ec89f2a6d6.png)
Chromium seems to have no problems but the go-astilectron window does?

**Comment by asticode** [comment]
Mmm this is weird. Unfortunately at this point it is an Electron issue and there's nothing I can do. Maybe you can check on Google if anybody has a similar problem using Electron and report back here.

**Comment by JujharSingh** [comment]
It's a problem with the libfreetype package, downgrading back to 2.8-0 fixes the issue.
