### ISSUE TITLE
old electron version

### ISSUE THREAD

**Issue by IIInsomnia** [asticode/go-astilectron#147]
Version 1.8.1 of Electron is quite old. Could it be upgraded to the latest version or is it not compatible with astilectron-go?

**Comment by asticode** [comment]
@IIInsomnia unless there have been changes that break compatibility, upgrading to a newer electron version should not be an issue.

Nonetheless, I have to test it a little bit.

If anyone want to test whether its app is working properly with the new electron version, all you have to do is:

 - update the version [here](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L23)
- build the bundler if you're using it
- build your app from scatch
- run your app and see whether everything is working

**Comment by Guillaume695** [comment]
I haven't tested all the features yet but I just tried with version 'v4.0.0-beta.4' and it worked right away :tada:  nice job!

**Comment by asticode** [comment]
Is there any reason we shouldn't wait for the `v4.0.0` to be stable?

I'd rather avoid bumping to a `v3.*.*` or a `beta` version if possible.

**Comment by bright-light-in-the-night** [comment]
@asticode and @Guillaume695 could you tell me how you did the step "build the bundler if you're using it"?
I have no problem building the app from scratch. I have changed the version of electron [here](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L23), but when I build the app, I still have the electron 1.8.1
PS: the app runs fine with version 1.8.1, but I need some new features of electron.

**Comment by asticode** [comment]
@bright-light-in-the-night you only need it if you're using the bootstrap.

Here are the steps:

```
$ cd $GOPATH/github.com/asticode/go-astilectron-bundler
$ go install ./astilectron-bundler
```

**Comment by bright-light-in-the-night** [comment]
Thanks!
I ran into [this post](https://github.com/asticode/go-astilectron/issues/57) that told me to `make`.
So I ran:
```cd /home/user/go/src/github.com/asticode/go-astilectron-bundler
make
```
Then I rebuild the app and now it's updated :relieved:

**Comment by asticode** [comment]
Hey guys,

Juste to let you know that I've bumped the Electron version to `4.0.1`. Don't forget to run `go install github.com/asticode/go-astilectron-bundler/astilectron-bundler` if you're using the bundler.

As usual, let me know if you're experiencing any problem.

Closing the issue for now, but feel free to reopen it if anything goes wrong.

Cheers
