### ISSUE TITLE
Change label of menus dynamically

### ISSUE THREAD

**Issue by cbairy** [asticode/go-astilectron#149]
Hi asticode,
Is there any way we can change the Label option of MenuItemOptions in SubMenu dynamically. I configure the options using bootstrap like
		MenuOptions: []*astilectron.MenuItemOptions{{
			Label: astilectron.PtrStr("File"),
			SubMenu: []*astilectron.MenuItemOptions{
				{
					Label: astilectron.PtrStr("About"),
					OnClick: func(e astilectron.Event) (deleteListener bool) {

Say that I want to rename Label as "Info" instead of "About" in the event listener. Is this possible?

**Comment by asticode** [comment]
@cbairy there's a simple way to achieve what you want to do:

- First you need to retrieve the `Menu` you want to update. If you're using the bootstrap, use the `OnWait` attribute.
- Then you need to retrieve the proper `MenuItem` within the `Menu`. To do that, you can use both `SubMenu` and `Item` functions to locate your `MenuItem`
- Once you have the `MenuItem`, you simply have to use its `SetLabel` method to update the label

Does it fix your issue?

**Comment by asticode** [comment]
What do you mean by "its not reflected in the actual menu of the window"?

Can you share screenshots if possible?

**Comment by cbairy** [comment]
![image](https://user-images.githubusercontent.com/3469880/48010378-7a8e3a80-e143-11e8-9a0f-3dfd203cf748.png)
![image](https://user-images.githubusercontent.com/3469880/48010422-91cd2800-e143-11e8-8264-01ff5dc0d62f.png)
![image](https://user-images.githubusercontent.com/3469880/48010536-cc36c500-e143-11e8-9304-ba4c806fd80f.png)
![image](https://user-images.githubusercontent.com/3469880/48010563-dbb60e00-e143-11e8-86ed-3a5749c98a77.png)
![image](https://user-images.githubusercontent.com/3469880/48010597-e7a1d000-e143-11e8-9268-0b87131ccbf4.png)

As you can see, labels in the logs are seen changed but the label in menu remains the same.

I used Astilectron-Demo project and 
Added toggleMenu *astilectron.MenuItem as a variable in the main package. Code changes as you suggested in below.
		OnWait: func(_ *astilectron.Astilectron, ws []*astilectron.Window, m *astilectron.Menu, _ *astilectron.Tray, _ *astilectron.Menu) error {
			w = ws[0]
			toggleMenu, _ = m.Item(0, 0)
			astilog.Infof("onwait")
			return nil
		}

		MenuOptions: []*astilectron.MenuItemOptions{{
			Label: astilectron.PtrStr("File"),
			SubMenu: []*astilectron.MenuItemOptions{
				{
					Label: astilectron.PtrStr(about),
					OnClick: func(e astilectron.Event) (deleteListener bool) {
						log.Println("label", *e.MenuItemOptions.Label)
						isChecked := false
						if about == "About" {
							isChecked = true
							about = "Information"
						} else {
							isChecked = false
							about = "About"
						}
						if err := bootstrap.SendMessage(w, "changeabout", isChecked, func(m *bootstrap.MessageIn) {
							astilog.Infof("about has been changed")
						}); err != nil {
							log.Println(err)
							astilog.Error(errors.Wrap(err, "sending about event failed"))
						}
						err := toggleMenu.SetLabel(about)
						astilog.Error(err)
						return
					},
				},
				{Role: astilectron.MenuItemRoleClose},
			}
