### ISSUE TITLE
How about making tag for recent update?

### ISSUE THREAD

**Issue by pankona** [asticode/go-astilectron#150]
Hello!

It seems the latest tag (v0.5.0) was created at Aug 2017, a little old.
Currently if go mod is enabled it causes build error because the v0.5.0 still referes go-astitools/zip but go-astilools's latest doesn't exist it.

JFYI, about go mod's behavior to resolve dependencies:
- go-astilectron has tag. Latest is v0.5.0. If version is not specfied version, then latest (v0.5.0) will be used.
- go-astitools doesn't has tag. then lastet will be used.

I think it is easy solution to bump version by making tag (like v0.6.0) not to refer deprecated packages (like go-astitools/zip) to support go mod.

I'm happy if you consider to bump up! :)

Thanks!

**Comment by asticode** [comment]
You're right!

I've added the `v0.6.0` tag.

Closing this issue now.

Cheers

**Comment by aparvizi** [comment]
با سلام
واقعیت اینه که معلوم نیست .
فعلا امکان واردات بااین دلار نیست -
اون مورد با دلار ۳۵۰۰ خرید شده بود 
قیمت جدید ۵ برابر میشه و بعیده کسی بخره -
فعلا منتظر ثبات بازار هستیم.
ممنون

**Comment by asticode** [comment]
@aparvizi sorry I didn't understand. Could you translate your message in english?

**Comment by pankona** [comment]
@asticode 
Hi! Thank you updating! I'm very happy! :)
Cheeeers!
