### ISSUE TITLE
How to Open Dev Tools

### ISSUE THREAD

**Issue by komyg** [asticode/go-astilectron#156]
Hi,

I am new to Astilectron and I have a very basic question: how can I open the dev tools for my window?

I am creating the window like this:

```
window := []*bootstrap.Window{{
		Homepage: "http://localhost:3000",
		Options: &astilectron.WindowOptions{
			Center:          astilectron.PtrBool(true),
			AlwaysOnTop: 		 astilectron.PtrBool(true),
			Transparent: 		 astilectron.PtrBool(true),
			Closable: 			 astilectron.PtrBool(false),
			Minimizable: 		 astilectron.PtrBool(false),
			Frame: 				 	 astilectron.PtrBool(true),
			Movable:				 astilectron.PtrBool(true),
			SkipTaskbar: 		 astilectron.PtrBool(false),
			WebPreferences:  &astilectron.WebPreferences {
				DevTools: astilectron.PtrBool(true),
			},
		},
	}}
```

And I am running the bootstrap like this:
```

	err := bootstrap.Run(bootstrap.Options{
		ResourcesPath: "./build",
		Windows: window,
		Debug: true,
	})
```

But the dev tools window does't open and whenever I type: `Ctrl`+ `Shift` + `I` nothing happens.

**Comment by asticode** [comment]
@komyg there are 2 ways to do it:

1) if you're using the bootstrap (which you seem to be using), you should add the `Debug` option (which you seem to be using as well). Then, once the app is opened, you should press `CTRL` + `O` to open the dev tools. Or go to the menu and look for it.

2) if you want to do it yourself, check out the [OpenDevTool](https://github.com/asticode/go-astilectron/blob/master/window.go#L408) method.

Does that fix your issue?

**Comment by komyg** [comment]
Hi,

Yes, I am using the bootstrap.

I tried to press `Ctrl` + `O` on the window, but nothing happened. I am setting the window as `frameless`and `transparent, but it didn't work even as I disabled these features.

As for calling the window `OpenDevTools` method, I am not sure how to access the `Window` struct from inside the `boostrap.WindowAdapter`.

Thanks,
Felipe

**Comment by komyg** [comment]
Hi,

Yes it does. I changed my code to:

```
func StartOverlay() {
	var w *astilectron.Window

	log.Debug("Starting astilectron...")
	window := []*bootstrap.Window{{
		Homepage: "http://localhost:3000",
		Adapter: func(i *astilectron.Window) {
			w = i
		},
		Options: &astilectron.WindowOptions{
			Height:          astilectron.PtrInt(150),
			Width:           astilectron.PtrInt(150),
			AlwaysOnTop: 		 astilectron.PtrBool(true),
			Transparent: 		 astilectron.PtrBool(true),
			Closable: 			 astilectron.PtrBool(false),
			Minimizable: 		 astilectron.PtrBool(false),
			Frame: 				 	 astilectron.PtrBool(false),
			Movable:				 astilectron.PtrBool(true),
			SkipTaskbar: 		 astilectron.PtrBool(false),
			Resizable:			 astilectron.PtrBool(false),
		},
	}}

	go func() {
		err := bootstrap.Run(bootstrap.Options{
			Windows: window,
			Debug: true,
		})

		if err != nil {
			log.WithError(err).Fatal("Error with Astilectron")
		}
	}()

	time.Sleep(2 * time.Second)
	w.OpenDevTools()
}
```
 And I managed to open the dev tools.

As for your question, the menu bar does not appear for me, because I am using a frameless window, however if I change my configuration to use a normal window, this is what I see:

![image](https://user-images.githubusercontent.com/25157901/49956683-f6bb3100-feec-11e8-956f-ec794444fb0d.png)

Thanks, 
Felipe

**Comment by asticode** [comment]
Haaaaa, that's why you couldn't use the shortcut! It's linked to the menu, so if the menu is not there (because the window is frameless) the shortcut won't work.

Happy you got it working!

Cheers

**Comment by komyg** [comment]
Just a quick follow up. I added a test menu to my application and now I have a the debug option (default to `Ctrl` + `D`) on it. So I guess I was really missing the menu.

Thank you for all the help.
