### ISSUE TITLE
UseContentSize option not working

### ISSUE THREAD

**Issue by komyg** [asticode/go-astilectron#157]
Hi,

I have another question. I am trying to use the window parameter: `UseContentSize = true` to size my window according to its contents.

However the window is always opening using the default 800x600 size.

My code is below, could you help me?

```
log.Debug("Starting astilectron...")
window := []*bootstrap.Window{{
    Homepage: "http://localhost:3000",
    Adapter: func(i *astilectron.Window) {
	w = i
     },
    Options: &astilectron.WindowOptions{
        UseContentSize:  astilectron.PtrBool(true),
        AlwaysOnTop: 		 astilectron.PtrBool(true),
        Transparent: 		 astilectron.PtrBool(false),
        Closable: 			 astilectron.PtrBool(false),
	Minimizable: 		 astilectron.PtrBool(false),
	Frame: 				 	 astilectron.PtrBool(true),
	Movable:				 astilectron.PtrBool(true),
	SkipTaskbar: 		 astilectron.PtrBool(false),
	Resizable:			 astilectron.PtrBool(true),
    },
}}

go func() {
    err := bootstrap.Run(bootstrap.Options{
    Windows: window,
    Debug: true,
    })
    if err != nil {
        log.WithError(err).Fatal("Error with Astilectron")
    }
}()
```

Thanks,
Felipe

**Comment by asticode** [comment]
Mmmm I'm not that familiar with the `useContentSize` option, but the electron doc states:

```
useContentSize Boolean (optional) - The width and height would be used as web page's size, which means the actual window's size will include window frame's size and be slightly larger. Default is false.
```

My understanding is that it still needs the width and height to be provided.

**Comment by komyg** [comment]
Well, I also provided `Width` and `Height` parameters, but then the window used those parameters instead of the being resized to the content size.

**Comment by asticode** [comment]
From what I gather from the doc, the option `useContentSize` won't fit to your content automatically. It seems to mean that the width/height you provide will correspond to the width/height of the web page (excluding the frame of the window) resulting in an overall larger window.

Does that make sense?

**Comment by komyg** [comment]
Yes, I guess I misinterpreted the documentation.

Thanks for the help!
Felipe
