### ISSUE TITLE
Need a sample project using Go and Vue.js with astilectron!

### ISSUE THREAD

**Issue by ganeshsaiavula** [asticode/go-astilectron#158]
I had an application that runs on plain **HTML, CSS and JavaScript and communicates with the Go**. I want this application to be re-written in **Vue.js** as the application got very much messed up. But i didn't find any useful docs/sample project  to kickstart my development. **I am entirely new to the Web Frameworks so guidance would of very much helpful.** **My application does not have api and all it only relies on the message between go and JS**. I want this binary to be running on all **Operating systems** that is generated by the **go-astiectron-bundler.**

**Comment by asticode** [comment]
@ganeshsaiavula unfortunately I'm far from being a JS expert and I have 0 experience with Vue.js. Maybe other folks will have some good inputs.

**Comment by maxiride** [comment]
I'm coming to this repo for the first time, @ganesh-sai did you manage to work with VueJS?
