### ISSUE TITLE
Bootstrap error: creating window failed: canceller.cancelled

### ISSUE THREAD

**Issue by komyg** [asticode/go-astilectron#159]
Hi,

I am having some trouble with go-astilectron. I deployed my software in some computers running Windows 7 and I got the following error: `creating window failed: canceller.cancelled` from the Astilectron Bootstrap.

This error is intermitent, sometimes it happens when my application is started, sometimes it doesn't happen at all.

The full log is below:

```
time="2019-01-04T09:02:41-02:00" level=info msg="Starting Astilectron Service"
time="2019-01-04T09:02:41-02:00" level=info msg="Starting update service"
time="2019-01-04T09:02:41-02:00" level=info msg="Checking for updates" Channel=beta
time="2019-01-04T09:02:41-02:00" level=info msg="Starting task service"
time="2019-01-04T09:02:41-02:00" level=info msg="Starting local server"
time="2019-01-04T09:02:41-02:00" level=info msg="Starting websocket server"
time="2019-01-04T09:02:41-02:00" level=debug msg="Skipping restoring resources..."
time="2019-01-04T09:02:41-02:00" level=debug msg=Starting...
time="2019-01-04T09:02:41-02:00" level=debug msg=Provisioning...
time="2019-01-04T09:02:42-02:00" level=debug msg="Astilectron has already been provisioned to version 0.29.0, moving on..."
time="2019-01-04T09:02:42-02:00" level=debug msg="Electron has already been provisioned to version 1.8.1, moving on..."
time="2019-01-04T09:02:42-02:00" level=debug msg=Listening...
time="2019-01-04T09:02:42-02:00" level=debug msg=Executing...
time="2019-01-04T09:02:42-02:00" level=debug msg="Starting cmd C:\\Users\\PEDEVE-2\\AppData\\Roaming\\Onyo Connector\\vendor\\electron-windows-386\\electron.exe C:\\Users\\PEDEVE-2\\AppData\\Roaming\\Onyo Connector\\vendor\\astilectron\\main.js 127.0.0.1:49177 false"
time="2019-01-04T09:03:12-02:00" level=debug msg="Stdout says: \r"
time="2019-01-04T09:03:12-02:00" level=error msg="No TCP connection has been accepted in the past 30s"
time="2019-01-04T09:03:12-02:00" level=debug msg=Stopping...
time="2019-01-04T09:03:12-02:00" level=debug msg=Closing...
time="2019-01-04T09:03:12-02:00" level=fatal msg="Error running Astilectron Bootstrap" error="creating window failed: canceller.cancelled"
```

Is this happening because the port: 49177 is unavailable? What can I do to prevent this?

Thanks,
Felipe

**Comment by asticode** [comment]
@komyg the most important message is `No TCP connection has been accepted in the past 30s`.

Normally, when the GO code is executed:

- it spawns a TCP server
- it executes the astilectron JS app that connects to this server
- and if no connection is detected by the server, the app stops.

Weirdly enough, you're in this case and this is the first time I've seen this.

I guess it might be a firewall problem.

Did you manage to fix your problem?

**Comment by komyg** [comment]
Hey @asticode, I don't think that this is a firewall issue, because the computers in which this error happened don't have any firewall configurations. My own app opens a HTTP server on the 8080 port and a Websocket in another port and we don't have any problems with this.

They are not the best computers either. Is it possible to increase this 30s timeout? Usually my app is loaded when the computer is starting, so maybe it is lacking resources.

Also is the port 49177 a random port? Does it change everytime I restart the app? What happens if someone else is using it?

Thanks

**Comment by asticode** [comment]
1) You can use the `AcceptTCPTimeout` option to override the `30s`
2) 49177 is indeed a random port that changes everytime the app is restarted. It shouldn't be used though since it's picked with `net.Listen("tcp", "127.0.0.1:")` ([here](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L191))

**Comment by komyg** [comment]
Ok, I will try to increase the accept timeout option and let you know.

**Comment by komyg** [comment]
Hi @asticode, I am sorry I forgot to reply to this thread.

I just wanted to let you know that my problem was solved by increasing the accept timeout.

Thanks for the help, 
Felipe

**Comment by asticode** [comment]
No problem, that's what I figured and that's why I closed the issue.

Thanks for sharing!

Cheers
