### ISSUE TITLE
IPC with Webpack Electron

### ISSUE THREAD

**Issue by nankeen** [asticode/go-astilectron#166]
I have a frontend written in VueJS that gets compiled with WebPack. I'm using the electron package from npm and I'm wondering if it's possible to do IPC with this setup, I can't find any `sendMessage` method in the package I'm using so I'm guessing it's from `astilectron`. But I can't invoke `astilectron` within VueJS, it's undefined. Can work around this or am I missing a method in the package?

**Comment by nankeen** [comment]
I was calling `astilectron.sendMessage` on mount. Fixed after moving it to a button instead. I'm curious why this happens. If this is a duplicate then maybe I've misunderstood some other issue, sorry.

**Comment by asticode** [comment]
@nankeen the `astilectron` var is available when the page gets loaded. [Check this out](https://github.com/asticode/astilectron/blob/master/main.js#L439) to see how the magic happens.
