### ISSUE TITLE
Adding Electron clipboard functionality

### ISSUE THREAD

**Issue by adambrakhane** [asticode/go-astilectron#167]
I have found that `CMD+C`/`CMD+V` does not copy and paste and I've noticed clipboard is on the list for future dev. I've also noticed that `cmd+v` doesn't even work in the dev console while `right click+paste` does work.

1) Do you know of a simple and dirty way to at least allow the right click version of copy/paste to the application window? It looks like the hooks are already there somewhere.
2) Have you started work on the clipboard integration? I would be interested in helping make it happen. The [electron clipboard docs](https://electronjs.org/docs/api/clipboard) are simple enough, but I would need some pointers about where things go in this library. Could you point at existing code that's likely similar that I could use as a starting point?

**Comment by asticode** [comment]
@adambrakhane there's a simple way to enable copy/paste as well as various shortcuts. Check out [this issue](https://github.com/asticode/go-astilectron/issues/68#issuecomment-354251555) and let me know if that fixes your issue.

**Comment by adambrakhane** [comment]
It does. I had actually read that issue but didn't realize it applied to me. I didn't make the connection that adding that role to a menu enabled copy and paste _for the entire application_.
