### ISSUE TITLE
Cannot run tests through vscode

### ISSUE THREAD

**Issue by Naatan** [asticode/go-astilectron#170]
vscode has a very useful testing feature, it lets you debug a test just by clicking the debug button on a test name. 

I wrote a simple test that runs an app and lets me debug the running of the app. It works fine when I manually run `go test` but falls apart when I run the test via vscode.

The invocation is identical in both cases, but the result is not. When using vscode to run the test I get the following errors:

```
time="2019-03-30T11:47:18-04:00" level=debug msg="Starting cmd /Users/nathanrijksen/.go/src/github.com/Naatan/gdom/assets/vendor/electron-darwin-amd64/appName.app/Contents/MacOS/appName /Users/nathanrijksen/.go/src/github.com/Naatan/gdom/assets/vendor/astilectron/main.js 127.0.0.1:63475 false" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says: internal/modules/cjs/loader.js:586" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says:     throw err;" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says:     ^" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says: " app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says: Error: Cannot find module 'electron'" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says:     at Function.Module._load (internal/modules/cjs/loader.js:510:25)" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says:     at Module.require (internal/modules/cjs/loader.js:640:17)" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says:     at require (internal/modules/cjs/helpers.js:20:18)" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says:     at Object.<anonymous> (/Users/nathanrijksen/.go/src/github.com/Naatan/gdom/assets/vendor/astilectron/main.js:3:18)" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says:     at Object.<anonymous> (/Users/nathanrijksen/.go/src/github.com/Naatan/gdom/assets/vendor/astilectron/main.js:549:3)" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says:     at Module._compile (internal/modules/cjs/loader.js:693:30)" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says:     at Module.load (internal/modules/cjs/loader.js:602:32)" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="Stderr says:     at tryModuleLoad (internal/modules/cjs/loader.js:541:12)" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg="App has crashed" app_name=
time="2019-03-30T11:47:18-04:00" level=debug msg=Stopping... app_name=
2019/03/30 11:47:18 Failed creating window: canceller.cancelled
```

The test code I use is:

```
func TestApp(t *testing.T) {
	astilog.SetLogger(astilog.New(astilog.Configuration{
		Out:           "stdout",
		Verbose:       true,
		DisableColors: true,
	}))

	app, err := ast.New(ast.Options{
		AppName:           "appName",
		BaseDirectoryPath: "assets",
	})
	if err != nil {
		log.Fatalf("Failed creating app: %v", err)
	}
	defer app.Close()

	app.Start()

	var w, _ = app.NewWindow("index.html", &ast.WindowOptions{})
	err = w.Create()
	if err != nil {
		log.Fatalf("Failed creating window: %v", err)
	}

	app.Wait()
}
```

I realize this might be an issue with vscode rather than this lib, but I'm not sure where to go from here. Any tips?

Note I am well aware this is not how you should write tests, I'm just using it to facilitate rapid iteration.

**Comment by asticode** [comment]
My guess is that `app.Start()` returns an `error`that you don't process and therefore key logs are missing. Could you log `app.Start()` error and let us know?

**Comment by wenzhencn** [comment]
> My guess is that `app.Start()` returns an `error`that you don't process and therefore key logs are missing. Could you log `app.Start()` error and let us know?

Hi, @asticode . I catch the problems too.
Then, i run the "npm install" command under path "C:\Users\{user}\AppData\Roaming\{appname}\vendor\astilectron".
This still cannot resolve it. I face a new problem is that code "require('electron')" returns a path.
`{"level":"debug","msg":"Stderr says:     app.commandLine.appendSwitch(s, v);\r","time":"2019-04-25T17:15:22+08:00"}
{"level":"debug","msg":"Stderr says:         ^\r","time":"2019-04-25T17:15:22+08:00"}
{"level":"debug","msg":"Stderr says: \r","time":"2019-04-25T17:15:22+08:00"}
{"level":"debug","msg":"Stderr says: TypeError: Cannot read property 'commandLine' of undefined\r","time":"2019-04-25T17:15:22+08:00"}
{"level":"debug","msg":"Stderr says:     at Object.\u003canonymous\u003e`

**Comment by asticode** [comment]
Are you running tests on [go-astilectron](https://github.com/asticode/go-astilectron) or [astilectron](https://github.com/asticode/go-astilectron) ?

**Comment by wenzhencn** [comment]
I using debug function in vscode.
But when i use `go run ./` or `dlv debug ./` command, it worked perfectly.

Maybe the problem is about vscode or vscode-go.

**Comment by asticode** [comment]
Mmmm indeed, I don't really know what `vscode` is really doing... Sorry I can't be of more help...

**Comment by confirm2315** [comment]
If someone appeared the same problem - I only found a solution

Launch configuration:
{
            "name": "Launch debug",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "program": "${workspaceFolder}",
            "showLog": true,
            "port": 2345,
            "host": "127.0.0.1",
            "preLaunchTask": "dlv"
}

Task configuration:
{
            "label": "dlv",
            "type": "shell",
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "command": "dlv debug ./ --headless --listen=:2345 --api-version=2",
            "isBackground": true,
            "problemMatcher": [
                {
                  "pattern": [
                    {
                      "regexp": ".",
                      "file": 1,
                      "location": 2,
                      "message": 3
                    }
                  ],
                  "background": {
                    "activeOnStart": true,
                    "beginsPattern": ".",
                    "endsPattern": ".",
                  }
                }
              ]
}

**Comment by tunggiga** [comment]
Unset the env variable **ELECTRON_RUN_AS_NODE** ( which is set by vscode ) will fix the problem :)

`os.Setenv("ELECTRON_RUN_AS_NODE", "")`
