### ISSUE TITLE
resize doesn't work when Resizable is false

### ISSUE THREAD

**Issue by fregie** [asticode/go-astilectron#172]
I set a window's Resizable to false, then the Resize function usually doesn't work on windows.
But if change the elements[json.targetID].setSize to elements[json.targetID].setBounds in main.js in astilectron, everything is fine.

**Comment by asticode** [comment]
From what I gather from [this issue](https://github.com/electron/electron/issues/4544), `Resizable` seems not to be working properly... 

What do you propose as a solution for this?

**Comment by fregie** [comment]
> From what I gather from [this issue](https://github.com/electron/electron/issues/4544), `Resizable` seems not to be working properly...
> 
> What do you propose as a solution for this?

yes, i can modify setSize to setBounds in astilectron and send a pullrequest

**Comment by fregie** [comment]
maybe,you can use setBounds to resize instead setSize like this:
`elements[json.targetID].setBounds({
                width: json.windowOptions.width,
                height: json.windowOptions.height
            });`

**Comment by asticode** [comment]
I think the best approach would be to add `SetBounds` in the GO API as well as in the `astilectron` JS project so that developer can still choose between both methods.

I'm welcoming PRs.
