### ISSUE TITLE
Cannot load js chunks

### ISSUE THREAD

**Issue by komyg** [asticode/go-astilectron#173]
Hi,

I created a window using React and I bundled everything together using the `create-react-app`. I then added the resulting bundle into my `Resources` folder and created a new window:

```
       var err error
	url := filepath.Join(a.Paths().DataDirectory(), "public/config/index.html")

	opts := &astilectron.WindowOptions{
		AutoHideMenuBar: astilectron.PtrBool(true),
		AlwaysOnTop:     astilectron.PtrBool(false),
		Transparent:     astilectron.PtrBool(false),
		Closable:        astilectron.PtrBool(true),
		Minimizable:     astilectron.PtrBool(true),
		Frame:           astilectron.PtrBool(true),
		Movable:         astilectron.PtrBool(true),
		SkipTaskbar:     astilectron.PtrBool(false),
		Resizable:       astilectron.PtrBool(true),
		Show:            astilectron.PtrBool(true),
		Icon:            astilectron.PtrStr("public/logo-onyo.ico"),
	}

	// Initialize the window
	connectorConfig.Window, err = a.NewWindow(url, opts)
	if err != nil {
		connectorConfig.Window = nil
		return err
	}

	// Register callbacks (must be done before the create so that the DidFinishLoad can execute).
	connectorConfig.Window.On(astilectron.EventNameWindowEventDidFinishLoad, connectorConfig.onWindowLoaded)
	connectorConfig.Window.OnMessage(connectorConfig.onConfigMessage)

	// Create the window
	err = connectorConfig.Window.Create()
	if err != nil {
		connectorConfig.Window = nil
		return err
	}
```

The problem is that when this window loads, I get an error saying that it could not load the js chunks in the index file:

```
<script src="/static/js/2.8e8a5637.chunk.js"></script>
<script src="/static/js/main.673b3637.chunk.js"></script>
```

I've checked my code against the demo and I believe that the problem is the `/`, because Electron is considering it as the root of my file system instead of a relative path (as you stated [here](https://github.com/asticode/go-astilectron/issues/162#issuecomment-461812888)). When I removed it my app worked:

```
<script src="static/js/2.8e8a5637.chunk.js"></script>
<script src="static/js/main.673b3637.chunk.js"></script>
```

My question is: is there a way to make Electron load the scripts correctly without publishing them on a local server or having to change the index.html to remove the `/`?

**Comment by asticode** [comment]
[That comment](https://github.com/electron/electron/issues/2242#issuecomment-299645388) may provide another solution even though I've never tested it.

However I'd be interested in the results of your tests if that's not too much of a bother.

Cheers

**Comment by komyg** [comment]
Hi @asticode,

I am sorry, but I am not sure how to test this.

From what I understood from your comment, I would need to register this callback with Electron: `electron.protocol.interceptFileProtocol`. But I don't know how I can access Electron using Astilectron.

I am sorry if this is a very basic question, but could you help me with this?

Thanks,
Komyg

**Comment by asticode** [comment]
@komyg you can access Electron in `vendor/astilectron/main.js` that is located in the app data (it depends on your OS but it's usually in the same folder as the binary).

You can try to use the code from the comment I've linked to, at the top of the `main.js` so that the `file://` protocol is handled a certain way.

If you confirm it fixes your issue, I'll see how we can merge it into the project.

Let me know if that's still not clear enough.

Cheers

**Comment by komyg** [comment]
Hi @asticode,

I changed the main.js file from Astilectron and added this:

```
'use strict'

const electron = require('electron')
const {app, BrowserWindow, ipcMain, Menu, MenuItem, Tray, dialog, Notification} = electron
const consts = require('./src/consts.js')
const client = require('./src/client.js').init()
const rl = require('readline').createInterface({input: client.socket})

let callbacks = {};
let counters = {};
let elements = {};
let menus = {};
let quittingApp = false;

electron.protocol.interceptFileProtocol(PROTOCOL, function (request, callback) {
      // // Strip protocol
      let url = request.url.substr(PROTOCOL.length + 1);

      // Build complete path for node require function
      url = path.join(__dirname, url);

      // Replace backslashes by forward slashes (windows)
      // url = url.replace(/\\/g, '/');
      url = path.normalize(url);

      console.log(url);
      callback({path: url});
  });
```

The problem is that I get the error below when I start my program.

![image](https://user-images.githubusercontent.com/25157901/57319940-1fc6a300-70d4-11e9-975e-481be5505c8e.png)

Thanks,
Komyg

**Comment by asticode** [comment]
It's normal, if you check out the full code of the comment I've linked to, you'll see both `PROTOCOL` and `WEB_FOLDER` are defined constants. I see that you've removed `WEB_FOLDER` but you still need to replace `PROTOCOL` with `file`.

Does that make sense?

**Comment by komyg** [comment]
Hi @asticode ,

I am sorry I didn't pay attention to that... Anyway I updated my code to this:

```
'use strict'

const electron = require('electron')
const {app, BrowserWindow, ipcMain, Menu, MenuItem, Tray, dialog, Notification} = electron
const consts = require('./src/consts.js')
const client = require('./src/client.js').init()
const rl = require('readline').createInterface({input: client.socket})

let callbacks = {};
let counters = {};
let elements = {};
let menus = {};
let quittingApp = false;

const WEB_FOLDER = '';
const PROTOCOL = 'file';

electron.protocol.interceptFileProtocol(PROTOCOL, (request, callback) => {
  // // Strip protocol
  let url = request.url.substr(PROTOCOL.length + 1);

  // Build complete path for node require function
  url = path.join(__dirname, WEB_FOLDER, url);

  // Replace backslashes by forward slashes (windows)
  // url = url.replace(/\\/g, '/');
  url = path.normalize(url);

  console.log(url);
  callback({path: url});
});
```

However when I ran it, I got this error:

![image](https://user-images.githubusercontent.com/25157901/57459235-36423b00-7249-11e9-9cdf-a1ed3aba5788.png)

Thanks,
Komyg

**Comment by asticode** [comment]
Could you try looking at [this part of the doc](https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocol) and replacing `atom` with `file`?

Or try to use [this function](https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocol) with the `file` scheme?

**Comment by komyg** [comment]
Hi @asticode, both links in your previous comments were pointing to the same URL. Is this correct?

Anyway, I managed to get things working with the protocol. Here is my code:

```
'use strict'

const electron = require('electron')
const {app, BrowserWindow, ipcMain, Menu, MenuItem, Tray, dialog, Notification, protocol} = electron
const consts = require('./src/consts.js')
const client = require('./src/client.js').init()
const rl = require('readline').createInterface({input: client.socket})
const path = require('path')

let callbacks = {};
let counters = {};
let elements = {};
let menus = {};
let quittingApp = false;

app.on('ready', () => {
	const WEB_FOLDER = '';
	const PROTOCOL = 'file';

	protocol.interceptFileProtocol(PROTOCOL, (request, callback) => {
	  // // Strip protocol
	  let url = request.url.substr(PROTOCOL.length + 1);

	  // Build complete path for node require function
	  url = path.join(__dirname, WEB_FOLDER, url);

	  // Replace backslashes by forward slashes (windows)
	  // url = url.replace(/\\/g, '/');
	  url = path.normalize(url);

	  console.log(url);
	  callback({path: url});
	});
})
```

Notice that I am also importing `protocol` on this line: `const {app, BrowserWindow, ipcMain, Menu, MenuItem, Tray, dialog, Notification, protocol} = electron`.

So now I managed to point Electron in the right direction and it is trying to load my files from the correct path. Unfortunately I ran into another problem: whenever I try to load the `index.html` file, I get this error: `Not allowed to load local resource: file:///C:/Users/Felipe/AppData/Roaming/My%20App/public/config/index.html`, which is referenced at the end of the [original thread](https://github.com/electron/electron/issues/2242#issuecomment-448587215) you sent me.

I found this thread: https://github.com/electron/electron/issues/13528, but it wasn't much help.

Thanks,
Komyg

**Comment by asticode** [comment]
Damn, sorry about linking the wrong URL...

I was trying to link [this method](https://electronjs.org/docs/api/protocol#protocolregisterstandardschemesschemes-options) that allows registering a new protocol and disabling its securities. Maybe you can try registering the `file` protocol with the `security` attribute set to `false`.

**Comment by komyg** [comment]
Hi, 

I tried to register the file [scheme as privileged](https://electronjs.org/docs/api/protocol#protocolregisterschemesasprivilegedcustomschemes), but I got an error saying that the protocol did not have this function: `protocol.registerSchemesAsPrivileged`.

Here is my code:

```
app.on('will-finish-launching', () => {
	protocol.registerSchemesAsPrivileged([
		{ scheme: 'file', privileges: { bypassCSP: true } }
	])
});
```

By the way, I am not sure that this was what you meant in your last message, but reading the documentation it seemed that this was the way to go.

Thanks,
Komyg

**Comment by zanitee** [comment]
@komyg I'm having the same issue, and in fact even all the resources and media files are having the same problem due to the leading forwards slash.

what was the the full fix you ended up using if you don't mind? thanks

**Comment by komyg** [comment]
Hi @zanitee, 

There isn't a permanent fix.

What I did to work around the problem was to remove all the `/` from the generated files. For example, in my React project, Webpack generated the scripts below: 

```
<script src="/static/js/2.8e8a5637.chunk.js"></script>
<script src="/static/js/main.673b3637.chunk.js"></script>
```

I then removed the first `/` from them:

```
<script src="static/js/2.8e8a5637.chunk.js"></script>
<script src="static/js/main.673b3637.chunk.js"></script>
```

I did this manually, but you could probably change the Webpack configuration to generate the scripts src without the `/`.

**Comment by lorenzorivosecchi** [comment]
Hi @komyg, actually the solution is very simple.

You just need to set the `homepage` property of your package json to `"./"`.

```json
{
 "homepage": "./"
}
```

Create React App will build the app using relative paths.

```html
    <script src="./static/js/2.31e292c2.chunk.js"></script>
    <script src="./static/js/main.744209c3.chunk.js"></script>
```

[Here](https://www.freecodecamp.org/news/building-an-electron-application-with-create-react-app-97945861647c/) is the guide where I found the solution.

**Comment by asticode** [comment]
Cheers !
