### ISSUE TITLE
flicker#notification not focused

### ISSUE THREAD

**Issue by huiruo** [asticode/go-astilectron#174]
When the app  receive a message, how to make the  the background app flicker to attract the user's attention in Windows ? The program is in the background and the window is not focused

**Comment by asticode** [comment]
My guess is you need to use a combination of `window.Show()` and `window.Resize` or `window.Move`

**Comment by huiruo** [comment]
thanks,i will try

**Comment by asticode** [comment]
I'll close this issue, but let me know if that doesn't work.

Cheers

**Comment by huiruo** [comment]
> I'll close this issue, but let me know if that doesn't work.
> 
> Cheers

I'm implementing other functions. I'll leave this requirement behind. I'll let you know if there are any problems.You can close this issue.Best wishes
