### ISSUE TITLE
Can I use "headless mode"?

### ISSUE THREAD

**Issue by Duplex3345678** [asticode/go-astilectron#176]
Hi, I am a beginner.

I have run DEMO successfully. Now I want to run DEMO in headless mode to let my program can run in only command line OS like CentOS or Ubuntu cli mode.

``
Windows: []*bootstrap.Window{
				{
					Homepage:       "index.html",
					MessageHandler: handleMessages,
					Options: &astilectron.WindowOptions{
						BackgroundColor: astilectron.PtrStr("#333"),
						Center:          astilectron.PtrBool(true),
						Height:          astilectron.PtrInt(700),
						Width:           astilectron.PtrInt(700),
						Transparent:     astilectron.PtrBool(true),
						Show:            astilectron.PtrBool(false),
					},
				},
			},
``

Above is my bootstrap.Window, I added "Show" and "Transparent" to try to make a headless mode. After I build and run it, it can use it in Ubuntu (not cli mode) successfully, and it is headless.
But, when I use Ubuntu cli mode, it have some errors about create window.

Below is my error log when I run it in Ubuntu cli mode

``
ERRO[0000] accept tcp 127.0.0.1:45523: use of closed network connection while TCP accepting
FATA[0000] running bootstrap failed: creating window failed: canceller.cancelled
``

My question is: can I add option like Show or something else to build a headless mode and successfully run in a only CLI OS?

**Comment by asticode** [comment]
What do you mean by "headless"?

**Comment by Duplex3345678** [comment]
@asticode 
I mean "run in background".

I want to program can also run in a CLI os, like CentOS
Because I use SSH to connection the remote computer which is  actually running the program, it only have CLI.

Can it run successfully with running background or no create window?

Thank you a lot!

**Comment by asticode** [comment]
Mmm I don't think you can use Electron in a CLI OS, therefore I don't think you can use this project in a CLI OS.

**Comment by Duplex3345678** [comment]
Ok!
Thanks for your answer.
