### ISSUE TITLE
Play Sound

### ISSUE THREAD

**Issue by huiruo** [asticode/go-astilectron#177]
support playing sound? How to Play Sound？

**Comment by asticode** [comment]
You should be able to play sound using Javascript: https://stackoverflow.com/questions/9419263/playing-audio-with-javascript

**Comment by Noofbiz** [comment]
Go also has a couple pretty good libraries for playing sound on the go side, if you want. [Oto](https://github.com/hajimehoshi/oto/) is really good and works across platforms. I use it in my game engine; haven't tried it with astilectron though.

**Comment by adambrakhane** [comment]
I've had success both with direct JS and howler.js. Might be cleaner to play sound directly from Go but doing it in JS makes it easy to debug/build in the browser only.

```
var audio = new Audio('static/lib/audio/beeps/beep-attention.mp3');
audio.play();
```

[Howler.js](https://github.com/goldfire/howler.js#quick-start)
```
var sound = new Howl({src: ['static/lib/audio/beeps/beep-attention.mp3']});
sound.play();
```

**Comment by huiruo** [comment]
> Go also has a couple pretty good libraries for playing sound on the go side, if you want. [Oto](https://github.com/hajimehoshi/oto/) is really good and works across platforms. I use it in my game engine; haven't tried it with astilectron though.
Good library!Thank you very much.

**Comment by huiruo** [comment]
> You should be able to play sound using Javascript: https://stackoverflow.com/questions/9419263/playing-audio-with-javascript

I am honored to have the author's enthusiastic answer, which has helped me a lot.

**Comment by huiruo** [comment]
> I've had success both with direct JS and howler.js. Might be cleaner to play sound directly from Go but doing it in JS makes it easy to debug/build in the browser only.
> 
> ```
> var audio = new Audio('static/lib/audio/beeps/beep-attention.mp3');
> audio.play();
> ```
> 
> [Howler.js](https://github.com/goldfire/howler.js#quick-start)
> 
> ```
> var sound = new Howl({src: ['static/lib/audio/beeps/beep-attention.mp3']});
> sound.play();
> ```

thanks,nice librarie
