### ISSUE TITLE
Avoid having antivirus starts the process for 10s the very first time

### ISSUE THREAD

**Issue by asticode** [asticode/go-astilectron#18]
Related comment: https://github.com/asticode/go-astilectron/issues/16#issuecomment-305681620

Same thing happened to me, even when using `-ldflags="-H windowsgui"` the process seems to start once, then disappear and then starts over again. The `vendor` folder doesn't seem to be created during the first start.

@lemtree are you using `cygwin` or another terminal than window's default to run the binary?

**Comment by deepch** [comment]
I'm use 

GOOS=windows GOARCH=amd64 go build -ldflags "-H windowsgui" -o windows_amd64.exe main.go resources.go app.go

And it works

The terminal window appears for a moment and disappears.

The vendor folder is downloaded for a long time, maybe it makes sense to put in an installer (current platfom)

**Comment by asticode** [comment]
@deepch do you have `cygwin` installed on your Windows machine? Or any terminal other than the Windows' default?

**Comment by deepch** [comment]
I use default windows install on VM xenserver for test

**Comment by lunny** [comment]
I have encountered this problem too. Windows 7 SP1 x64. Any update of this?

**Comment by asticode** [comment]
Nah, unfortunately I've had little time to work on this. The weird thing I've discovered is that it seems to be linked to executing a binary in windows in a certain way... but I don't have more information.

Feel free to investigate.

**Comment by beardww** [comment]
I haven't encountered this glitch, but I'm building the windows binary in OSX for Win7SP1x64

**Comment by asticode** [comment]
I've finally had some time to work on this issue and unfortunately here's what I've discovered (I'm on GO 1.10.1 and Windows 10): 

- the glitch only happens when first using the binary just after having built for the first time
- the next times it's working fine
- in my case this is the *antivirus* that is spawning the first process and then killing it. Maybe sandboxing it to check whether it's a virus. Indeed when I disable the antivirus (Avast in my case) I don't experience the glitch even when first using the binary.

Unfortunately I don't have any solution for that since it seems like a legit thing to experience if the user has installed an antivirus just for that.

However I'm all ears if anybody has a suggestion.
