### ISSUE TITLE
TCP Connection Stream destroyed

### ISSUE THREAD

**Issue by pitridev** [asticode/go-astilectron#180]
After running my application, then leaving it open and idle for roughly 1-2 hours. It will randomly crash within that time frame and give the following errors. I have tested this twice now, both tests had the same results.

![1d99bdfa0f44d7fe99149429ff60444f](https://user-images.githubusercontent.com/30211810/56705473-03436780-66df-11e9-97ee-c5b8418c0842.png)
![a1c562114461eb9fe6b257b03426fa96](https://user-images.githubusercontent.com/30211810/56705474-03436780-66df-11e9-8374-68a6084fc0ed.png)

**Comment by asticode** [comment]
By any chance, can you run the same test while running the Go app with the following modifications:

1) add `astilog.FlagInit()` after `flag.Parse()` at the top of your `main` function
2) run the Go app with the `-v` flag
3) paste logs here

The idea is to capture what Go is saying when this error occurs.

**Comment by pitridev** [comment]
[go.log](https://github.com/asticode/go-astilectron/files/3123853/go.log)

**Comment by asticode** [comment]
This is really interesting, thanks for the logs.

It may be linked to some connection timeout value on the GO or the JS side.

I'll investigate further when I have time. In the meantime, if anybody has time to investigate further, feel free.

**Comment by Akumzy** [comment]
@asticode [ipc](https://github.com/Akumzy/ipc) please take a look

**Comment by Akumzy** [comment]
I think it's more reliable than TCP

**Comment by asticode** [comment]
@Akumzy `ipc` through `stdin` is a really good idea that I used at the beginning of this project. Unfortunately, at that time `stdin` was not working in Electron on Windows. And as far as I'm concerned, it's still not. Therefore it's unusable until `stdin` is working on Windows.

**Comment by Akumzy** [comment]
@asticode I don't know the core architecture behind your great project `go-astilectron` but based on my knowledge.
The main aim here is to create a good IPC medium between `Go` and `Nodejs` right?
If so we can boot up the ipc connection between Electron main process and Go `stdin` and then proxy all events meant for broswerWindows through `ipcMain`, `ipcRenderer` or  `webContent` eventEmitters

**Comment by Akumzy** [comment]
Secondly almost all electron methods are main process based which you can access from renderer through `remote` as well, so almost all event going to browserWindows are user defined proxying  might not affect performance.

**Comment by asticode** [comment]
> we can boot up the ipc connection between Electron main process and Go stdin

Thing is, in this project Go is executing a child Electron process, not the other way around. Therefore to implement your idea we would have to use Electron stdin instead. And as I've mentioned, Electron stdin is not working properly on Windows. So that's not possible.

That's why I've chosen to use TCP between Go and Electron but I guess we could also have uses name pipes or anything similar.

**Comment by Akumzy** [comment]
Ohh now I get you.

**Comment by pitridev** [comment]
> This is really interesting, thanks for the logs.
> 
> It may be linked to some connection timeout value on the GO or the JS side.
> 
> I'll investigate further when I have time. In the meantime, if anybody has time to investigate further, feel free.

The issue is 100% in relation to a connection timeout in either Go or JS. The following test proves such.

I started the same application, only this time I created a JavaScript function with the following:
```js
$(function () {
    setInterval(ping, 30000);
});

function ping() {
    sendMessage("ping", null, null);
}

function sendMessage(name, data, callback) {
    console.log('Invoking event ' + name + ' with data ' + data);

    astilectron.sendMessage(name + "\n" + data, function (rData) {
        if (callback != null) {
            callback(rData);
        }
    });
}
```

My application has been running untouched and idle for over 10 hours now without any issues. It appears that sending a "ping" to the connection every 30 seconds has kept the connection open.

If anyone encounters the issue in the meantime, this is a nice workaround. Most clients/server do a ping/pong anyways to ensure the connection is still open. You don't need the pong response, only the ping will suffice.

I will try and locate the timeout connection option that is not being set correctly once I have some free time if no one gets to it first.

**Comment by asticode** [comment]
Thanks for the feedback!

Could you try adding the following code [here](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L237) and see whether that fixes the problem:

```go
if err = conn.SetDeadline(time.Time{}); err != nil {
	astilog.Errorf("Setting deadline failed")
	return
}
```

**Comment by qq283436889** [comment]
I have the same problem
mac os x

**Comment by asticode** [comment]
@qq283436889 could you try what I've suggested in my previous comment and see whether it fixes the problem ?

**Comment by qq283436889** [comment]
DEBU[0235] Astilectron says: {"name":"window.event.hide","targetID":"1"}  app_name= source="reader.go:61"
DEBU[0237] Astilectron says: {"name":"window.event.show","targetID":"1"}  app_name= source="reader.go:61"
DEBU[0237] Closing...                                    app_name= source="astilectron.go:322"

ERRO[0237] accept tcp 127.0.0.1:49923: use of closed network connection while TCP accepting  app_name= source="astilectron.go:232"

DEBU[0237] Stopping...                                   app_name= source="astilectron.go:355"

ERRO[0237] read tcp 127.0.0.1:49923->127.0.0.1:49924: use of closed network connection while reading  app_name= source="reader.go:55"


Desktop switch window ，application exits automatically。

error

a javascript error occurred in the main process

uncaught exception:
error:read econnreset
at tcp.onstreamread (internal/stream_base_commons.js:111:27)


mac os sierra 10.12.6/mac os mojave 10.14.2beta

vendor

electron-darwin-amd64-v4.0.1

**Comment by qq283436889** [comment]
forgot to add Wait() at the very end of the main function. This is the blocking pattern

**Comment by asticode** [comment]
👍
