### ISSUE TITLE
window enlargement

### ISSUE THREAD

**Issue by huiruo** [asticode/go-astilectron#182]
How to prohibit window enlargement？
`			Options: &astilectron.WindowOptions{
				BackgroundColor: astilectron.PtrStr("#ffffff"),
				Center:          astilectron.PtrBool(true),
				Height:          astilectron.PtrInt(950),
				Width:           astilectron.PtrInt(950),
				MinHeight:       astilectron.PtrInt(950),
				MinWidth:        astilectron.PtrInt(950),
				MaxHeight:		 astilectron.PtrInt(950),
				MaxWidth:		 astilectron.PtrInt(950),
			},`
I set 'MaxHeight' and 'MaxWidth'  attributes,the width is able to prohibit  enlargement.But the height  can enlarge while using mouse to pull

**Comment by huiruo** [comment]
> How to prohibit window enlargement？
> `	Options: &astilectron.WindowOptions{ BackgroundColor: astilectron.PtrStr("#ffffff"), Center: astilectron.PtrBool(true), Height: astilectron.PtrInt(950), Width: astilectron.PtrInt(950), MinHeight: astilectron.PtrInt(950), MinWidth: astilectron.PtrInt(950), MaxHeight:	astilectron.PtrInt(950), MaxWidth:	astilectron.PtrInt(950), },`
> I set 'MaxHeight' and 'MaxWidth' attributes,the width is able to prohibit enlargement.But the height can enlarge while using mouse to pull

when I set ：
`		Windows: []*bootstrap.Window{{
			Homepage:       "index.html",
			MessageHandler: handleMessages,
			Options: &astilectron.WindowOptions{
				BackgroundColor: astilectron.PtrStr("#ffffff"),
				Center:          astilectron.PtrBool(true),

				Height:          astilectron.PtrInt(750),
				Width:           astilectron.PtrInt(850),

				MinHeight:       astilectron.PtrInt(750),
				MinWidth:        astilectron.PtrInt(850),

				MaxHeight:		 astilectron.PtrInt(750),
				MaxWidth:		 astilectron.PtrInt(850),
			},
		}},`
This seemed to work！

**Comment by asticode** [comment]
Have your tried using the `Resizable` attribute set to `false`?

```go
Windows: []*bootstrap.Window{{
  Resizable: astilectron.PtrBool(false),
}}
```

**Comment by huiruo** [comment]
> Have your tried using the `Resizable` attribute set to `false`?
> 
> ```go
> Windows: []*bootstrap.Window{{
>   Resizable: astilectron.PtrBool(false),
> }}
> ```

Thank,The problem has been solved
