### ISSUE TITLE
Can you provide a simple demo 

### ISSUE THREAD

**Issue by PSK144** [asticode/go-astilectron#188]
Given Demo file is complex to understand. It is hard to trace back the function calls and declarations and some files can't open due to the bulk size.

Can you provide a simple demo for easy understanding. I already go through the instruction given in the source page but still struggling. need help...

**Comment by tuhao1020** [comment]
+1
same problem, my code can't work at all,  I just need a "Hello world" sample to understand how to create a window and show it

**Comment by asticode** [comment]
I've added a minimalistic example that you can run with `go run example/main.go -v`.

But it doesn't use the bundler or the bootstrap.
