### ISSUE TITLE
Loading a second template into the primary window

### ISSUE THREAD

**Issue by morriswinkler** [asticode/go-astilectron#19]
I am trying to load a second template.
So far I used the js function:
```
 window.open("/templates/secondsTemplate");
```

That will open a new window, my goal is to open it in the same window. 

I am using the bootstrap, therefore I do not have access to the window variable in go.
Anyway, I couldn't find anything in the code that would load a new template. My guess is that this is done from the js side. 

Any suggestions?

**Comment by veecue** [comment]
What about simply using `document.location.href = "/templates/secondsTemplate";` ?

**Comment by asticode** [comment]
@veecue's suggestion is a good one, you can navigate through templates like you would navigate from page to page in a web page using `<a>` tags or the `location` JS object. After all this is HTML and JS behind the scenes.

Also you can access the bootstrap's `*astilectron.Window` using the `AdaptWindow` option which is a 

```go
func(w *astilectron.Window)
```

but in your case that wouldn't make your life easier.

If this answers your question, please close this issue.
Cheers

**Comment by morriswinkler** [comment]
Yes, thanks.

**Comment by morriswinkler** [comment]
Just as a reference, this is also a nice sollution: 
https://www.christianengvall.se/electron-app-navigation/
