### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by zhb1207** [asticode/go-astilectron#192]
Uncaught Exception:
Error: read ECONNRESET at TCP.onStreamRead(internal/stream_base_commons.js:111:27)

Hi, I met this error when I used bundler and bootstrap to run the app, and open a second window in the app. After this Error, the window would be closed. However this error never appear if I use "go run main.go" to start the app.
I noticed this Error happens inside the function of astilectron.NewWindow()

Machine: windows 10

Is it a problem with bundling dependency or nodeJS or something else?
Thanks.

**Comment by zhb1207** [comment]
I found the reason, it was my fault, sorry for the inconvenience.

**Comment by nikhilsaraf** [comment]
@zhb1207 I'm facing the same issue, can you describe your solution please?

**Comment by nyugoh** [comment]
Am getting the same error, @zhb1207 what's the solution?

**Comment by w01fb0ss** [comment]
@zhb1207 I'm facing the same issue, can you describe your solution please?
