### ISSUE TITLE
Integrating go-astilectron into existing Electron project

### ISSUE THREAD

**Issue by sbrow** [asticode/go-astilectron#193]
Hello! Love the project. I am wondering if there is any way to start `go-astilectron` from the javascript side (specifically the `electron main` process) so that I can integrate `go-astilectron` into my projects that already have a javascript backend.

I'm looking for these two things:
1. The ability to create event handlers in javascript that can communicate with windows created in `go-astilectron` (for services that don't have good go libraries yet, or have already been implemented in the project's js).
2. The ability to run the project by calling `$ electron ./electron.js` rather than running `go-astilectron` directly. (that way any standard electron bundler can be used, e.g: [electron-builder](https://github.com/electron-userland/electron-builder), [electron-forge](https://github.com/electron-userland/electron-forge), etc.)

I've provided below an example of the kind of API I'm thinking of.

Is any of this possible? From what I understand, `astilectron` seems a little "all-or-nothing" in this regard, but perhaps I'm missing something.

 Thanks in advance.

<details>
<summary><b>Example</b></summary>
The javascript:

```javascript
// electron.js (entry point for the application)

import { start, getWindowsSync } from "astilectron";
import { exec } from "child_process";
import { ipcMain } from "electron";

// setup astilectron. (javascript side)
const port = start();

// Launch go-astilectron. (go side, see below)
let go = exec("./go_astilectron_project_binary", port);

// `main` same as `mainWindow` in main.go.
// Sync blocks until window is created.
const [ main ] = getWindowsSync();

ipcMain.on("handle in js", (message) => {
  console.debug(`received ${message} in js`);
  main.webContents.send("reply");
});
```

And the go code:
```go
//main.go (entry point for go)

/**
  * Package main is the go-astilectron bindings for this app
  */
package main

import (
    "github.com/asticode/astilog"
    "github.com/asticode/go-astilectron"
)

func main() {
    var app, _ := astilectron.New(&astilectron.WindowOptions{})
    var mainWindow, _ := app.newWindow("file://<working dir>/app/index.html", nil)
    mainWindow.create()
    mainWindow.On("handle in go", func(m *astilectron.Message) {
        // Unmarshal
        var s string
        m.Unmarshal(&s)

        // Process message
        astilog.Debugf("received %s in go", s)
    })
}
```
```json
// package.json
{
    "name": "project-name",
    "scripts": {
        "start:dev": "electron ./electron.js"
    },
    "dependencies": {
        "astilectron": "<version number>",
        "electron": "<version number>"
    }
}
```
To run the project (in development mode), one would simply call:
```bash
$ electron ./electron.js
```
or
```bash
node run start:dev
```
</details>

**Comment by asticode** [comment]
Here are my thoughts about what you're looking for:

1. having Electron spawning go-astilectron that itself calls another Electron instance to create windows doesn't seem like a good idea to me. If you already have an Electron project, it should be the only one creating windows. The GO part should be limited to a simple service that can communicate with the Electron project. But as far as I'm concerned, in your case GO shouldn't be creating windows.
2. seems like a very good thing to be looking for indeed!

Therefore here's what you need in my opinion:

1. a GO library that spawns a server that can listen to JS events sent by Electron. You would need to use such library in your GO services in order to communicate with Electron.
2. a JS library that connects to the GO server and sends all Electron events deemed interesting

Would that fill your needs?

**Comment by sbrow** [comment]
Thanks for the feedback. While there are alternative solultions to this problem, I think it would make `go-astilectron` more accessible to Node.js developers if it could be started from either side (js or go).

Assuming I correctly understand how `go-astilectron` works, I believe all that's needed to get what I'm looking for is: a function in `go-astilectron` that connects to an existing `astilectron` instance rather than creating a new one. 

Using that, `astilectron` could be started from the js side, allowing users to import extra code into the electron main process, while still handling window control and other backend things in go.

Below I have lists of how I think `go-astilectron` works, and the process I'm hoping to achieve.

## How go-astilectron currently works? (go -> js)
1. User starts go-astilectron: `$ go run main.go`.
2. go downloads `astilectron` and `electron`.
3. go picks a port for astilectron.
4. go starts astilectron: `exec.Command("astilectron", "<path to electron>", "<app/main.js>", "<port>")`
5. go creates windows.

## My alternative proposal (js -> go)
1. user starts electron `$ electron app/main.js`.
2. js picks a port for astilectron.
3. js starts astilectron.
4. js starts go-astilectron: `exec("./main.go", "<port>")`.
5. go connects to astilectron and creates windows.

We don't need to worry about downloading electron or astilectron because we can handle that with npm.

Is my understanding correct? I know you probably don't want to make this kind of modification yourself, but if it's as small as I think it is, with a little more information I could open up a PR for it.

**Comment by sbrow** [comment]
After playing around with it a little bit, I managed to get this working, although it is a bit of a kludge. The only change I had to make to `go-astilectron` was to make `Astilectron.listenTCP` public ([see here](https://github.com/sbrow/go-astilectron/commit/c5f8f974f02258d3d1ab0fdbb6e18ad347f39b72)). However, I will need to make some changes to the `astilectron` package to give it a sensible API. Will update again when I have that fleshed out a bit better.

**Comment by sbrow** [comment]
I've gotten it working! Example [here](https://github.com/sbrow/go-astilecton-from-js-example).

If this is a feature that you'd be interested in merging than I can open some PRs for it, it will require edits to both `astilectron` and `go-astilectron`.

Just need to agree on what the APIs should look like and make sure there aren't any bugs.

**Comment by asticode** [comment]
I really like the idea!

However I really wish not to make the `listen` method public if possible. I'd rather see :

- a new attribute added to the `Options` passed to the `New` method (something like "Passive: true")
- you need to call `Start` instead of `Listen`, but thanks to the previous option, it skips the provision and the execution

As for the value of the port, perhaps it would make more sense if it was given to the GO script through a flag and then passed in the `Options`?

What do you think?

**Comment by sbrow** [comment]
I think that all makes good sense. Currently, Go just picks a random port and sends it to astilectron via stdout.

Just a few more questions:
1. I had to add a `Astilectron.WaitOn` function in Go to wait for the electron ready event. Is this acceptable or  should that be hidden in the `Start` function as well?
2. Any thoughts on the js API? It didn't really have one previously because it was all called via CLI.

**Comment by asticode** [comment]
1. Check out the [synchronousFunc](https://github.com/asticode/go-astilectron/blob/master/helper.go#L152) method that allows you to execute something and waiting either for the context to be cancelled, or a specific event to be received from the JS. And it should be hidden in the `Start` function as well.
2. Do you need anything else in addition of a `start` method in JS ?

**Comment by sbrow** [comment]
synchronousFunc works great! As for the JS side, it might be nice in the future to expose the windows created by go, but for now, all that _needs_ to be exposed is start.

The question is how to tell Astilectron that the TCP server is ready. Currently, I have go-astilectron write to stdout when the server is up, which is probably not ideal.

The electron entrypoint looks like this:

<details>
<summary>electron.js</summary>

```js
"use strict";

const astilectron = require("astilectron");
const child_process = require("child_process");

const port = "8080";
// Start go-astilectron at port 8080
const cmd = child_process.exec(`${main} ${port}`);
cmd.stdout.pipe(process.stdout);
cmd.stderr.pipe(process.stderr);

cmd.stdout.on("data", data => {
  // Wait for go-astilectron to print "Starting" to stdout
  // before starting astilectron.
  if (data.match("Starting")) {
    // Start astilectron.
    astilectron.start(`127.0.0.1:${port}`);
  }
});
```

</details>

My other idea would be pinging the server every 100ms or so until it connects or timeouts.

**Comment by asticode** [comment]
Does `stdout` work in Windows as well? I had a bad experience with using `stdout` with Electron in Windows since it didn't work...

**Comment by sbrow** [comment]
It worked fine when I tried it, but that was sending from Go to JS, don't know about the other way round.

**Comment by asticode** [comment]
I think pinging the server for some time before timing out is a better solution since this requires no logic in GO.

**Comment by sbrow** [comment]
Will do. After that's implemented and both PRs are merged, I'll close this issue.

**Comment by sbrow** [comment]
Just a reminder, PR asticode/astilectron#22 still needs to be merged in order for these changes to work.

**Comment by asticode** [comment]
PR has been merged, I've created a `0.33.0` tag therefore you'll need to update [this constant](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L23) accordingly.

**Comment by sbrow** [comment]
astilectron should also get published to [npm](https://www.npmjs.com/) so that it can be used by javascript developers.

**Comment by asticode** [comment]
This is actually a very good idea and I just did: https://www.npmjs.com/package/astilectron. Let me know if I did anything wrong as I'm not an NPM expert.

Cheers

**Comment by asticode** [comment]
FYI I've bumped `astilectron` version ([commit](https://github.com/asticode/go-astilectron/commit/91fc3e721cd97a1c7213aa3993296f071965e2de)). Is there anything else that needs to be done?

**Comment by sbrow** [comment]
Unfortunately, I have experienced one minor problem when I close the window 
![Screen Shot 2019-09-25 at 10 46 56](https://user-images.githubusercontent.com/6729162/65612191-de9b3680-df81-11e9-94b8-bf80f6d4868f.png)

Other than that, everything is perfect! I have set up an example project [here](https://github.com/sbrow/go-astilecton-from-js-example) for anyone that would like to experiment with this feature.

**Comment by asticode** [comment]
Are you closing the GO app before closing the window?

**Comment by sbrow** [comment]
I am not manually closing the Go app.

**Comment by asticode** [comment]
Can you paste GO logs when it happens? (execute GO with the `-v` flag after having initialized `astilog` so that I can see debug logs as well)

**Comment by sbrow** [comment]
Sorry for the late response. Where are the logs getting saved? I tried running my `main.go` with `go run -v main.go $PORT`, but it didn't output any logs that I'm aware of.

**Comment by asticode** [comment]
You need to add the following at the top of your main function:

```go
flag.Parse()
astilog.FlagInit()
```

Then logs will be printed in `stdout`.

**Comment by asticode** [comment]
Did you manage to fix your problem ?
