### ISSUE TITLE
Can go-astilectron run in sandbox of apple?

### ISSUE THREAD

**Issue by fregie** [asticode/go-astilectron#194]
I want to submit my app to app store,but it request running in sandbox
And if running in sandbox,the electron released can't be run,operation not permitted
It means go-astilectron can't create a executable file of electron
Is there any solution of this issuess?

**Comment by asticode** [comment]
To submit your app to the Apple Store you need to sign your app with a valid Apple Certificate. Unfortunately, the signing step has not been implemented as of now.

**Comment by winwisely99** [comment]
Is the signing step different from just signing a standard app for Mac OS ?

**Comment by asticode** [comment]
To be honest, I haven't tried submitting an app to the app store. I'm mainly basing my statement on Electron builder doc. But from what I gather, it isn't different from just signing a standard app for MacOS.

Let me know if that's not the case.

**Comment by winwisely99** [comment]
Ok thanks. Will give it a shot
