### ISSUE TITLE
Reloading page

### ISSUE THREAD

**Issue by komyg** [asticode/go-astilectron#195]
Hi,

I am having and issue that when my application launches, instead of displaying the page, it just displays blank and I have to forcibly reload the page to get it to work.

To reload the page, currently I am opening the dev-tools and pressing `Ctrl+R`. But I want the user to be able to do this on his own using the standard keys, such as `F5`, for example.

To do this, I created the menu below on my Window, but when I press the accelerator keys, nothing happens. I also tried not specifying the Accelerator (since the [Electron documentation](https://electronjs.org/docs/api/menu-item#roles) states that it will be handled by the default key), but that didn't work either.

Am I doing something wrong?

```
           m := connector.window.NewAstiMenu([]*astilectron.MenuItemOptions{
		{
			Accelerator: astilectron.NewAccelerator("CmdOrCtrl", "Shift", "I"),
			Visible:     astilectron.PtrBool(false),
			OnClick: func(e astilectron.Event) (deleteListener bool) {
				connector.window.OpenDevTools()
				return
			},
		},
		{
			Accelerator: astilectron.NewAccelerator("CmdOrCtrl", "Shift", "R"),
			Visible:     astilectron.PtrBool(false),
			Role:        astilectron.MenuItemRoleForceReload,
		},
		{
			Accelerator: astilectron.NewAccelerator("F5"),
			Visible:     astilectron.PtrBool(false),
			Role:        astilectron.MenuItemRoleReload,
		},
	})
```

Thanks,
Komyg

**Comment by asticode** [comment]
It seems like when `visible` is set to `false`, it disables the shortcut.

Can you try not setting the `Visible` option and let me know whether that works?

**Comment by komyg** [comment]
Hi, @asticode, I did that, but the result was the same.

It seems that the default roles are not working for some reason. For example, when I changed this: 

```
{
    Accelerator: astilectron.NewAccelerator("CmdOrCtrl", "Shift", "I"),
    Visible:     astilectron.PtrBool(false),
    OnClick: func(e astilectron.Event) (deleteListener bool) {
        connector.window.OpenDevTools()
        return
    },
}
```

To use the default role: `toggleDevTools`, it stopped working.

**Comment by asticode** [comment]
It's weird because I've tried adding this menu item to the demo, and it worked:

```go
{
	Accelerator: astilectron.NewAccelerator("CmdOrCtrl", "Shift", "R"),
	Role:        astilectron.MenuItemRoleForceReload,
}
```

When you tried it, did you say the new item in the menu?
