### ISSUE TITLE
Notification not working

### ISSUE THREAD

**Issue by komyg** [asticode/go-astilectron#196]
Hi,

I am trying to show a notification but it is not working. My code is below:

```
          m := connector.window.NewAstiMenu([]*astilectron.MenuItemOptions{
		{
			Accelerator: astilectron.NewAccelerator("CmdOrCtrl", "T"),
			Visible:     astilectron.PtrBool(false),
			OnClick: func(e astilectron.Event) (deleteListener bool) {
				n := a.NewNotification(&astilectron.NotificationOptions{
					Body: "Hello world!",
					//Icon:  "public/logo-onyo.png",
					Title: "Conector Onyo",
				})
				n.Create()
				n.Show()
				return
			},
		},
	})
```

And I expected that my test notification would be shown when I pressed `Ctrl+T`, however this is not happening.

Here are the Astilectron logs:

```
DEBU[0019] Astilectron says: {"name":"menu.item.event.clicked","targetID":"7","menuItemOptions":{"checked":false,"enabled":true,"label":"","visible":false}}
DEBU[0019] Sending to Astilectron: {"name":"notification.cmd.create","targetID":"15","notificationOptions":{"body":"Hello world!","title":"Conector Onyo"}}
DEBU[0019] Astilectron says: {"name":"notification.event.created","targetID":"15"}
DEBU[0019] Sending to Astilectron: {"name":"notification.cmd.show","targetID":"15"}
```

**Comment by asticode** [comment]
@komyg which OS are you working on?

**Comment by komyg** [comment]
Hi @asticode, I am testing on Windows 10.

**Comment by asticode** [comment]
Seems like Windows has some additional needs before being able to display the notifications. Check out [the doc](https://electronjs.org/docs/tutorial/notifications#windows) for more information. Feel free to close this issue if you feel that "fixes" your issue.

**Comment by komyg** [comment]
Yes, I saw that, but even following the instructions (adding my .exe to my home folder), it didn't work...

Anyway, it seems that the web notifications are working for me (the ones that are called with the `Notification` object in javascript), so I think that we can close this issue.

Thanks,
Komyg
