### ISSUE TITLE
Get path to DataDirectory early

### ISSUE THREAD

**Issue by Happy-Ferret** [asticode/go-astilectron#199]
Curious. Is there any way to retrieve the path to the data directory prior to the initial bootstrapping? Running ``astilog.Info(path.Join(a.Paths().DataDirectory(), "resources", "locales"))`` (where a is ``var a *astilectron.Astilectron``, which is assigned during OnWait. Which, judging from the log output, is not soon enough in the boot order) from **main()** results in a runtime error (``invalid memory address or nil pointer dereference``).

I need the path prior to the initialization of MenuOptions, since the menu labels are being translated and I need a way to actually locate the "locales" folder that contains the language specific JSON files.

**Comment by asticode** [comment]
If you use the bootstrap, the soonest you can retrieve the paths is by using the `Adapter` option which is a `func(a *astilectron.Astilectron)`. Would that fix your issue?

**Comment by Happy-Ferret** [comment]
No. That's, unfortunately, still further down the chain and thus results in a nil pointer dereference, as well.

For now I've solved the issue by using [configDir](https://github.com/shibukawa/configdir), utilizing ``AppName`` for the ``vendor-name`` string and leaving the other string parameter empty.

At least on Windows it points to the exact same path ``DataDirectory`` would point to. Hopefully, the same will be true for GNU/Linux and Mac OS.

**Comment by asticode** [comment]
Would that fix it, if I added a `MenuOptionsFunc` option that is a `func(a *astilectron.Astiecltron) []*astilectron.MenuItemOptions` and that would be used instead of `MenuOptions`? That way you can build your label based on paths.

**Comment by Happy-Ferret** [comment]
In theory, that should work. Yes.

**Comment by asticode** [comment]
OK, I've added the option in the bootstrap. Can you let me know whether it fixes your issue?

**Comment by Happy-Ferret** [comment]
Your patch works splendidly. Thank you, so much!

Just did a dry-run (obviously, I still need to load the actual translations. But since I got the path now...)

```go
	if err := bootstrap.Run(bootstrap.Options{
		Asset:    Asset,
		AssetDir: AssetDir,
		AstilectronOptions: astilectron.Options{
			AppName:            AppName,
			AppIconDarwinPath:  "resources/icon.icns",
			AppIconDefaultPath: "resources/icon.png",
		},
		Debug: *debug,
		MenuOptionsFunc: func(app *astilectron.Astilectron) []*astilectron.MenuItemOptions {
			return []*astilectron.MenuItemOptions{{
				Label: astilectron.PtrStr("File"),
				SubMenu: []*astilectron.MenuItemOptions{
					{
						Label:       astilectron.PtrStr(app.Paths().DataDirectory()),
						Accelerator: newAccel,
						OnClick: func(e astilectron.Event) (deleteListener bool) {
							if err := bootstrap.SendMessage(w, "new_map", nil); err != nil {
								astilog.Error(errors.Wrap(err, "sending new_map event failed"))
							}
							return false
						},
					},
				},
			}}
		},
...
```

**Comment by AlexJujushvili** [comment]
![Uploading Capture.PNG…]()
Please help me. how did i get it

**Comment by AlexJujushvili** [comment]
![Capture](https://user-images.githubusercontent.com/13392216/201750798-1aa340db-01c2-4d30-99c7-e864562f46e9.PNG)
I can't help it.  I'm a beginner  :)  please

**Comment by asticode** [comment]
instead of using `a.paths().AppExecutable()` you need to use `a.Paths().AppExecutable()`

**Comment by AlexJujushvili** [comment]
Thank you very much !!! "asticode" is an excellent project ... !
