### ISSUE TITLE
Question: How to create window in another monitor?

### ISSUE THREAD

**Issue by prsolucoes** [asticode/go-astilectron#2]
Hi,

How to create window in another monitor?

I have a desktop app:
https://itunes.apple.com/us/app/prprojector-datashow-projetor-louvor-palestra-m%C3%BAsica/id1050484268?ls=1&mt=12

I want convert to Go with your lib, but i need control window in other monitor.

Thanks.

**Comment by asticode** [comment]
@prsolucoes as of now it's not available but that is a really nice enhancement. I'll start working on it right now.

Unfortunately I won't have a way to test it thoroughly until next Tuesday as I don't have an external monitor at home. We have 2 options:

- if you really want to test it quickly I'll create a new branch on which you'll be able to check whether it's working properly. This way seems quicker but it will take longer to debug as I'll have to wait for your inputs to make changes and chances are we're not in the same timezone :D
- if you don't mind waiting until next week, I'll test it and merge in master next week

What do you think?

**Comment by asticode** [comment]
@prsolucoes I've added bindings for multi screens/displays. This is available in the `dev-display` branch for now but I will merge it as soon as I/somebody can test it's working properly.

Here's how you can create a window in another monitor:

- fetch the available displays:

```go
var displays = a.Displays()
```

- create the window in the proper display:

```go
a.NewWindowInDisplay(yourURL, yourOptions, displays[your display index])
```

- or move the window to the proper display:

```go
w.MoveInDisplay(displays[your display index], yourX, yourY)
```

Let me know how it goes.

**Comment by prsolucoes** [comment]
O.o Thanks. I will test it on thursday, i dont have another monitor here in my home, only on my work. I will test.

Another issue is about icon and app name. On my mac, the icon example is not changed and the title and info is showing Electron and not my app name. How i can solve it?

**Comment by asticode** [comment]
@prsolucoes you were right, there was something wrong with setting your own app name + icon on MacOSX.

However I've fixed it, should be better now :) (still in the `dev-display` branch). I'll merge it in master later this week.

To add your own app name + icon just do the following:

```go
var a, _ = astilectron.New(astilectron.Options{
    AppName: "<your app name>",
    AppIconDefaultPath: "<your .png icon>",
    AppIconDarwinPath:  "<your .icns icon>",
    BaseDirectoryPath: "<where you want the provisioner to install the dependencies>",
})
```

Please close this issue if it fixes your problem.

NOTE : I'm not an expert MacOSX user but I've experienced some cache problem with MacOSX when testing setting a custom icon. Indeed even when setting a legit .icns path I couldn't see the change. I read you have to test it in a new folder as MacOSX is keeping the icon you used in previous tests in its cache. Hope it makes sense.

**Comment by prsolucoes** [comment]
Ok, icons and title on mac is working fine now.

**Comment by asticode** [comment]
@prsolucoes did you have time to test the multi displays?

**Comment by prsolucoes** [comment]
Sorry for late response. It is working OK man. Very nice job. Dont stop !!!!  Im trying remake my app with this, but finding some problems with html outline and auto width, nothing related to your project. Thanks.
