### ISSUE TITLE
Generate a PDF of the current view

### ISSUE THREAD

**Issue by scorredoira** [asticode/go-astilectron#201]
Hi, is it possible to generate a pdf of the current view?

Thank you

**Comment by scorredoira** [comment]
In this post I found that it can be generated using **webContents** but I have no idea where to put this code so I can call it from my application. Can you point me to where to do it?

https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsprinttopdfoptions-callback

https://medium.com/@ishwar.rimal/generating-pdf-with-electron-js-31b59ac93249

# contents.printToPDF(options)

```
const { BrowserWindow } = require('electron')
const fs = require('fs')

let win = new BrowserWindow({ width: 800, height: 600 })
win.loadURL('http://github.com')

win.webContents.on('did-finish-load', () => {
  // Use default printing options
  win.webContents.printToPDF({}, (error, data) => {
    if (error) throw error
    fs.writeFile('/tmp/print.pdf', data, (error) => {
      if (error) throw error
      console.log('Write PDF successfully.')
    })
  })
})
```

**Comment by asticode** [comment]
There are 2 ways for that: either you add this just for your script, either you make PRs to add this to the library. It's up to you.

1) Adding this just for your script

In the `.js` of the page you're trying to print, you can call NodeJS. Therefore, whenever you feel printing is good, you should be able to call `require('electron').remote.getCurrentWindow().webContents.printToPDF({})` and add the proper options. I've not tested it, but that's the way I would try it first.

2) Adding this to the library
- `GO`

Add a `PrintToPDF` function with proper options to the [window](https://github.com/asticode/go-astilectron/blob/master/window.go) struct. This method will send a new event to the `JS`

- `JS`

Intercept the event coming from `GO` and simply call `elements[json.targetID].webContents.printToPDF({})` with options provided by the event.

Of course, I prefer the 2nd option by I can't force you to make PRs 😄

**Comment by scorredoira** [comment]
Great, thank you very much for the info. I will definitely go for the 2nd option :)
