### ISSUE TITLE
Removing electron menu from taskbar context menu

### ISSUE THREAD

**Issue by jesst3r** [asticode/go-astilectron#202]
Greetings, thank you for your framework, its awesome!
Could you help me please, how to remove electron menu from the taskbar context menu? 
Thanks in advance 
![nASPc7n3wt](https://user-images.githubusercontent.com/331591/65532459-82460180-df04-11e9-9b20-f1ffc03237f8.png)

**Comment by asticode** [comment]
@jesst3r I can't reproduce your problem. Could you share the code you're running by any chance? Also, which taskbar context menu are you talking about?
