### ISSUE TITLE
Can i use typescript in this package?

### ISSUE THREAD

**Issue by bettersun** [asticode/go-astilectron#207]
I want to use typescript instead of  javascript.
There is no guide in readme.md.

Should I first compile the typescript file to javascript and copy to the  resource directory?

**Comment by asticode** [comment]
I've never tried it, but that would be how I would do it.

Can you share here the results of your tests ?

**Comment by bettersun** [comment]
I am sorry.
I haven't found the right way.
I just want to know is that possible or not.
If now it is impossible, then i will use the javascript.

Thank you.
