### ISSUE TITLE
go mod download encountered checksum issue.

### ISSUE THREAD

**Issue by polaris112358** [asticode/go-astilectron#209]
Hi, there!

Here is some error when I run go mod, it seems that SUM check not correct:

o: finding github.com/asticode/go-astilectron v0.9.3
go: downloading github.com/asticode/go-astilectron v0.9.3
go: extracting github.com/asticode/go-astilectron v0.9.3
verifying github.com/asticode/go-astiamqp@v1.0.1/go.mod: checksum mismatch
	downloaded: h1:P6ykqiZTrhziRnZP+sfCSTQvvQIJCzSM6Jiv7IH8XpQ=
	sum.golang.org: h1:Xe27K2GHnsEoIgAtHi+udd7xXV5YSQG4nE3ggZoyU/4=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

go env:
$ go env GOPROXY
https://mirrors.aliyun.com/goproxy/

$ go env GOSUMDB
sum.golang.google.cn

**Comment by asticode** [comment]
@polaris112358 thanks for letting me know !

This is linked to https://github.com/asticode/go-astiamqp/issues/1 and I've released `v0.9.4` of `go-astilectron` that should fix the problem.

Does is work now ?

**Comment by polaris112358** [comment]
Yeah, it works fine now!
