### ISSUE TITLE
paths.go:65 undefined os.Executable

### ISSUE THREAD

**Issue by rand99** [asticode/go-astilectron#21]
I'm getting an error when getting the repo (I have electron installed)

```
$ go get -u github.com/asticode/go-astilectron
# github.com/asticode/go-astilectron
../github.com/asticode/go-astilectron/paths.go:65: undefined: os.Executable

$ go version
go version go1.8.3 darwin/amd64

```

**Comment by asticode** [comment]
@rand99 could you provide your `go env` as well?

I'll test Monday on a Mac to see if I can reproduce because I can't on Linux.

Cheers

**Comment by asticode** [comment]
I've upgraded to 1.8.3 on a Mac and I can't reproduce the error. The only thing I can think of is that your go binary is 1.8.3 indeed but your $GOROOT or $GOPATH is pointing to a go version < 1.8.

Could you tell what does the command `go env` output?

**Comment by rand99** [comment]
Thank you, that was the problem.
I had an old go version installed and it got mixed up with the brew version.
Deleting GOROOT from bash_profile and deleting the old version did the trick.
