### ISSUE TITLE
electron-v4.0.1-darwin-x64.zip download every time?

### ISSUE THREAD

**Issue by akzhou** [asticode/go-astilectron#210]
hello!!
go run main.go application would   remove compile directory and download dependency package every time?

`2020/01/14 15:14:59 astikit: starting worker...
2020/01/14 15:14:59 Starting...
2020/01/14 15:14:59 Provisioning...
2020/01/14 15:14:59 Provisioning Astilectron...
2020/01/14 15:14:59 Removing directory /var/folders/8r/fvqs8x2d18g8c40htxjhsybc0000gn/T/go-build597073958/b001/exe/vendor/astilectron
2020/01/14 15:14:59 Downloading https://github.com/asticode/astilectron/archive/v0.34.0.zip into /var/folders/8r/fvqs8x2d18g8c40htxjhsybc0000gn/T/go-build597073958/b001/exe/vendor/astilectron-v0.34.0.zip
2020/01/14 15:14:59 astikit: sending GET request to https://github.com/asticode/astilectron/archive/v0.34.0.zip (1/1)
2020/01/14 15:15:02 Creating directory /var/folders/8r/fvqs8x2d18g8c40htxjhsybc0000gn/T/go-build597073958/b001/exe/vendor/astilectron
2020/01/14 15:15:02 Unzipping /var/folders/8r/fvqs8x2d18g8c40htxjhsybc0000gn/T/go-build597073958/b001/exe/vendor/astilectron-v0.34.0.zip/astilectron-0.34.0 into /var/folders/8r/fvqs8x2d18g8c40htxjhsybc0000gn/T/go-build597073958/b001/exe/vendor/astilectron
2020/01/14 15:15:02 Provisioning Electron...
2020/01/14 15:15:02 Removing directory /var/folders/8r/fvqs8x2d18g8c40htxjhsybc0000gn/T/go-build597073958/b001/exe/vendor/electron-darwin-amd64
2020/01/14 15:15:02 Downloading https://github.com/electron/electron/releases/download/v4.0.1/electron-v4.0.1-darwin-x64.zip into /var/folders/8r/fvqs8x2d18g8c40htxjhsybc0000gn/T/go-build597073958/b001/exe/vendor/electron-darwin-amd64-v4.0.1.zip
2020/01/14 15:15:02 astikit: sending GET request to https://github.com/electron/electron/releases/download/v4.0.1/electron-v4.0.1-darwin-x64.zip (1/1)
`

**Comment by asticode** [comment]
@akzhou `astilectron` will download all dependencies in the path provided in the `BaseDirectoryPath` option. If the option is not set, it will download them in the executable path.

Moreover you're using `go run` which :

- creates a temporary folder (`/var/folders/8r/fvqs8x2d18g8c40htxjhsybc0000gn/T/go-build597073958/b001/exe` in your case)
- runs your go code inside it
- removes the temporary folder

Therefore, all dependencies are downloaded in the temporary folder and removed once the execution is done.

You have 2 options to change that behavior:

- keep using `go run` but provide a specific `BaseDirectoryPath` option (e.g. `/tmp/astilectron`)
- use `go build` instead and run the binary

Does that answer your question?

**Comment by akzhou** [comment]
> @akzhou `astilectron` will download all dependencies in the path provided in the `BaseDirectoryPath` option. If the option is not set, it will download them in the executable path.
> 
> Moreover you're using `go run` which :
> 
> * creates a temporary folder (`/var/folders/8r/fvqs8x2d18g8c40htxjhsybc0000gn/T/go-build597073958/b001/exe` in your case)
> * runs your go code inside it
> * removes the temporary folder
> 
> Therefore, all dependencies are downloaded in the temporary folder and removed once the execution is done.
> 
> You have 2 options to change that behavior:
> 
> * keep using `go run` but provide a specific `BaseDirectoryPath` option (e.g. `/tmp/astilectron`)
> * use `go build` instead and run the binary
> 
> Does that answer your question?

Got it!! Thank you

**Comment by asticode** [comment]
Cheers
