### ISSUE TITLE
How do I automatically update a compiled project application GUI

### ISSUE THREAD

**Issue by lengnuan-v** [asticode/go-astilectron#211]
For example, update the application version on the server, prompt for update on the client, and automatically update to the latest version after confirmation

**Comment by asticode** [comment]
@lengnuan-v unfortunately you can't right now 😞 But this issue is already tracked [here](https://github.com/asticode/go-astilectron-bootstrap/issues/1).

Let me know if you feel like submitting a PR. I'll close this issue for now.
