### ISSUE TITLE
Could I open dialog in Golang side?

### ISSUE THREAD

**Issue by extrame** [asticode/go-astilectron#212]
as title

**Comment by asticode** [comment]
@extrame you will need to send a message from GO to JS using this GO code:

```go
w.SendMessage("open.dialog", nil)
```

and intercept it in JS to open the dialog the way you want using this JS code:

```javascript
// This will wait for the astilectron namespace to be ready
document.addEventListener('astilectron-ready', function() {
    // This will listen to messages sent by GO
    astilectron.onMessage(function(message) {
        // Process message
        if (message === "open.dialog") {
            astilectron.showOpenDialog({}, function() {});
        }
    });
})
```

Available dialogs are listed [here](https://github.com/asticode/astilectron/blob/master/index.js#L477) with available arguments.

Does answer your question ?
