### ISSUE TITLE
Astilectron 0.35.0 astilectron.showOpenDialog callback not work

### ISSUE THREAD

**Issue by oldfeel** [asticode/go-astilectron#214]
After upgrade to Astilectron 0.35.0, astilectron.showOpenDialog callback not work.
Astilectron 0.34.0 and Electron 4.0.1 is ok.

Astilectron: 0.35.0
Electron: 7.1.10

````
      astilectron.showOpenDialog({
        propertkies: ['openFile'],
        title: "title",
        buttonLabel: "submit",
        filters: [{ name: "Wow", extensions: ["exe"] }]
      }, paths => {
        // this line not work
        console.log("paths " + paths)
      })
````

**Comment by asticode** [comment]
This was my mistake to provide such methods in the `astilectron` namespace in the first place.

I've removed them and I've updated the doc.

[Check it out](https://github.com/asticode/go-astilectron#dialogs) : now you need to `require` the `dialog` package yourself and use the available methods.

Such methods have evolved between Electron `4.0.1` and `7.1.10` : methods with a `Sync` prefix return the result and you should execute the callback on this result. Methods without the `Sync` prefix returns a `Promise` and you need to use `.then()` to get the result. The Electron doc contains examples.

Let me know if that fixes your problem.

**Comment by oldfeel** [comment]
Thank you very much! In react i use
````
const { dialog } = window.require('electron').remote
````
This work for me.
