### ISSUE TITLE
Open file dialog

### ISSUE THREAD

**Issue by adambrakhane** [asticode/go-astilectron#216]
I recently had to upgrade the astielectron version (only committed my code and lost the scr dirs above) and while most of the API changes were easy to change for it looks like I no longer have access to the electron file dialog.

I need to open a dialog to a _file that does not yet exist_. I used to do that like this:
```
if (typeof dialog != "undefined") {
     filename = dialog.showSaveDialog(null,{"title":"Save Master Inventory File","defaultPath":"inventory.xlsx"})
} else {
     filename = "browser_test.xlsx"
}
```
Where the "undefined" check let me run the code in a browser during development. Now, it seems like "dialog" is always undefined. 

I checked around the new examples and found:
```
astilectron.showOpenDialog({message: "Select files", properties: ['openFile', 'multiSelections'], title: "Select files"}, function(paths) {
```

But 1) it seems like that only can reference existing files, it's not really meant for creating a new file. 2) Is not defined either. This is the debug console inside my astilectron app:
![image](https://user-images.githubusercontent.com/4698659/75306744-8eb1eb80-580f-11ea-9478-6da5b299085a.png)

![image](https://user-images.githubusercontent.com/4698659/75306761-9d000780-580f-11ea-8f14-2caf5108c30b.png)

Can you help?

**Comment by asticode** [comment]
I recently removed the `astilectron` dialog methods since it was only wrapping `electron` ones. I've updated the [doc](https://github.com/asticode/go-astilectron#dialogs) to show how to use `dialogs` now. `dialog` should not be `undefined` if you follow the doc.

Let me know if that fixes your problem.

**Comment by adambrakhane** [comment]
Perfect, thanks.
