### ISSUE TITLE
How to hide Dev Tools in mac menubar

### ISSUE THREAD

**Issue by xiusin** [asticode/go-astilectron#220]
eg: `edit`, `view`, `window`, `help`

**Comment by asticode** [comment]
I think you need to [set your own menu](https://github.com/asticode/go-astilectron#menus) for that. It will overwrite the default one.

Does that answer your question?

**Comment by xiusin** [comment]
@asticode 
![cut](https://user-images.githubusercontent.com/36065131/76043407-6f932680-5f92-11ea-8c74-7686cb984aae.png) 
I did not setting any menu. But the menu bar still shows that

**Comment by asticode** [comment]
@xiusin you need to set your own menu to override the default one.

**Comment by xiusin** [comment]
@asticode thinks, i have solved it
