### ISSUE TITLE
Packaged app tips require MAC OS 10.15 or later

### ISSUE THREAD

**Issue by tieing** [asticode/go-astilectron#226]
![image](https://user-images.githubusercontent.com/29286699/78094377-02df4080-7407-11ea-95f8-2fa9f264278c.png)

My mac version is 10.14.6 and I use the examples in the library for packaging! But it doesn't work after packaging. Where can I change the system version requirements? I have added it to my 'bundler.json'

```
 "info_plist"{
"LSMinimumSystemVersion": "10.13.1"
}
```
Please help me

**Comment by 976546460** [comment]
![image](https://user-images.githubusercontent.com/29286699/78095572-e1338880-7409-11ea-9af1-d810f98b2445.png)
I opened the binary in the package and double-clicking it works!

**Comment by asticode** [comment]
Can check [this comment](https://github.com/asticode/go-astilectron/issues/109#issuecomment-453226390) out ?

**Comment by tieing** [comment]
ok , thank you very much
