### ISSUE TITLE
Use html/template along with astilectron-bootstrap?

### ISSUE THREAD

**Issue by chinenual** [asticode/go-astilectron#228]
I am trying to adapt the demo project to serve "templated" HTML files (using "html/template"), but am not sure that that's compatible with the bootstrap module.  

I see an older project using astielectron (perhaps written before bootstrap was available) that does use templates (https://github.com/veecue/GroupMatcher). It directly sets  up http handlers and a local web server and directly calls a.Start(), a.NewWindow(), a.NewMenu(), a.Wait(), etc.  Should emulate that project's more verbose initialization or is there a way to intercept page handlers so I can apply templates?

**Comment by asticode** [comment]
I think your best bet would indeed be to spawn an http server that would serve your templates. Then, I think all you'd have to do would be to specify you http server homepage [here](https://github.com/asticode/go-astilectron-demo/blob/master/main.go#L90).

Does that fix your problem ?

**Comment by chinenual** [comment]
I had tried that, but had trouble keeping the builtin service serving untemplated pages vs. http server serving its pages.   Surely just my inexperience with the library.  In the end I gave up am refactoring my app as a SPA and using electron IPC to inject content rather than relying on html/template.  Perhaps someone else will try this and post an example of how best to do it...

**Comment by asticode** [comment]
> had trouble keeping the builtin service serving untemplated pages vs. http server serving its pages

Why not, in your custom server, add 2 routes :

- one that would serve static files (untemplated pages)
- one that would serve template files

**Comment by chinenual** [comment]
I wish I'd kept a snapshot of the code I was using... I did have two routes (one serving templates, the other serving static files).  My guess is that I didn't sufficiently distinguish the route paths from the path served automatically by astilectron.  Looking back, it doesn't seem hard to do what I wanted to do and I can't recall enough of the details to explain why I couldn't get it to work.

**Comment by asticode** [comment]
No worries, hope your new solution is working nicely.

Cheesr
