### ISSUE TITLE
examples error

### ISSUE THREAD

**Issue by deepch** [asticode/go-astilectron#23]
github.com/asticode/go-astilectron/examples/5.single_binary_distribution

bash-3.2$ go run *.go
# command-line-arguments
./main.go:34: undefined: Asset
bash-3.2$

**Comment by asticode** [comment]
First of all thanks for your interest in `go-astilectron`.

As specified in the readme:

```5.single_binary_distribution shows how to use go-astilectron in a unique binary. For this example you have to run one of the previous examples (so that the .zip files exist) and run the following commands:

$ go generate examples/5.single_binary_distribution/main.go
$ go run examples/5.single_binary_distribution/main.go examples/5.single_binary_distribution/vendor.go -v
```

Therefore in order for this example to work properly, you have to run `go generate main.go` first.

Does this fix your problem?

**Comment by deepch** [comment]
thx yes it fix problem

I build it  go build examples/5.single_binary_distribution/main.go examples/5.single_binary_distribution/vendor.go

if run console ./main work
if run finder on Mac OS windows closes 1 sec

**Comment by asticode** [comment]
Are you sure you have the correct permissions to run the file from the Finder? Is there any error message?

**Comment by deepch** [comment]
thx I my fail
