### ISSUE TITLE
How to close the app over tray menu

### ISSUE THREAD

**Issue by ThomasCybulski** [asticode/go-astilectron#230]
Hi,

I'm struggling a bit to close the running application over the tray menu. I'm using the bundler and I added the following code:

```
TrayOptions: &astilectron.TrayOptions{
	Image: astikit.StrPtr("resources/icon.png"),
	Tooltip: astikit.StrPtr("Your tooltip"),
},
TrayMenuOptions: []*astilectron.MenuItemOptions{{
	Label: astikit.StrPtr("Close"),
	OnClick: func(e astilectron.Event) (deleteListener bool) {
		// ?
		return
	},
}},
```

What can I insert in the OnClick function? Has anyone an idea?
Thanks!

**Comment by asticode** [comment]
Sure, you should be able to use the [Quit](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L386) method.

Let me know whether that fixes your problem.

**Comment by ThomasCybulski** [comment]
Thank you! Works fine!
