### ISSUE TITLE
macOS  10.15.4  Can't open App 

### ISSUE THREAD

**Issue by kmend** [asticode/go-astilectron#234]
Building for os darwin and arch amd64 astilectron: 0.37.0 electron: 7.1.10

go run main.go   everything is normal

astilectron-bundler

Packaged success， Can't open App 

Compile log：

xxx@xxxdeMacBook-Pro go-astilectron-demo % astilectron-bundler                              
2020/04/22 14:36:55 Bundling for environment darwin/amd64
2020/04/22 14:36:55 Binding data
2020/04/22 14:36:55 Removing /var/folders/bm/zxtnm93x4ngdd2y2tn1hv_cm0000gn/T/astibundler/bind
2020/04/22 14:36:55 Creating /var/folders/bm/zxtnm93x4ngdd2y2tn1hv_cm0000gn/T/astibundler/bind
2020/04/22 14:36:55 Creating /var/folders/bm/zxtnm93x4ngdd2y2tn1hv_cm0000gn/T/astibundler/bind/vendor_astilectron_bundler
2020/04/22 14:36:55 Creating /var/folders/bm/zxtnm93x4ngdd2y2tn1hv_cm0000gn/T/astibundler/cache
2020/04/22 14:36:55 /var/folders/bm/zxtnm93x4ngdd2y2tn1hv_cm0000gn/T/astibundler/cache/astilectron-0.37.0.zip already exists, skipping download of https://github.com/asticode/astilectron/archive/v0.37.0.zip
2020/04/22 14:36:55 Copying /var/folders/bm/zxtnm93x4ngdd2y2tn1hv_cm0000gn/T/astibundler/cache/astilectron-0.37.0.zip to /var/folders/bm/zxtnm93x4ngdd2y2tn1hv_cm0000gn/T/astibundler/bind/vendor_astilectron_bundler/astilectron.zip
2020/04/22 14:36:55 /var/folders/bm/zxtnm93x4ngdd2y2tn1hv_cm0000gn/T/astibundler/cache/electron-darwin-amd64-7.1.10.zip already exists, skipping download of https://github.com/electron/electron/releases/download/v7.1.10/electron-v7.1.10-darwin-x64.zip
2020/04/22 14:36:55 Copying /var/folders/bm/zxtnm93x4ngdd2y2tn1hv_cm0000gn/T/astibundler/cache/electron-darwin-amd64-7.1.10.zip to /var/folders/bm/zxtnm93x4ngdd2y2tn1hv_cm0000gn/T/astibundler/bind/vendor_astilectron_bundler/electron.zip
2020/04/22 14:36:55 Creating /var/folders/bm/zxtnm93x4ngdd2y2tn1hv_cm0000gn/T/astibundler/bind/resources
2020/04/22 14:36:55 Copying /Users/xxx/Downloads/go-astilectron-demo/resources to /var/folders/bm/zxtnm93x4ngdd2y2tn1hv_cm0000gn/T/astibundler/bind/resources
2020/04/22 14:36:55 Generating /Users/xxx/Downloads/go-astilectron-demo/bind_darwin_amd64.go
2020/04/22 14:36:58 Removing /Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64
2020/04/22 14:36:58 Creating /Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64
2020/04/22 14:36:58 Building for os darwin and arch amd64 astilectron: 0.37.0 electron: 7.1.10
2020/04/22 14:36:58 Executing go build -ldflags -X "main.AppName=Astilectron demo" -X "main.BuiltAt=2020-04-22 14:36:58.873195 +0800 CST m=+3.191675902" -X "main.VersionAstilectron=0.37.0" -X "main.VersionElectron=7.1.10" -o /Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64/binary .
2020/04/22 14:37:07 Creating /Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/MacOS
2020/04/22 14:37:07 Moving /Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64/binary to /Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/MacOS/Astilectron demo
2020/04/22 14:37:07 Chmoding /Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/MacOS/Astilectron demo
2020/04/22 14:37:07 Creating /Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/Resources
2020/04/22 14:37:07 Copying /Users/xxx/Downloads/go-astilectron-demo/resources/icon.icns to /Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/Resources/Astilectron demo.icns
2020/04/22 14:37:07 Adding Info.plist to /Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/Info.plist

App Contents Only 3 generated

Info.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>CFBundleIconFile</key>
		<string>Astilectron demo.icns</string>
		<key>CFBundleDisplayName</key>
		<string>Astilectron demo</string>
		<key>CFBundleExecutable</key>
		<string>Astilectron demo</string>
		<key>CFBundleName</key>
		<string>Astilectron demo</string>
		<key>CFBundleIdentifier</key>
		<string>com.Astilectron demo</string>
		<key>LSUIElement</key>
		<string>NO</string>
		<key>CFBundlePackageType</key>
		<string>APPL</string>
	</dict>
</plist>
```

MacOS
    Astilectron demo   --- 74mb

Resources
    Astilectron demo.icns

Is this a complete package? Can't open App , Seek help， thanks~~

**Comment by asticode** [comment]
Can you run `/Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/MacOS/Astilectron demo` and paste logs here ?

**Comment by kmend** [comment]
> Can you run `/Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/MacOS/Astilectron demo` and paste logs here ?

There are only 3 files in the package after packaging. 

/Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/MacOS/Astilectron demo


log is the compilation log, the log after running astilectron-bundler

I don't know if this is a complete package, it can't be run

**Comment by asticode** [comment]
This is normal that there are 3 files only after bundling. All resources are binded to the binary (that's why it's so big).

Execution is failing but there must be logs when it does. Therefore I need you to run `/Users/xxx/Downloads/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app/Contents/MacOS/Astilectron demo` manually which means running the binary generated by the packaging. This  log is not the one after running astilectron-bundler.

**Comment by 84570829** [comment]
macos 10.13.6 
App doesn't work but binary does
this log：
/Users/samir/gocode/app/cbdesk_ast/output/darwin-amd64/cbc.app/Contents/MacOS/cbc ; exit;
astikit: starting worker...
Starting...
Provisioning...
Astilectron has already been provisioned to version 0.41.0, moving on...
Provisioning Electron...
Removing directory /Users/samir/gocode/app/cbdesk_ast/output/darwin-amd64/cbc.app/Contents/MacOS/vendor/electron-darwin-amd64
Downloading https://github.com/electron/electron/releases/download/v7.1.10/electron-v7.1.10-darwin-x64.zip into /Users/samir/gocode/app/cbdesk_ast/output/darwin-amd64/cbc.app/Contents/MacOS/vendor/electron-darwin-amd64-v7.1.10.zip
/Users/samir/gocode/app/cbdesk_ast/output/darwin-amd64/cbc.app/Contents/MacOS/vendor/electron-darwin-amd64-v7.1.10.zip already exists, skipping download...
Creating directory /Users/samir/gocode/app/cbdesk_ast/output/darwin-amd64/cbc.app/Contents/MacOS/vendor/electron-darwin-amd64
Unzipping /Users/samir/gocode/app/cbdesk_ast/output/darwin-amd64/cbc.app/Contents/MacOS/vendor/electron-darwin-amd64-v7.1.10.zip into /Users/samir/gocode/app/cbdesk_ast/output/darwin-amd64/cbc.app/Contents/MacOS/vendor/electron-darwin-amd64
Finishing provisioning electron for darwin system
Copying /Users/samir/gocode/app/cbdesk_ast/output/darwin-amd64/cbc.app/Contents/MacOS/resources/icon.icns to /Users/samir/gocode/app/cbdesk_ast/output/darwin-amd64/cbc.app/Contents/MacOS/vendor/electron-darwin-amd64/Electron.app/Contents/Resources/electron.icns
Closing...
astikit: stopping worker...

**Comment by asticode** [comment]
Are you running the [demo](https://github.com/asticode/go-astilectron-demo) or some custom code? If you're running custom code, can you share it by any chance?
