### ISSUE TITLE
macos 10.15.4 start app failed

### ISSUE THREAD

**Issue by xiusin** [asticode/go-astilectron#235]
Start for the first time after building the app， i got the next error msg.
```
[2020/04/24 10:00] main.go:152: [ERRO] running bootstrap failed: starting astilectron failed: provisioning failed: provisioning astilectron failed: 
unzipping /xxx/xxx.app/Contents/MacOS/vendor/astilectron-v0.38.0.zip/astilectron-0.38.0 
into 
/xxx/xxx.app/Contents/MacOS/vendor/astilectron failed: unzipping /xxx/xxx.app/Contents/MacOS/vendor/astilectron-v0.38.0.zip/astilectron-0.38.0 into /xxx/xxx.app/Contents/MacOS/vendor/astilectron failed: 
astikit: content in archive does not match specified internal path astilectron-0.38.0

```
![image](https://user-images.githubusercontent.com/36065131/80167553-40547980-8613-11ea-8a79-cdbb593037aa.png)

**Comment by asticode** [comment]
There must be a difference of `astilectron` version between the `bundler` and `go-astilectron` lib. Could you run `go install github.com/asticode/go-astilectron-bundler/astilectron-bundler` and try again packaging your app ?

**Comment by xiusin** [comment]
@asticode thinks. it's ok
