### ISSUE TITLE
electron.exe exit code:1

### ISSUE THREAD

**Issue by ewener** [asticode/go-astilectron#236]
When I run demo successfully and then close, it always prints an error as the title。

environment：
- win10
- go 1.14
- electron 7.1.10
- astilectron 0.38.0

**Comment by asticode** [comment]
Can you print the full logs?

**Comment by ewener** [comment]
> Can you print the full logs?

2020/04/28 19:52:02 Running app built at
2020/04/28 19:52:02 astikit: starting worker...

2020/04/28 19:52:02 Skipping restoring resources...
2020/04/28 19:52:02 Starting...
2020/04/28 19:52:02 Provisioning...
2020/04/28 19:52:02 Astilectron has already been provisioned to version 0.38.0, moving on...
2020/04/28 19:52:02 Electron has already been provisioned to version 7.1.10, moving on...
2020/04/28 19:52:02 Listening...
2020/04/28 19:52:02 Executing...
2020/04/28 19:52:02 Starting cmd C:\Users\yamei\AppData\Roaming\vendor\electron-windows-amd64\electron.exe C:\Users\yamei\AppData\Ro
aming\vendor\astilectron\main.js 127.0.0.1:49904 true
2020/04/28 19:52:03 Stdout says:
2020/04/28 19:52:03 Astilectron says: {"name":"app.event.ready","targetID":"app","displays":{"all":[{"id":2528732444,"bounds":{"x":0
,"y":0,"width":1280,"height":720},"workArea":{"x":0,"y":0,"width":1280,"height":690},"accelerometerSupport":"unknown","monochrome":f
alse,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"
width":1280,"height":720},"workAreaSize":{"width":1280,"height":690},"scaleFactor":1.5,"rotation":0,"internal":false,"touchSupport":
"unknown"}],"primary":{"id":2528732444,"bounds":{"x":0,"y":0,"width":1280,"height":720},"workArea":{"x":0,"y":0,"width":1280,"height
":690},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, ma
trix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1280,"height":720},"workAreaSize":{"width":1280,"height":690},"scaleFac
tor":1.5,"rotation":0,"internal":false,"touchSupport":"unknown"}},"supported":{"notification":true}}
2020/04/28 19:52:03 Sending to Astilectron: {"name":"window.cmd.create","targetID":"1","sessionId":"2","url":"c:\\Users\\yamei\\AppD
ata\\Roaming\\resources\\app\\index.html","windowOptions":{"backgroundColor":"#333","center":true,"height":700,"icon":"C:\\Users\\ya
mei\\AppData\\Roaming\\resources\\icon.png","width":700}}
2020/04/28 19:52:03 Astilectron says: {"name":"window.event.focus","targetID":"1"}
2020/04/28 19:52:06 Astilectron says: {"name":"window.event.did.finish.load","targetID":"1"}
2020/04/28 19:52:06 Sending to Astilectron: {"name":"menu.cmd.create","targetID":"3","menu":{"id":"3","items":[{"id":"4","options":{
"label":"File"},"rootId":"app","submenu":{"id":"5","items":[{"id":"6","options":{"label":"About"},"rootId":"app"},{"id":"7","options
":{"role":"close"},"rootId":"app"},{"id":"8","options":{"type":"separator"},"rootId":"app"},{"id":"9","options":{"accelerator":"Cont
rol+d","label":"Debug","type":"checkbox"},"rootId":"app"}],"rootId":"app"}}],"rootId":"app"}}
2020/04/28 19:52:06 Astilectron says: {"name":"menu.event.created","targetID":"3"}
2020/04/28 19:52:06 astikit: worker is now waiting...
2020/04/28 19:52:06 Astilectron says: {"name":"window.event.message","targetID":"1","message":{"name":"explore"},"callbackId":"1"}
2020/04/28 19:52:06 Sending to Astilectron: {"name":"window.cmd.message.callback","targetID":"1","callbackId":"1","message":{"name":
"explore.callback","payload":{"dirs":[...],"files":{"data":{"datasets":[{"backgroundColor":["rgba(255, 206, 86, 0.2)","rgba(75, 192, 192, 0.2)","rgba(255, 99, 132, 0.2)"
,"rgba(54, 162, 235, 0.2)","rgba(153, 102, 255, 0.2)"],"borderColor":["rgba(255, 206, 86, 1)","rgba(75, 192, 192, 1)","rgba(255,99,1
32,1)","rgba(54, 162, 235, 1)","rgba(153, 102, 255, 1)"],"data":[3145728,606208,524288,524288,1144873]}],"labels":["NTUSER.DAT","ntu
ser.dat.LOG1","NTUSER.DAT{1464e577-bb5c-11e9-8f77-9cb6d0c8fb2d}.TMContainer00000000000000000001.regtrans-ms","NTUSER.DAT{1464e577-bb
5c-11e9-8f77-9cb6d0c8fb2d}.TMContainer00000000000000000002.regtrans-ms","other"]},"type":"pie"},"files_count":27,"files_size":"5Mb",
"path":"C:\\Users\\my"}}}
2020/04/28 19:52:11 Sending to Astilectron: {"name":"window.cmd.message","targetID":"1","message":{"name":"check.out.menu","payload"
:"Don't forget to check out the menu!"}}
2020/04/28 19:52:11 Astilectron says: {"name":"app.cmd.quit","targetID":"app"}
2020/04/28 19:52:11 Astilectron says: {"name":"window.event.closed","targetID":"1"}
2020/04/28 19:52:11 Stopping...
2020/04/28 19:52:11 astikit: stopping worker...
2020/04/28 19:52:12 'C:\Users\yamei\AppData\Roaming\vendor\electron-windows-amd64\electron.exe' exited with code: 1
2020/04/28 19:52:12 App has closed
2020/04/28 19:52:12 Closing...
2020/04/28 19:52:12 Stopping...
2020/04/28 19:52:12 accept tcp 127.0.0.1:49904: use of closed network connection while TCP accepting

**Comment by asticode** [comment]
This is "normal", the electron binary seems to return a status code != 0 in that case. You can ignore it in this case.
