### ISSUE TITLE
astikit: received signal urgent I/O condition

### ISSUE THREAD

**Issue by chinenual** [asticode/go-astilectron#239]
I am consistently seeing tons of "astikit: received signal urgent I/O condition" messages in my log the first time I run my application (I presume it is while unpacking all the resources).  I'll get hundreds of these during startup.   On subsequent invocations, I'll see a couple dozen of these during startup - but not nearly as many.

Machine is a 16G macbook pro (disk is SSD).  I don't _think_ I have I/O problems in general...

I see @asticode's comment in that this is unusual and sign of "bad things".  What might be the cause?  I don't notice any other problems, but I may not be looking the right places.  Should I be worried?

@asticode 's original comment: https://github.com/asticode/go-astilectron/issues/225#issuecomment-605412608_

**Comment by asticode** [comment]
In fact I'm getting those consistently too in perfectly fine case... I think the handling of this signal has been added to GO recently and logging it is not necessary.

Therefore I've updated an [IgnoredSignals](https://github.com/asticode/go-astilectron-bootstrap/blob/master/options.go#L17) attribute to the `bootstrap` options, just put `[]os.Signal{syscall.SIGURG}` if you want to ignore those signals.

**Comment by chinenual** [comment]
Sounds perfect.  A silly question: is this something I can try immediately or is it pending a new go-astielectron release?  I just refreshed go-astielectron and the new field is not yet recognized:
```
# go get -u github.com/asticode/go-astilectron
go: github.com/asticode/go-astilectron upgrade => v0.14.2
go: downloading github.com/asticode/go-astilectron v0.14.2
go: downloading github.com/asticode/go-astikit v0.6.0
go: github.com/asticode/go-astikit upgrade => v0.6.0
...
# astilectron-bundler
...
./main.go:320:3: unknown field 'IgnoredSignals' in struct literal of type bootstrap.Options

```

**Comment by asticode** [comment]
@chinenual you need to fetch changes in the `bootstrap` as well

**Comment by chinenual** [comment]
D'oh!  Works, of course.    Apparently the Windows runtime doesn't use SIGURG, so I had to declare the variables in platform specific files, but it's working fine.  Thanks again!
