### ISSUE TITLE
Can i use the resize in bootstrap

### ISSUE THREAD

**Issue by deepch** [asticode/go-astilectron#24]
I create

```
MessageHandler: func(w *astilectron.Window, m bootstrap.MessageIn) {
			if err := w.Resize(200, 200); err != nil {
				log.Println(err)
			}
		},
```

and 

```
<script>
    function clickelemet() {
            astilectron.send({name: "say", payload: {message: "hello"}})
    }
</script>
```

At the first click the window changes its size but then stops doing it.

**Comment by deepch** [comment]
w.Resize(200, 200) lock 
if use work any time
go w.Resize(200, 200)

Please tell me how to properly resize the window using bootstrap

**Comment by asticode** [comment]
1. Regarding your first problem, let's assume your window is 400x400. The first time you click on the button, the window is resized from 400x400 to 200x200 therefore you see the window being resized. The second and next times you click on the button, the window is resized from 200x200 to 200x200 so nothing happens. It's normal behavior.

**Comment by asticode** [comment]
2. Can you paste the code where you see `w.Resize` being locked?

If your goal is to simply set the initial size of the Window, you can use the `Height` and `Width` attributes of the `WindowOptions` of the Bootstrap options.

**Comment by deepch** [comment]
1. I certainly stretched the window before the second push.
2. Any example use MessageHandler: + w.Resize 

```
MessageHandler: func(w *astilectron.Window, m bootstrap.MessageIn) {
			if err := w.Resize(200, 200); err != nil {
				log.Println(err)
			}
log.Println("I not locked")
		},
```

**Comment by deepch** [comment]
1. problem full lock MessageHandler + bootstrap  next click no receive func MessageHandler
if 

```
w.Resize(200, 200);  <----------------- locked
time.Sleep(1*time.Second)
w.Resize(400, 400);

```
windows resize 200x200 and stop any actions lock 

if 

```
go w.Resize(200, 200);
time.Sleep(1*time.Second)
go w.Resize(400, 400);

```
windows resize 200x200 and after 1 sec  400x400

this problem use bootstrap +  MessageHandler

I just wanted to change the size of the window after authorization.

2. yes

**Comment by asticode** [comment]
Can you run your program with the `-v` flag and paste the logs when it happens here?

**Comment by deepch** [comment]
thx I redesign it
