### ISSUE TITLE
Linux: unexpected popup when invoking dialog.showSaveDialogSync()

### ISSUE THREAD

**Issue by chinenual** [asticode/go-astilectron#241]
This is a weird one.  Probably an electron issue rather than astilectron, but I'l try here first (since it will be awkward to have to explain how my main process is in golang to the electron devs...). 

I am cross compiling to Mac, Windows and Linux.  Almost everything works great, except I'm seeing an unwanted popup notification "sometimes" when I show a native Save dialog.  This doesn't happen on every invocation.  I can open the dialog one or two times with no abnormal behavior, but at some point, when I call dialog.showSaveDialogSync(), electron pops up a notification in front of the dialog with a stretched version of my appicon as the body of the window and the message "Electron "<title>" is ready" (screenshot attached below).   The "<title>" appears to be the native file dialog's title (in the screenshot I captured, below the dialog had no title, so it appears as ""). After a few seconds the popup goes away on its own.

This only happens on Linux. I've never seen it happen on Mac or Windows.

I've tried newer versions of electron (both 7.2.4 and 8.2.5) and both show the same behavior.  I've grepped electron and astielectron sources and don't see where this might be happening...

Ideas?

Here's how I'm invoking the dialog (in my app/static/js/index.js): 

```
const {dialog} = require('electron').remote;
...
    saveSYNDialog: function() {
	path = dialog.showSaveDialogSync({
	    filters: [
		{ name: 'State', extensions: ['syn'] },
		{ name: 'All Files', extensions: ['*'] }],
            properties: ['openFile', 'promptToCreate']
	});
	console.log("in fileDialog: " + path);
```
![Untitled](https://user-images.githubusercontent.com/1839327/81023918-dec8b200-8e3f-11ea-91b4-22bdcd9dc77f.png)

**Comment by chinenual** [comment]
Apparently I'm not the first to notice this.  It's been reported to the Electron project - but I don't see any sign of any effort to fix.   If anyone has any ideas for a workaround, I'm all ears! 

https://github.com/electron/electron/issues/20025

**Comment by asticode** [comment]
Mmmm unfortunately I don't see any possible workaround in the `astilectron` ecosystem, sorry 😞

**Comment by chinenual** [comment]
That's what I figured.   I'll close this issue - if anyone stumbles on this in the future, the Electron bug is logged as https://github.com/electron/electron/issues/20025
