### ISSUE TITLE
Nested WEB pages, prompt: Uncaught TypeError: window.jQuery is not a function

### ISSUE THREAD

**Issue by lengnuan-v** [asticode/go-astilectron#244]
Nested WEB pages, prompt: Uncaught TypeError: window.jQuery is not a function

**Comment by lengnuan-v** [comment]
`func main() {
	// Parse flags
	flag.Parse()

	// Set up logger

	// 日志
	l := log.New(log.Writer(), log.Prefix(), log.Flags())

	// Get base dir path
	var err error
	var p = "./resources/icon"

	// Create astilectron
	var a *astilectron.Astilectron
	if a, err = astilectron.New(log.New(os.Stderr, "", 0),astilectron.Options{
		AppName:            "Astilectron",
		AppIconDefaultPath: "app.png",
		AppIconDarwinPath:  "app.icns",
		BaseDirectoryPath:  p,
	}); err != nil {
		l.Fatal(errors.Wrap(err, "creating new astilectron failed"))
	}
	defer a.Close()
	a.HandleSignals()

	// Start
	if err = a.Start(); err != nil {
		l.Fatal(errors.Wrap(err, "starting failed"))
	}

	// Create window
	var w *astilectron.Window
	if w, err = a.NewWindow("http://127.0.0.1", &astilectron.WindowOptions{
		Center: astikit.BoolPtr(true),
		Height: astikit.IntPtr(600),
		Width:  astikit.IntPtr(600),
	}); err != nil {
		l.Fatal(errors.Wrap(err, "new window failed"))
	}
	if err = w.Create(); err != nil {
		l.Fatal(errors.Wrap(err, "creating window failed"))
	}

	w.OpenDevTools()
	// Add listener
	w.On(astilectron.EventNameWindowEventMove, func(e astilectron.Event) (deleteListener bool) {
		l.Println("Window moved")
		return
	})

	// Simulate actions
	//go func() {
	//	time.Sleep(time.Second)
	//	if err = w.Move(0, 0); err != nil {
	//		l.Fatal(errors.Wrap(err, "moving window failed"))
	//	}
	//	time.Sleep(time.Second)
	//	if err = w.Resize(200, 200); err != nil {
	//		l.Fatal(errors.Wrap(err, "resizing window failed"))
	//	}
	//	time.Sleep(time.Second)
	//	if err = w.Maximize(); err != nil {
	//		l.Fatal(errors.Wrap(err, "maximizing window failed"))
	//	}
	//	time.Sleep(time.Second)
	//	if err = w.Unmaximize(); err != nil {
	//		l.Fatal(errors.Wrap(err, "unmaximizing window failed"))
	//	}
	//	time.Sleep(time.Second)
	//	if err = w.Minimize(); err != nil {
	//		l.Fatal(errors.Wrap(err, "minimizing window failed"))
	//	}
	//	time.Sleep(time.Second)
	//	if err = w.Restore(); err != nil {
	//		l.Fatal(errors.Wrap(err, "restoring window failed"))
	//	}
	//	time.Sleep(time.Second)
	//	if err = w.Resize(600, 600); err != nil {
	//		l.Fatal(errors.Wrap(err, "resizing window failed"))
	//	}
	//	if err = w.Center(); err != nil {
	//		l.Fatal(errors.Wrap(err, "centering window failed"))
	//	}
	//}()

	// Blocking pattern
	a.Wait()
}
`

**Comment by lengnuan-v** [comment]
Unable to execute window.jQuery

**Comment by asticode** [comment]
Are you importing JQuery in your app?

**Comment by chinenual** [comment]
There's apparently a known conflict when Using jQuery in Electron apps that causes jQuery to not initialize the $ variaboe.  I had to import mine like this:

```
  <!-- jQuery/Electron "bug": https://techsparx.com/nodejs/electron/load-jquery-bootstrap.html -->
    <script src="static/js/jquery-3.4.1.slim.js"
	    type="text/javascript"
	    onload="window.$ = window.jQuery = module.exports;"></script>
```

**Comment by lengnuan-v** [comment]
> 您要在应用程序中导入JQuery吗？

Yes, I embedded a WEB background directly so that it could be used in the client side, but there was no problem in the browser. After embedding, I reported an error: window.jQuery is not a function

**Comment by lengnuan-v** [comment]
> Are you importing JQuery in your app?

Yes, I embedded a WEB background directly so that it could be used in the client side, but there was no problem in the browser. After embedding, I reported an error: window.jQuery is not a function

**Comment by asticode** [comment]
Checkout `chinenual`'s [comment](https://github.com/asticode/go-astilectron/issues/244#issuecomment-626167003)
