### ISSUE TITLE
AppIconDefaultPath

### ISSUE THREAD

**Issue by deepch** [asticode/go-astilectron#25]
Could you check whether your icon changed after removal and re download vendor

![2017-07-10 14 34 46](https://user-images.githubusercontent.com/7899955/28016423-f58883c4-657c-11e7-842b-8912609b016c.png)

code

```
package main

import (
        "flag"

        astilectron "github.com/asticode/go-astilectron"
        astilog "github.com/asticode/go-astilog"
        "github.com/pkg/errors"
)

func main() {
        // Parse flags
        flag.Parse()

        // Set up logger
        astilog.SetLogger(astilog.New(astilog.FlagConfig()))

        // Get base dir path
        var err error
        var p = "/Users/deepweb/Desktop/work/test2/src/github.com/asticode/go-astilectron/examples"

        // Create astilectron
        var a *astilectron.Astilectron
        if a, err = astilectron.New(astilectron.Options{
                AppName:            "Astilectron",
                AppIconDefaultPath: p + "/gopher.png",
                AppIconDarwinPath:  p + "/gopher.icns",
                BaseDirectoryPath:  p,
        }); err != nil {
                astilog.Fatal(errors.Wrap(err, "creating new astilectron failed"))
        }
        defer a.Close()
        a.HandleSignals()

        // Start
        if err = a.Start(); err != nil {
                astilog.Fatal(errors.Wrap(err, "starting failed"))
        }

        // Create window
        var w *astilectron.Window
        if w, err = a.NewWindow(p+"/index.html", &astilectron.WindowOptions{
                Center: astilectron.PtrBool(true),
                Height: astilectron.PtrInt(600),
                Width:  astilectron.PtrInt(600),
        }); err != nil {
                astilog.Fatal(errors.Wrap(err, "new window failed"))
        }
        if err = w.Create(); err != nil {
                astilog.Fatal(errors.Wrap(err, "creating window failed"))
        }

        // Blocking pattern
        a.Wait()
}

```

ls /Users/deepweb/Desktop/work/test2/src/github.com/asticode/go-astilectron/examples

```
bash-3.2$ ls /Users/deepweb/Desktop/work/test2/src/github.com/asticode/go-astilectron/examples
1.basic_window			3.webserver_app			5.single_binary_distribution	7.menus				gopher.icns			index.html
2.basic_window_events		4.remote_messaging		6.screens_and_displays		8.bootstrap			gopher.png			vendor
bash-3.2$ 

```

I think a few days ago there was no such problem.

**Comment by deepch** [comment]
very strange

I delete vendor and rerun 

![2017-07-10 16 09 54](https://user-images.githubusercontent.com/7899955/28019669-60a6c29e-658a-11e7-9b94-1e8a54d5dc13.png)

![2017-07-10 16 11 10](https://user-images.githubusercontent.com/7899955/28019677-6736d73e-658a-11e7-9037-416e3ed13620.png)

it no my icons ;)

**Comment by asticode** [comment]
This is the icon of your first comment.

MacOSX has an internal cache regarding icons. I don't really know how it works, but if you move your projet to another folder, somehow it will show the correct icon.

This is particularly frustrating for developers but unfortunately there's nothing we can do against this internal cache.

**Comment by asticode** [comment]
@deepch Is your problem solved?

**Comment by deepch** [comment]
At the moment I designed. I will do this in more detail later.
For the time being I have different icons for some reason.
![2017-07-16 12 50 48](https://user-images.githubusercontent.com/7899955/28246563-8ad907bc-6a25-11e7-9587-31a790541dc4.png)

3 - random icon

**Comment by asticode** [comment]
@deepch are you using an .icns icon? are you sure it's not corrupted? 

When I see this random icon, my guess is that your icon file is corrupted and therefore MacOSX displays a default icon instead...

**Comment by asticode** [comment]
@deepch is your issue resolved?
