### ISSUE TITLE
Excuse me;How to place 【electron】 in an engineering directory;Instead of putting it under C:\Users\86173\AppData\ projectName\

### ISSUE THREAD

**Issue by bluebat1** [asticode/go-astilectron#251]
Excuse me;How to place electron dependence in the engineering directory;Instead of putting it under C:\Users\86173\AppData\ projectName\

**Comment by asticode** [comment]
In [Options](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L62) you have both `BaseDirectoryPath` and `DataDirectoryPath` attributes you can play with to see if you can achieve what you want.
