### ISSUE TITLE
DevTools "Inspect" element context menu?

### ISSUE THREAD

**Issue by chinenual** [asticode/go-astilectron#252]
I suspect the answer is no - I've searched the sources and don't see a way, but I'll ask anyway...

DevTools is very helpful in debugging UI-side stuff.  But as my pages become more and more complex, it is time consuming to click through the Elements tree hierarchy every time to find the element I'm interested in inspecting.   Is there any chance there's a way to enable something like Chrome's "Inspect" context menu (which opens up dev tools to the elements tree to the element the cursor is hovering over ?

**Comment by asticode** [comment]
It seems there's [a way](https://stackoverflow.com/questions/32636750/how-to-add-a-right-click-menu-in-electron-that-has-inspect-element-option-like) to do it in plain JS in your app. However this totally short circuits the `astilectron` workflow. But I guess this is a good solution for a debugging problem.

**Comment by chinenual** [comment]
Thanks again @asticode !   I was able to make this work - tho I had to alter the require statements from the example:
```javascript
const remote = require('electron').remote;
const Menu = remote.Menu;
const MenuItem = remote.MenuItem;
```
