### ISSUE TITLE
LoadUrl Option

### ISSUE THREAD

**Issue by Oyal2** [asticode/go-astilectron#253]
Im trying to load my electron window with a current url. [Similar to this one](https://www.electronjs.org/docs/api/web-contents)

Electron supports it here `win.loadURL('http://github.com')`  but I cant seem to find a solution for this feature. Whenever I try to **WindowLoadOptions** and I call **document.URL** I just the directory of my static html file. Any feature that can achieve the loadURL that electron has?

**Comment by asticode** [comment]
When you [create a window](https://github.com/asticode/go-astilectron#create-a-window), the first arg is the url of the window
