### ISSUE TITLE
the exe file can't run (win10 64Bit)

### ISSUE THREAD

**Issue by bettersun** [asticode/go-astilectron#254]
astilectron-bundler infomation
`
E:\go\src\github.com\asticode\go-astilectron-demo>astilectron-bundler
2020/06/11 15:45:01 Bundling for environment windows/amd64
2020/06/11 15:45:01 Binding data
2020/06/11 15:45:01 Removing C:\Users\jn\AppData\Local\Temp\astibundler\bind
2020/06/11 15:45:01 Creating C:\Users\jn\AppData\Local\Temp\astibundler\bind
2020/06/11 15:45:01 Creating C:\Users\jn\AppData\Local\Temp\astibundler\bind\vendor_astilectron_bundler
2020/06/11 15:45:01 Creating C:\Users\jn\AppData\Local\Temp\astibundler\cache
2020/06/11 15:45:01 C:\Users\jn\AppData\Local\Temp\astibundler\cache\astilectron-0.39.0.zip already exists, skipping download of https://github.com/asticode/astilectron/archive/v0.39.0.zip
2020/06/11 15:45:01 Copying C:\Users\jn\AppData\Local\Temp\astibundler\cache\astilectron-0.39.0.zip to C:\Users\jn\AppData\Local\Temp\astibundler\bind\vendor_astilectron_bundler\astilectron.zip
2020/06/11 15:45:01 C:\Users\jn\AppData\Local\Temp\astibundler\cache\electron-windows-amd64-7.1.10.zip already exists, skipping download of https://github.com/electron/electron/releases/download/v7.1.10/electron-v7.1.10
-win32-x64.zip
2020/06/11 15:45:01 Copying C:\Users\jn\AppData\Local\Temp\astibundler\cache\electron-windows-amd64-7.1.10.zip to C:\Users\jn\AppData\Local\Temp\astibundler\bind\vendor_astilectron_bundler\electron.zip
2020/06/11 15:45:01 Creating C:\Users\jn\AppData\Local\Temp\astibundler\bind\resources
2020/06/11 15:45:01 Copying E:\go\src\github.com\asticode\go-astilectron-demo\resources to C:\Users\jn\AppData\Local\Temp\astibundler\bind\resources
2020/06/11 15:45:02 Generating E:\go\src\github.com\asticode\go-astilectron-demo\bind_windows_amd64.go
2020/06/11 15:45:06 Running rsrc for icon E:\go\src\github.com\asticode\go-astilectron-demo\resources\icon.ico into E:\go\src\github.com\asticode\go-astilectron-demo\windows.syso
2020/06/11 15:45:06 Removing E:\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64
2020/06/11 15:45:06 Creating E:\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64
2020/06/11 15:45:06 Building for os windows and arch amd64 astilectron: 0.39.0 electron: 7.1.10
2020/06/11 15:45:06 Executing go build -ldflags -H "windowsgui" -X "main.AppName=Astilectron demo" -X "main.BuiltAt=2020-06-11 15:45:06.3488043 +0800 CST m=+4.600696801" -X "main.VersionAstilectron=0.39.0" -X "main.Vers
ionElectron=7.1.10" -o E:\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64\binary github.com\asticode\go-astilectron-demo
2020/06/11 15:45:18 Moving E:\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64\binary to E:\go\src\github.com\asticode\go-astilectron-demo\output\windows-amd64\Astilectron demo.exe

E:\go\src\github.com\asticode\go-astilectron-demo>

`

**Comment by bettersun** [comment]
go env
`
E:\go\src\github.com\asticode\go-astilectron-demo>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jn\AppData\Local\go-build
set GOENV=C:\Users\jn\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\go\src\github.com\asticode\go-astilectron-demo\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\jn\AppData\Local\Temp\go-build047389718=/tmp/go-build -gno-record-gcc-switches

`

**Comment by bettersun** [comment]
This can run
https://github.com/asticode/go-astilectron/tree/master/example

This can't run
https://github.com/asticode/go-astilectron-demo

**Comment by asticode** [comment]
Without the logs when running the exe, it's hard to debug remotely.

Could you run the exe in a terminal, and paste the logs here ?

**Comment by bettersun** [comment]
The most difficult thing is that there is no log.
I tried to run it in terminal, but nothing was output.

go mod
```
module github.com/asticode/go-astilectron-demo

go 1.13

require (
	github.com/akavel/rsrc v0.9.0 // indirect
	github.com/asticode/go-astichartjs v0.1.0
	github.com/asticode/go-astikit v0.8.0
	github.com/asticode/go-astilectron v0.16.0
	github.com/asticode/go-astilectron-bootstrap v0.4.1
)
```

**Comment by chinenual** [comment]
The windows build does not log to stdout/stderr as do the Mac or LInux 
builds.   To get a log, I force a log to both stderr and to a file with 
a MultiWriter


    import (
         "gopkg.in/natefinch/lumberjack.v2"

    ....


         multi := io.MultiWriter(
             &lumberjack.Logger{
                 Filename:   "./mylog.log",
                 MaxSize:    5, // megabytes
                 MaxBackups: 2,
                 Compress:   false,
             },
             os.Stderr)
         log.SetOutput(multi)
         // Create logger
         l = log.New(log.Writer(), log.Prefix(), log.Flags()|log.Lshortfile)


(lumberjack rolls log files - you can substitute a simple FileWriter).  
Just be careful to do the stderr logging _last_ (multiwriter will not 
try to write to the second output if the first output fails  -- don't 
ask me how i know...)


Steve

**Comment by bettersun** [comment]
> 
> The windows build does not log to stdout/stderr as do the Mac or LInux builds.   To get a log, I force a log to both stderr and to a file with a MultiWriter ``` import (     "gopkg.in/natefinch/lumberjack.v2" ....     multi := io.MultiWriter(         &lumberjack.Logger{             Filename:   "./mylog.log",             MaxSize:    5, // megabytes             MaxBackups: 2,             Compress:   false,         },         os.Stderr)     log.SetOutput(multi)     // Create logger     l = log.New(log.Writer(), log.Prefix(), log.Flags()|log.Lshortfile) ``` (lumberjack rolls log files - you can substitute a simple FileWriter).  Just be careful to do the stderr logging _last_ (multiwriter will not try to write to the second output if the first output fails  -- don't ask me how i know...)

Thank you, I have a try

**Comment by bettersun** [comment]
It seems that the main() method was not executed.
The source down print nothing in the terminal.

```
func main() {
	fmt.Printf("main start")
```

**Comment by asticode** [comment]
This reminds me of an issue I had a while ago, which was the antivirus blocking the execution of the app. Could you try disabling your antivirus temporarily and see if the exe opens ?

**Comment by bettersun** [comment]
I haven`t resolve the prolem.
I just want to close this issue.
