### ISSUE TITLE
run in dev

### ISSUE THREAD

**Issue by masterdubs** [asticode/go-astilectron#259]
How do you run the javascript in dev and the app at the same time  without the need to build the js and then astilectron-bundler bd ?

**Comment by asticode** [comment]
If your dev js is available on a local server (like `vuejs` does for instance), you can use the [Homepage](https://github.com/asticode/go-astilectron-bootstrap/blob/master/options.go#L32) attribute to point to the local server. Otherwise unfortunately there's no way around building your js and binding data using `astilectron-bundler`.

**Comment by masterdubs** [comment]
Cool will try that thank you. What's the best way to include astilectron in vue ?

**Comment by asticode** [comment]
In dev I would do as suggested before, and in prod I would build files into the `app` folder and use the bundler to bind files. I don't think there are many more things you can do.

**Comment by masterdubs** [comment]
Thanks. Last one sorry I'm new to astilectron, switching from another framework. How do you insert the astilectron in the J's, tried the send message but of course it doesn't find the first part 'astilectron'.

**Comment by asticode** [comment]
`astilectron` will get inserted automatically, you just need to wait for it by listening to `astilectron-ready` event:

```js
// This will wait for the astilectron namespace to be ready
document.addEventListener('astilectron-ready', function() {
    // Use astilectron. methods
})
```

**Comment by masterdubs** [comment]
I tried that, but I'm unable to build my vuejs for production as it fail with "  ```
error  'astilectron' is not defined  no-undef
"
```

it looks like that: 
`document.addEventListener('astilectron-ready', function () {
              astilectron.onMessage((message) => {
                if (message["name"] === "nodeblock") {
                  this.block = message["payload"]["block_number"]
                  console.log(message)
                }
              })
            }
    );`

**Comment by masterdubs** [comment]
weird, solved with a reboot

**Comment by masterdubs** [comment]
Build is solved with a reboot, strange. I still unable when I use the 
`astilectron.sendMessage
`

**Comment by masterdubs** [comment]
solved, I added --no-cache to npm command. Thank you for the help really appreciate.
