### ISSUE TITLE
template rendering issue

### ISSUE THREAD

**Issue by jpastorm** [asticode/go-astilectron#260]
### Example main.go
**line 35**

if w, err = a.NewWindow("public/index.html", &astilectron.WindowOptions{

**Solve:**
if w, err = a.NewWindow("index.html", &astilectron.WindowOptions{

**Comment by asticode** [comment]
As the doc states, you need to run `go run example/main.go -v` to run the example, therefore you need to be in the project root directory. My guess is that you tried to run the example while being in the example folder.

**Comment by jpastorm** [comment]
:O  yes I do that, my Fault. I will try with a react proyect
