### ISSUE TITLE
electron-windows-amd64\electron.exe' exited with code: 3221225477

### ISSUE THREAD

**Issue by w01fb0ss** [asticode/go-astilectron#263]
![image](https://user-images.githubusercontent.com/44709004/88771630-18485980-d1b2-11ea-8bd7-3eb005eb0e43.png)

**Comment by asticode** [comment]
Can you try running the demo and see if you're having the same issue ?

**Comment by w01fb0ss** [comment]
> Can you try running the demo and see if you're having the same issue ?

The program crashes occasionally, not every time

**Comment by asticode** [comment]
Which OS (including the version) are you running the demo on ?

**Comment by w01fb0ss** [comment]
> Which OS (including the version) are you running the demo on ?

windows 10 
os version 1809

**Comment by asticode** [comment]
Can you try updating [this value](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L17) to `7.3.3` and try again ?

**Comment by w01fb0ss** [comment]
> Can you try updating [this value](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L17) to `7.3.3` and try again ?


I have updated [this value](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L17) to `9.1.2`，the program runs normally, thank you! I will run for a while to see if the crash happens again
