### ISSUE TITLE
How to globally set link to be explored in default browser ?

### ISSUE THREAD

**Issue by afeduohz** [asticode/go-astilectron#264]
I edited index.html like,

...
&lt;a href="https://google.com"&gt;google&lt;/a&gt;
...

Click this anchor, my window will redirect/navigate to google. :( Indeed, I want to open google in default browser in my OS

**Comment by asticode** [comment]
In a `<script>` tag, you should add 

```javascript
const { remote } = require('electron')
``` 

to import the `remote` module.

Then create the following JS function

```javascript
openExternalBrowser(url) {
  remote.shell.openExternal(url)
}
```

And make sure this function is called whenever your user clicks the link.

**Comment by afeduohz** [comment]
Thanks @asticode . It works well this way. 
Additionally, I am looking for the solution that I can inject/bind the function to handle the link click or other events.
for example,
w.On('xxx-click', func (e Event) {
  //actions beyond defaults.
  xxx
  xxx 
})
-------
Why I need this ?
I want to load custom html files that contents are not controlled by myself.
@asticode  can we support this way ?

**Comment by asticode** [comment]
Would this work ?

```html
<a onclick="openExternalBrowser">Test</a>
```

```javascript
const { remote } = require('electron')

openExternalBrowser(e) {
  remote.shell.openExternal(e.target.href)
}
```
