### ISSUE TITLE
How to update the Electron Version

### ISSUE THREAD

**Issue by komyg** [asticode/go-astilectron#265]
Hi @asticode ,

I noticed the that the Electron version that we are using is 7.1.0 and that the latest is the 9.1.2. I believe that this is causing some issues in my app, because the version 7.1.0 uses an older version of Chromium (in my tests, everything works fine in a regular browser, but does not work well in Electron).

How can I upgrade the Go-Astilectron or the Astilectron packages to use Electron 9 or the latest version of Electron 7?

Note: I would be happy to open a PR back to this project if you want.

Thanks,
Felipe

**Comment by chinenual** [comment]
You can set the electron version in bundler.json - i've been running 
with 8.2.5 with no problems.

{
    "app_name": "My App",
     "version_electron" : "8.2.5",
...

**Comment by komyg** [comment]
Hi,

That worked for me! 

Thanks for the help!
Felipe
