### ISSUE TITLE
How to exit gracefully

### ISSUE THREAD

**Issue by w01fb0ss** [asticode/go-astilectron#268]
The program sometimes displays javascript errors, like the following. 
![image](https://user-images.githubusercontent.com/44709004/90466463-711d6900-e144-11ea-930b-26da41a9e859.png)

How can I exit gracefully without crashing?

**Comment by asticode** [comment]
Do you have a short code sample to reproduce your error so that I can point you in the best direction ?

Indeed, depending on the way you use the lib, there are different ways to exit gracefully.

**Comment by w01fb0ss** [comment]
I can't reproduce the error. I want the program displays javascript errors by dialog, but only in the console.

**Comment by syntaxgame** [comment]
I suppose you are trying to send close message from Javascript to Go, as I did. In order to prevent this error, call Close function for your main window in your message handling function. Function signature is below:

// Close closes the window
func (w *Window) Close() (err error)
