### ISSUE TITLE
How to configure SeverityLogger?

### ISSUE THREAD

**Issue by chinenual** [asticode/go-astilectron#273]
I'd like to reduce the verbosity of the log to omit things line window.move.event and other events that might be useful for debugging, but not in production.   My reading of the sources is that Debugf, ErrorF, Infof are all just hardcoded to unconditionally emit whenever they are called.   I expected to be able to find a configuration option somewhere similar to log4j to set the log severity (to filter out Debug events, for example).  Instead I suspect I need to create a custom type that does that? 

Can you point me to a code snippet where this sort of configuration is done?  Or confirm that I need to create my own logger? 

Thanks!

**Comment by chinenual** [comment]
I just discovered the go-astilog project which appears to address most of my questions.  My app was based on the -demo project which doesn't use astilog, so defaults to a very verbose log.

**Comment by asticode** [comment]
Great !

You can also use a custom logger since you can provide one [here](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L83). It just needs to implement the [proper interfaces](https://github.com/asticode/go-astikit/blob/master/logger.go#L8)
