### ISSUE TITLE
Something went wrong.

### ISSUE THREAD

**Issue by SwankyTigerYY** [asticode/go-astilectron#275]
error:Something went wrong.url:https://demo.cloudreve.org/#/login

**Comment by asticode** [comment]
I need more information to be able to help you: logs, screenshots, ...

**Comment by SwankyTigerYY** [comment]
I used example, I just changed the URL.
username:123@mail.com
password:123123123

```
package main
import (
	"fmt"
	"log"

	"github.com/asticode/go-astikit"
	"github.com/asticode/go-astilectron"
)

func main() {
	// Set logger
	l := log.New(log.Writer(), log.Prefix(), log.Flags())

	// Create astilectron
	a, err := astilectron.New(l, astilectron.Options{
		AppName:           "Test",
		BaseDirectoryPath: "example",
	})
	if err != nil {
		l.Fatal(fmt.Errorf("main: creating astilectron failed: %w", err))
	}
	defer a.Close()

	// Handle signals
	a.HandleSignals()

	// Start
	if err = a.Start(); err != nil {
		l.Fatal(fmt.Errorf("main: starting astilectron failed: %w", err))
	}

	// New window
	var w *astilectron.Window
	if w, err = a.NewWindow("https://demo.cloudreve.org/#/login", &astilectron.WindowOptions{
		Center: astikit.BoolPtr(true),
		Height: astikit.IntPtr(700),
		Width:  astikit.IntPtr(700),
	}); err != nil {
		l.Fatal(fmt.Errorf("main: new window failed: %w", err))
	}

	// Create windows
	if err = w.Create(); err != nil {
		l.Fatal(fmt.Errorf("main: creating window failed: %w", err))
	}

	// Blocking pattern
	a.Wait()
}
```

**Comment by SwankyTigerYY** [comment]
![1600846475(1)](https://user-images.githubusercontent.com/24326903/93981381-7ceaf380-fdb2-11ea-9caf-d0949e752615.jpg)
![1600846485(1)](https://user-images.githubusercontent.com/24326903/93981402-82483e00-fdb2-11ea-8535-678c14a34234.jpg)

**Comment by asticode** [comment]
It seems like this error is not linked to `astilectron` but to the website you're calling.

You can use [dev tools](https://github.com/asticode/go-astilectron#open-the-dev-tools) to know more about the error, but there's nothing more I can do from an `astilectron` standpoint.

**Comment by SwankyTigerYY** [comment]
Thank you for your reply
