### ISSUE TITLE
How to open external url in default browser?

### ISSUE THREAD

**Issue by lijinsummer** [asticode/go-astilectron#276]
I want to open a URL in my default browser. Electron's shell module provide function to support it(shell.openExternal('https://github.com')), but I cannot find similar function in astilectron. Please help me solve it. Thanks.

And I have another question. Can I change the windowOptions after new window? For example when I new window with option frame = false, then resize the window and set the option frame = true.

**Comment by asticode** [comment]
> I want to open a URL in my default browser. Electron's shell module provide function to support it(shell.openExternal('https://github.com')), but I cannot find similar function in astilectron. Please help me solve it. Thanks.

A quick Google search gave me [this](https://gist.github.com/hyg/9c4afcd91fe24316cbf0). However I don't know what's your exact use case.

> And I have another question. Can I change the windowOptions after new window? For example when I new window with option frame = false, then resize the window and set the option frame = true.

You can resize the window but won't be able to change options manually.

**Comment by lijinsummer** [comment]
Thanks for your prompt reply :)  My use case is : there are some links in my app, when click these links I hope the url will be accessed through browser, instead of new another window in app.

**Comment by asticode** [comment]
NodeJS is enabled in your JS code. Therefore you can do `require("shell").openExternal("http://www.google.com")` in your JS.
