### ISSUE TITLE
Remove menu area?

### ISSUE THREAD

**Issue by hkdb** [asticode/go-astilectron#278]
Is there a proper go-astilectron bootstrap options way to remove the menu area all together? I don't plan on having any menus at all in my app.

Thanks!

**Comment by asticode** [comment]
Normally, the default menu is removed. What do you mean by `menu area` ?

**Comment by hkdb** [comment]
![Screenshot from 2020-09-28 16-17-46](https://user-images.githubusercontent.com/38838639/94407832-90c59980-01a6-11eb-87d1-920a2d2992e5.png)

Here's my code for the bootstrap part:
```
	// Run bootstrap
	l.Printf("Running app built at %s\n", BuiltAt)
	if err := bootstrap.Run(bootstrap.Options{
		Asset:    Asset,
		AssetDir: AssetDir,
		AstilectronOptions: astilectron.Options{
			AppName:            "Super App",
			AppIconDarwinPath:  "resources/icon.icns",
			AppIconDefaultPath: "resources/logo.png",
			SingleInstance:     true,
		},
		Debug:         true, //*debug,
		Logger:        l,
		RestoreAssets: RestoreAssets,
		Windows: []*bootstrap.Window{{
			Homepage:       "index.html",
			MessageHandler: handleMessages,
			Options: &astilectron.WindowOptions{
				BackgroundColor: astikit.StrPtr("#333"),
				Center:          astikit.BoolPtr(true),
				Height:          astikit.IntPtr(windowHeight),
				Width:           astikit.IntPtr(windowWidth),
			},
		}},
	}); err != nil {
		l.Fatal(fmt.Errorf("running bootstrap failed: %w", err))
	}
```
I didn't specify a menu at all and I am getting the blank menu area as per the screenshot above the code snippet.

Thanks!

**Comment by asticode** [comment]
Are you testing on MacOSX ? If so, which version are you using ?

**Comment by hkdb** [comment]
I am on Pop! OS 20.04 but the final product is targeted to run on Windows, MacOS, and Linux. Thanks!

**Comment by asticode** [comment]
Setting `Debug` to `true` creates a menu. Could you try with `Debug` set to `false` ?

**Comment by hkdb** [comment]
Ahhhh I see! menu area is gone as soon as I set the debug to false. Thank you!

**Comment by asticode** [comment]
Cheers

**Comment by hkdb** [comment]
Sorry to keep pestering you about this and I really appreciate your help but I just noticed that while in Linux, I am able to paste just fine, in MacOS, it doesn't work. So I found this:

https://github.com/asticode/go-astilectron/issues/68

But doesn't that mean that I have to build a menu item and have a menu just so I can have copy and paste?

Thanks!

**Comment by asticode** [comment]
Unfortunately yes, you need to set menu items with proper shortcuts in order to copy/paste

**Comment by hkdb** [comment]
Looks like as long as I set a empty label on the menu item, the bar doesn't show up in mac. So I guess my solution for now is to have the build script comment out that menu item block for the Linux build and un-comment the block for the Mac build. A dirty hack but will certainly accomplish what I need. Off to Windows testing!

Thanks again for your help!
