### ISSUE TITLE
Store electron and astilectron according OS and arch

### ISSUE THREAD

**Issue by lunny** [asticode/go-astilectron#28]
Since some developers using Windows and others MacOS and we would like to keep the binary on the git. It's so difficult to cooperate between us. Why not store electron and astilectron according OS and arch?

**Comment by asticode** [comment]
I agree with you, adding the TODO

**Comment by asticode** [comment]
in fact the TODO was already there : https://github.com/asticode/go-astilectron/blob/master/paths.go#L51 :D

if anyone is interested in contributing, I'd be happy to review a PR

**Comment by lunny** [comment]
@asticode I will try that.
