### ISSUE TITLE
Notification Icon Path

### ISSUE THREAD

**Issue by Joe-Improbable** [asticode/go-astilectron#280]
I'm using Astilectron's notification API to send a notification to the user. However, I'm confused about the `Icon` field. Is the path provided here meant to be relative to the `resources` folder similar to `Astilectrons.Options` `AppIconDefaultPath` or is it relative to something else. 

Example code, which reuses the same icon path as `AppIconDefaultPath`, which works, but it does not for notification icons:
```
var notification = asti.NewNotification(&astilectron.NotificationOptions{
		Body:     message,
		HasReply: astikit.BoolPtr(false),
		Icon:     "resources/app/icons/64x64.png",
		Title:    title,
	})
```

**Comment by asticode** [comment]
I think path to notification and tray icons need to be absolute. Check out [this logic](https://github.com/asticode/go-astilectron-bootstrap/blob/master/run.go#L155) for that.
