### ISSUE TITLE
Weird behavior with Go only in MacOS

### ISSUE THREAD

**Issue by hkdb** [asticode/go-astilectron#283]
Hi again... So I wrote everything in something else before I switched to go-astilectron which required me to deal with all the dialogs and notifications with Go so I decided to use "github.com/sqweek/dialog" for that purpose and it worked really well for all 3 platforms until I ported it over to go-astilectron. Since I was porting over the app rather than starting from scratch, instead of using Electron dialogs, I just make calls from JS to Go and have it execute a function which includes code that calls dialogs to interact with the user; mainly choosing files and also notifying users of errors or telling them that things are completed.

This works pretty well in Linux and it works fine in Windows as well but for some reason, anything to do with that in MacOS just does nothing.

if I run the compiled binary inside the .app directly rather than running the .app, I see all the output which shows that Go got the call and does the fmt.Println line right before the function and then nothing happens.

Any ideas what might be causing this?

Thanks!

**Comment by asticode** [comment]
Unfortunately nothing comes to mind. I think your best bet is either dropping `go-astilectron` or `github.com/sqweek/dialog` and use only one of them at the same time

**Comment by hkdb** [comment]
Argh.... ok... Thanks! Guess I will have to deal... Off to rewriting all my dialog and notification logic... :/ Do you have any advice in terms of being able to invoke popup dialogs directly from Go or should I always depend on returning payload to invoke popup dialogs in JS? Thanks!

**Comment by hkdb** [comment]
Nevermind... brain is not working properly today... Guess I can also setup a listener on JS and invoke popups that well. Thanks!
