### ISSUE TITLE
Single instance lock API

### ISSUE THREAD

**Issue by NickTikhonov** [asticode/go-astilectron#284]
Hey again!

I'm wondering whether it's possible currently to determine whether the process has a single instance lock? 
My use case is opening the app via a file protocol handler - in which case, I want the existing window to receive the context of the second invocation. This is done by electron via `app.requestSingleInstanceLock()`: https://www.electronjs.org/docs/api/app#apprequestsingleinstancelock 

Thanks again!

**Comment by asticode** [comment]
This API is [implemented](https://github.com/asticode/astilectron/blob/master/main.js#L13) in `astilectron` and you should be able to use it with the [SingleInstance](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L70) option.

**Comment by NickTikhonov** [comment]
Hey @asticode - we're currently using the `SingleInstance` option to prevent multiple instances of the app from being created, and it's working great. However, this option doesn't seem to be giving any feedback of the second invocation to the first. For example, using the above electron API I am able to receive the arguments of the second invocation in the first intance:

```
  app.on('second-instance', (event, commandLine, workingDirectory) => {
     ...here I'm able to do something with the command line arguments from the second invocation...
  })
```

Would it be possible to achieve a similar API with astilectron?

**Comment by asticode** [comment]
This is indeed doable. I won't have time to work on this though, but I'm welcoming PRs. Here's a more detailed description of what to do:

1) In JS, send an event to GO [here](https://github.com/asticode/astilectron/blob/master/main.js#L23) using the same logic as [this](https://github.com/asticode/astilectron/blob/master/index.js#L34) for example. Name the event `app.event.second.instance` and the body should be `{"secondInstance":{"commandLine": commandLine, "workingDirectory": workingDirectory}`
2) In GO add the event name [here](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L31) and the event body [here](https://github.com/asticode/go-astilectron/blob/master/event.go#L15) (something like 
```go
type EventSecondInstance {
  CommandLine []string `json:"commandLine"`
  WorkingDirectory string `json:"workingDirectory"`
}
```

Once done, you should be able to capture the event in GO using

```go
a.On(EventNameAppEventSecondInstance, func(e Event) bool {
  // TODO Do something with the body
  log.Println(e.SecondInstance)
})
```
