### ISSUE TITLE
Failed to debug with vscode

### ISSUE THREAD

**Issue by eclipseAce** [asticode/go-astilectron#285]
`go run main.go bind_windows_amd64.go -v` works well, but failed to debug with Ctrl+F11
DEBUG CONSOLE shows:

API server listening at: 127.0.0.1:19208
2020-10-15T16:12:57+08:00 info layer=debugger launching process with args: [d:\git\go-astilectron-demo\__debug_bin]
2020-10-15T16:12:58+08:00 warning layer=debugger could not set asyncpreemptoff <nil>
2020-10-15T16:12:58+08:00 debug layer=debugger continuing
2020/10/15 16:12:58 Running app built at
2020/10/15 16:12:58 astikit: starting worker...
2020/10/15 16:12:58 Skipping restoring resources...
2020/10/15 16:12:58 Starting...
2020/10/15 16:12:58 Provisioning...
2020/10/15 16:12:58 Astilectron has already been provisioned to version 0.41.0, moving on...
2020/10/15 16:12:58 Electron has already been provisioned to version 7.1.10, moving on...
2020/10/15 16:12:58 Listening...
2020/10/15 16:12:58 Executing...
2020/10/15 16:12:58 Starting cmd E:\Administrator\AppData\Roaming\vendor\electron-windows-amd64\electron.exe E:\Administrator\AppData\Roaming\vendor\astilectron\main.js 127.0.0.1:58079 true
2020/10/15 16:12:58 Stderr says: internal/modules/cjs/loader.js:720
2020/10/15 16:12:58 Stderr says:     throw err;
2020/10/15 16:12:58 Stderr says:     ^
2020/10/15 16:12:58 Stderr says: 
2020/10/15 16:12:58 Stderr says: Error: Cannot find module 'electron'
2020/10/15 16:12:58 Stderr says: Require stack:
2020/10/15 16:12:58 Stderr says: - E:\Administrator\AppData\Roaming\vendor\astilectron\main.js
2020/10/15 16:12:58 Stderr says:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
2020/10/15 16:12:58 Stderr says:     at Module._load (internal/modules/cjs/loader.js:622:27)
2020/10/15 16:12:58 Stderr says:     at Module._load (electron/js2c/asar.js:717:26)
2020/10/15 16:12:58 Stderr says:     at Function.Module._load (electron/js2c/asar.js:717:26)
2020/10/15 16:12:58 Stderr says:     at Module.require (internal/modules/cjs/loader.js:775:19)
2020/10/15 16:12:58 Stderr says:     at require (internal/modules/cjs/helpers.js:68:18)
2020/10/15 16:12:58 Stderr says:     at Object.<anonymous> (E:\Administrator\AppData\Roaming\vendor\astilectron\main.js:3:17)
2020/10/15 16:12:58 Stderr says:     at Module._compile (internal/modules/cjs/loader.js:880:30)
2020/10/15 16:12:58 Stderr says:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
2020/10/15 16:12:58 Stderr says:     at Module.load (internal/modules/cjs/loader.js:735:32) {
2020/10/15 16:12:58 Stderr says:   code: 'MODULE_NOT_FOUND',
2020/10/15 16:12:58 Stderr says:   requireStack: [
2020/10/15 16:12:58 Stderr says:     'E:\\Administrator\\AppData\\Roaming\\vendor\\astilectron\\main.js'
2020/10/15 16:12:58 Stderr says:   ]
2020/10/15 16:12:58 Stderr says: }
2020/10/15 16:12:58 'E:\Administrator\AppData\Roaming\vendor\electron-windows-amd64\electron.exe' exited with code: 1
2020/10/15 16:12:58 App has crashed
2020/10/15 16:12:58 Stopping...
2020/10/15 16:12:58 astikit: stopping worker...
2020/10/15 16:12:58 Closing...
2020/10/15 16:12:58 accept tcp 127.0.0.1:58079: use of closed network connection while TCP accepting
2020/10/15 16:12:58 Stopping...
2020/10/15 16:12:58 running bootstrap failed: creating window failed: context canceled
2020-10-15T16:12:59+08:00 debug layer=debugger halting
Process exiting with code: 0

Please help

**Comment by asticode** [comment]
What do you mean by `debug with Ctrl+F11` ?

**Comment by eclipseAce** [comment]
![image](https://user-images.githubusercontent.com/11436358/96202288-65f28800-0f91-11eb-93bb-791d60553ffc.png)
shortcut key for debugging

**Comment by asticode** [comment]
do you know what command is run by the debugging process ?

**Comment by eclipseAce** [comment]
`dlv debug --headless=true --listen=127.0.0.1:29097 --api-version=2` 
I found it in task manager, but sorry I don't know the details of VSCode's debugging process

**Comment by eclipseAce** [comment]
![image](https://user-images.githubusercontent.com/11436358/96246447-3bc5b800-0fdb-11eb-8a47-5b7baf703dda.png)

I found electron cmd runs without workdir, is that the reason why electron fails?

**Comment by asticode** [comment]
Mmmm I don't know but check out answers at the bottom of this [this issue](https://github.com/asticode/go-astilectron/issues/170), this may fix your problem

**Comment by eclipseAce** [comment]
It's now resolved by add `os.Unsetenv("ELECTRON_RUN_AS_NODE")`  according to #170, thanks a lot

**Comment by eclipseAce** [comment]
I found the distribution exe crashed when environment variable ELECTRON_RUN_AS_NODE exists
`set ELECTRON_RUN_AS_NODE=true`
`start output\windows-amd64\Astilectron demo.exe`
It's interesting
