### ISSUE TITLE
Text Input?

### ISSUE THREAD

**Issue by micahlhoover** [asticode/go-astilectron#288]
I'm sure there is probably a way to take user input, but I didn't see anything about it in the examples.

I'm thinking about something analogous to <input type="text"> or a text edit or something like that. A text area option would be cool too.

Apologies if there is already something like this and I missed it.

**Comment by asticode** [comment]
@micahlhoover the simplest solution would be to do that interaction in JS and send the value to GO if need be. You can use a `<input type="text"/>` and then use [these tricks](https://github.com/asticode/go-astilectron#send-messages-from-javascript-to-go)
