### ISSUE TITLE
Native File Explorer

### ISSUE THREAD

**Issue by radding** [asticode/go-astilectron#293]
Is there the ability to open the native file explorer similar to this method:

```javascript
const { dialog } = require('electron')
console.log(dialog.showOpenDialog({ properties: ['openFile', 'multiSelections'] }))
```

https://www.electronjs.org/docs/api/dialog

**Comment by asticode** [comment]
NodeJS integration is always enabled therefore you have access to `electron` in your JS.

Your code should work fine.

**Comment by radding** [comment]
Ahh you're right. This method requires you to use `remote` in the JS, which is why I initially missed it! Thanks.
