### ISSUE TITLE
How to retrieve load page cookies?

### ISSUE THREAD

**Issue by cxfksword** [asticode/go-astilectron#295]
I create a new window with web page url. ex:

```
var w, _ = a.NewWindow("https://test.com/login", &astilectron.WindowOptions{
	Center: astikit.BoolPtr(true),
	Height: astikit.IntPtr(360),
	Width:  astikit.IntPtr(420),		
})
```
When page loaded, how to retrieve all page cookies (include HttpOnly cookie)?

**Comment by asticode** [comment]
You will be able to retrieve page cookies only in your JS using these [APIs](https://github.com/electron/electron/blob/v7.1.10/docs/api/cookies.md).

Use something like this to retrieve the `session` object :

```javascript
const session = require('electron').remote.session
```

**Comment by cxfksword** [comment]
Thanks your reply.

I have retrieved cookies in preload using JS, when i want to send  cookies to go by ```astilectron.sendMessage```, ```astilectron``` is undefined, why?

**Comment by asticode** [comment]
Make sure you're executing `astilectron.sendMessage` once you've received `astilectron-ready` event:

```javascript
// This will wait for the astilectron namespace to be ready
document.addEventListener('astilectron-ready', function() {
    // This will send a message to GO
    astilectron.sendMessage("hello", function(message) {
        console.log("received " + message)
    });
})
```

**Comment by cxfksword** [comment]
Thanks, I has succeeded. But this way can't retrieve ```HttpOnly``` cookie. 😂
