### ISSUE TITLE
Question. How can I call window.close() from a javascript function?

### ISSUE THREAD

**Issue by LuisFlahan4051** [asticode/go-astilectron#296]
I have tried using messages, but  I can't find where astilectron is defined or imported to use it.

**Comment by asticode** [comment]
`astilectron` is automatically available in your JS if you wrap your calls in:

```javascript
document.addEventListener('astilectron-ready', function() {
  // Your logic
})
```

Checkout the doc on how to [receive](https://github.com/asticode/go-astilectron#javascript) or [send](https://github.com/asticode/go-astilectron#javascript-1) messages.

**Comment by LuisFlahan4051** [comment]
Thanks, I have already solved the problem.
