### ISSUE TITLE
Bad electron architecture selected form arm in raspberry pi

### ISSUE THREAD

**Issue by iXo** [asticode/go-astilectron#30]
Hello,

in the file paths.go, the arch is hard coded on x64 for linux, but when running on raspberry pi (2 in my case) the valid arch must be armv7l.

Best regards.

**Comment by asticode** [comment]
What does `runtime.GOARCH` contains in that case?

**Comment by iXo** [comment]
go env, gives me GOARCH as "arm"

uname -a for infos : 
Linux raspberrypi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux

**Comment by asticode** [comment]
Could you tell me what does `go env` fully output?

Electron has either `arm` and `armv7l`, and the Golang wiki says there is a GOARM environment variable but I want to make sure in your case.

**Comment by asticode** [comment]
And if you don't see a `GOARM` line in `go env`, can you tell me if you have a `GOARM` environment variable anyway?

**Comment by iXo** [comment]
Here is what go env gives me :

`GOARCH="arm"
GOBIN="/home/pi/Documents/gopath/bin"
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/Documents/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM=""
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build582105204=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"`

uname -a
Linux raspberrypi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie) 
Release:	8.0
Codename:	jessie

Go installed from this how to : https://gist.github.com/konradko/a9468beb70f0fa47766f5ebf966f24e8   go1.8.3.linux-armv6l.tar.gz

**Comment by asticode** [comment]
@iXo I've pushed an `arm` branch, could you tell me if that fixes your problem?

**Comment by asticode** [comment]
@iXo did you have time to test it?

**Comment by iXo** [comment]
Sorry @asticode for the delay, the rpi wasn't availble, your modification(s) in the arm branch are valid, here is the cli log proving it :

> pi@raspberrypi:~/Documents/gopath/src/test $ cd ../github.com/asticode/go-astilectron/
> pi@raspberrypi:~/Documents/gopath/src/github.com/asticode/go-astilectron $ git status
> Sur la branche master
> Votre branche est à jour avec 'origin/master'.
> rien à valider, la copie de travail est propre
> pi@raspberrypi:~/Documents/gopath/src/github.com/asticode/go-astilectron $ git branch -a
> * master
>   remotes/origin/HEAD -> origin/master
>   remotes/origin/arm
>   remotes/origin/master
>   remotes/origin/splash
> pi@raspberrypi:~/Documents/gopath/src/github.com/asticode/go-astilectron $ git checkout arm
> La branche arm est paramêtrée pour suivre la branche distante arm depuis origin.
> Basculement sur la nouvelle branche 'arm'
> pi@raspberrypi:~/Documents/gopath/src/github.com/asticode/go-astilectron $ git branch -a
> * arm
>   master
>   remotes/origin/HEAD -> origin/master
>   remotes/origin/arm
>   remotes/origin/master
>   remotes/origin/splash
> pi@raspberrypi:~/Documents/gopath/src/github.com/asticode/go-astilectron $ cd ..
> pi@raspberrypi:~/Documents/gopath/src/github.com/asticode $ cd ..
> pi@raspberrypi:~/Documents/gopath/src/github.com $ cd ..
> pi@raspberrypi:~/Documents/gopath/src $ cd test/
> pi@raspberrypi:~/Documents/gopath/src/test $ ls
> test.go
> pi@raspberrypi:~/Documents/gopath/src/test $ go build
> pi@raspberrypi:~/Documents/gopath/src/test $ ./test -v
> DEBU[0000] Starting...                                  
> DEBU[0000] Provisioning...                              
> DEBU[0000] Astilectron has already been provisioned to version 0.6.0, moving on... 
> DEBU[0000] Provisioning Electron...                     
> DEBU[0000] Removing directory /home/pi/Documents/gopath/src/github.com/asticode/go-astilectron/examples/vendor/electron 
> DEBU[0000] Downloading https://github.com/electron/electron/releases/download/v1.6.5/electron-v1.6.5-linux-arm.zip into /home/pi/Documents/gopath/src/github.com/asticode/go-astilectron/examples/vendor/electron-v1.6.5.zip 
> DEBU[0058] Creating directory /home/pi/Documents/gopath/src/github.com/asticode/go-astilectron/examples/vendor/electron 
> DEBU[0058] Unzipping /home/pi/Documents/gopath/src/github.com/asticode/go-astilectron/examples/vendor/electron-v1.6.5.zip into /home/pi/Documents/gopath/src/github.com/asticode/go-astilectron/examples/vendor/electron 
> DEBU[0073] System doesn't require finshing provisioning electron, moving on... 
> DEBU[0073] Listening...                                 
> DEBU[0073] Executing...                                 
> DEBU[0073] Starting cmd /home/pi/Documents/gopath/src/github.com/asticode/go-astilectron/examples/vendor/electron/electron /home/pi/Documents/gopath/src/github.com/asticode/go-astilectron/examples/vendor/astilectron/main.js 127.0.0.1:42844

Thanks for all.

**Comment by asticode** [comment]
Perfect! I've merged this branch in `master`.

Thanks for testing on an ARM arch :)
