### ISSUE TITLE
Tray click event

### ISSUE THREAD

**Issue by shayne** [asticode/go-astilectron#31]
Just started working with go-astilectron and ran into a case where I wanted to click/double-click the tray icon (win platform). Doesn't look like those events are sent up to go-land.

**Comment by asticode** [comment]
@shayne you're right, I'll add it to the TODOs

**Comment by shayne** [comment]
If you want to point me in the right general direction I can see about sending a PR.

**Comment by asticode** [comment]
Sounds good. Here's what has to be done:

- first off, you'll have to modify https://github.com/asticode/astilectron. Check out Electron's doc for Tray: https://github.com/electron/electron/blob/v1.6.5/docs/api/tray.md#event-click and see all the available events. You'll have to add them in the list at https://github.com/asticode/astilectron/blob/master/src/consts.js#L31. Constants would be named something like `trayEventBalloonClicked` and events would be named something like `tray.event.balloon.clicked`.

- then you gotta listen to those electron's events when creating a tray with JS. Check out `windowCreate` (https://github.com/asticode/astilectron/blob/master/main.js#L227) and create a `trayCreate` function that includes the logic at https://github.com/asticode/astilectron/blob/master/main.js#L106 and add all the `.on()` functions that are needed for each and every events.

- when you're done modifying `astilectron`, you can submit a PR there. Once merged you'll have to create a tag for this new version that we'll use in `go-astilectron`.

- now off to `go-astilectron`: all you have to do is add event names as constants in https://github.com/asticode/go-astilectron/blob/master/tray.go#L7. Then you'll be able to catch them using the `On` method that `Tray` "inherit" from the `object` struct.

- ho and also bump the `astilectron` version used once you'll have created the proper tag. During development, if you want `go-astilectron` to use a specific `astilectron` path you can use the go flag `astilectron-directory-path`. That way you don't have to develop in the vendor directory.

As you can see most modifications have to be done on the javascript side, if that raises any issue let me know, I'll have some time to work on this enhancement in the coming week.

Let me know if you have any questions, I have the feeling I haven't been really articulate.

Cheers.

**Comment by asticode** [comment]
@shayne I've added the basic tray click events starting with https://github.com/asticode/go-astilectron/blob/master/tray.go#L9

Does this fix your issue?

**Comment by shayne** [comment]
Yeah this should work. I ended up moving to a platform-native implementation in the mean time (for other reasons). But will give astilectron another look!
