### ISSUE TITLE
how to injection js and css using golang?

### ISSUE THREAD

**Issue by jilieryuyi** [asticode/go-astilectron#310]
how to injection js and css using golang?

**Comment by asticode** [comment]
I don't really understand what you're trying to achieve.

Take a look at the [demo](https://github.com/asticode/go-astilectron-demo) and the way it uses both [js and css](https://github.com/asticode/go-astilectron-demo/tree/master/resources/app/static)

**Comment by jilieryuyi** [comment]
I found this: elements[json.targetID].webContents.executeJavaScript, thank you!!
