### ISSUE TITLE
Electron 12 and context isolation

### ISSUE THREAD

**Issue by paolobelluticm** [asticode/go-astilectron#318]
# Problem

Apparent incompatibility by-default with Electron 12.

# Context

Trying out Electron 12.0.5, to keep up with the times. For reference, `astilectron.DefaultVersionElectron` is currently `11.1.0`.

# Symptoms

The following error appears in the log upon window creation:

```
Astilectron says: {"name":"window.event.did.finish.load","targetID":"1"}
Sending to Astilectron: {"name":"window.cmd.web.contents.open.dev.tools","targetID":"1"}
astikit: worker is now waiting...
Stderr says: (node:22204) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
Stderr says:     at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/renderer_init.js:89:1563)
Stderr says:     at electron/js2c/renderer_init.js:117:435
Stderr says:     at electron/js2c/renderer_init.js:101:390
Stderr says:     at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:105:665)
Stderr says:     at EventEmitter.emit (events.js:315:20)
Stderr says:     at Object.onMessage (electron/js2c/renderer_init.js:93:925)
Stderr says: (Use `electron --trace-warnings ...` to show where the warning was created)
Stderr says: (node:22204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Stderr says: (node:22204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It is often (strangely not always) accompained by the following error message in the developer console:
```
Uncaught ReferenceError: require is not defined
    at <anonymous>:1:23
```
Source is `debugger:///VM-85:1`, which leads to the problem code:
```
const {ipcRenderer} = require('electron')
            var astilectron = {
                onMessageOnce: false,
                ...
```
...which undoubteldy comes from [astilectron/index.js](https://github.com/asticode/astilectron/blob/cf8ac47bed894150baf4b96a048640d77e217e9f/index.js#L452).

# Cause

An [answer on StackOverflow](https://stackoverflow.com/a/66509352/13851636) points to a probable cause, which is that Electron 12 enabled [context isolation](https://www.electronjs.org/docs/tutorial/context-isolation) by default (see [breaking changes for Electron 12.0](https://www.electronjs.org/docs/breaking-changes#default-changed-contextisolation-defaults-to-true)).

# Work-around

A work-around seems to manually disable context isolation for the window via `astilecton.WindowOptions`:
```
	// a: *astilectron.Astilectron
	a.NewWindow(url, &astilectron.WindowOptions{
		// ...
		WebPreferences: &astilectron.WebPreferences{
			ContextIsolation: astikit.BoolPtr(false),
		},
	})
```

# Questions

Could/should this situation be handled at the level of (go-)astilectron? May context isolation be incompatible with the way Astilectron currently works? Any ideas at all about this?

**Comment by asticode** [comment]
First off, thanks for the detailed issue.

I do think context isolation is incompatible with `astilectron` therefore it needs to be disabled by force.

Nodejs integration is already [enabled by force](https://github.com/asticode/astilectron/blob/master/index.js#L399).

If you feel like it, I'd welcome a PR that would simply set `json.windowOptions.webPreferences.contextIsolation = false` as well.

Cheers

**Comment by paolobelluticm** [comment]
OK, so it appears that context isolation was the only breaking change in the way of Electron 12 compatibility. Both my app and go-astilectron-demo run fine on the latest stable version 12.0.6, and even 13.0.0-beta.20. Smooth sailing ahead!

Many thanks.

RESOLVED FIXED
