### ISSUE TITLE
Position window?

### ISSUE THREAD

**Issue by Dontmindmes** [asticode/go-astilectron#326]
Hey i see there is an option to center the window but is there an option to position the window at the bottom right? or top right?

**Comment by asticode** [comment]
You need to use a combination of [x and y](https://github.com/asticode/go-astilectron/blob/master/window.go#L121) and the [display](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L408) attributes (such as `width` and `height`).

Let me know how it goes

**Comment by Dontmindmes** [comment]
I am aware of that but is it possible to have it auto set there? Every computer is gonna have diffrent axis of bottem right or top right is there away to have it auto set?

**Comment by asticode** [comment]
> I am aware of that but is it possible to have it auto set there?

Unfortunately I don't think so

> Every computer is gonna have diffrent axis of bottem right or top right

If you use the `display` attributes as I mentionned, it will contain width and height of the user's screen, therefore if you do the correct computations you'll be able to adapt the behavior to every setups
