### ISSUE TITLE
 Creating directory C:\Users\mike\AppData\Roaming\Test\vendor\electron-windows-amd64 fail!!

### ISSUE THREAD

**Issue by MikeGrateful** [asticode/go-astilectron#328]
![image](https://user-images.githubusercontent.com/15280143/127886706-24f15933-ca9d-41c4-b824-d857d10fb8cd.png)

**Comment by MikeGrateful** [comment]
![image](https://user-images.githubusercontent.com/15280143/127886896-e4dd05c7-a3ef-4b39-a4f7-f93c1f133e1a.png)

**Comment by MikeGrateful** [comment]
![image](https://user-images.githubusercontent.com/15280143/127887153-eb89577a-ddc2-4290-814d-33fe4297aa62.png)
download Stuck

**Comment by MikeGrateful** [comment]
plase!! give me electron-windows-amd64-v11.4.3.zip

**Comment by asticode** [comment]
does the computer you're running electron on have access to internet and github.com ?
