### ISSUE TITLE
Run With Sudo

### ISSUE THREAD

**Issue by roociferSonOfTheMorning** [asticode/go-astilectron#329]
Hi again! 

When I attempt to run with sudo I get `Running as root without --no-sandbox is not supported.` Is there anyway I can pass --no-sandbox to the electron command?

Thank you!

**Comment by asticode** [comment]
Check out [this issue](https://github.com/asticode/go-astilectron-bundler/issues/94)

**Comment by roociferSonOfTheMorning** [comment]
That did it! Thank you, thank you!!!
