### ISSUE TITLE
RaspberryPi: Display ID should use int64 and invalid (non-arm/armv7) electron package downloaded

### ISSUE THREAD

**Issue by xplodwild** [asticode/go-astilectron#33]
Hi everyone,

Running into two small issues when using Astilectron on a Raspberry Pi (cross-compiled using GOOS=linux and GOARCH=arm)

First, the wrong electron package is downloaded. I haven't debugged it yet, but the default x64 package is downloaded instead of the arm (or even better, the armv7l) one.

Second, the display ID when using the full KMS driver on Raspberry Pi 3 B is larger than 64 bits and causes a JSON unmarshalling exception:

```
ERRO[0003] json: cannot unmarshal number 1267736906825728 into Go struct field DisplayOptions.id of type int while unmarshaling {"name":"app.event.ready","targetID":"main","displays":{"all":[{"id":1267736906825728,"bounds":{"x":0,"y":0,"width":600,"height":1024},"workArea":{"x":0,"y":0,"width":600,"height":1024},"size":{"width":600,"height":1024},"workAreaSize":{"width":600,"height":1024},"scaleFactor":1,"rotation":270,"touchSupport":"unknown"}],"primary":{"id":1267736906825728,"bounds":{"x":0,"y":0,"width":600,"height":1024},"workArea":{"x":0,"y":0,"width":600,"height":1024},"size":{"width":600,"height":1024},"workAreaSize":{"width":600,"height":1024},"scaleFactor":1,"rotation":270,"touchSupport":"unknown"}}} 
```

Replacing int pointers in display/display_pool with int64 pointers seems to fix the issue. I'll make a pull request if changing that has no other side effect.

**Comment by asticode** [comment]
@xplodwild are you sure you have fetched the last changes from the repo because it looks like problems that I've already been fixed:

- https://github.com/asticode/go-astilectron/blob/master/display.go#L21
- https://github.com/asticode/go-astilectron/blob/master/paths.go#L112

**Comment by xplodwild** [comment]
Whoops my bad, I'm using glide which took the v0.4.0 tag. I'll try with master.

**Comment by xplodwild** [comment]
One note regarding the arm path though, I think you should use the armv7l release instead of the arm. The Go team dropped support for armv6 anyway in the compiler and outputs only armv7 binaries anyway, so the armv7l binaries are better optimized.

**Comment by asticode** [comment]
@xplodwild I've updated to `armv7l` (I've no way of testing it so let me know if that causes any problems) and I've also created a `v0.5.0` tag which should help with glide.

If that fixes your problem, please close this issue.

Cheers

**Comment by xplodwild** [comment]
All good! Thanks
