### ISSUE TITLE
not load the index.html when I Click start the compiled program in GUI mode 

### ISSUE THREAD

**Issue by thathappiness** [asticode/go-astilectron#333]
it works well when I excute the compiled program in command line mode, but when I start the program by clicking in GUI mode, the program does not load any html page, show only blank page, what the problem? I use a MacOS computer

**Comment by asticode** [comment]
I guess you're using both `bootstrap` and `bundler`. Can you share your `bootstrap` options you provide to the `Run` method and more specifically your [Windows](https://github.com/asticode/go-astilectron-demo/blob/master/main.go#L91) options ?

**Comment by thathappiness** [comment]
I use neither **bootstrap** nor **bundler**, just the basic usage...

now I find the problem: 
when I start the program under command line mod,the work dir is the project dir, and it works good, **but it changed to system user dir when I start program by clicking under GUI mod, this leads to the problem that the program can not find the static resources**, I don't know why, how can I resovle this problem?

**the code:**
![Uploading c2706fd020cbf6ce28e88302d845e96.png…]()

**Comment by asticode** [comment]
Since you're not using either bootstrap or bundler, you're left with the default GO/Electron behavior. Unfortunately there's nothing this lib can do for you in this case 😞 Your only solution is to provide absolute paths to functions like what the bundler does.

**Comment by thathappiness** [comment]
thank you for the help
