### ISSUE TITLE
What is the corresponding operation to open supportFetchAPI?

### ISSUE THREAD

**Issue by dosgo** [asticode/go-astilectron#336]
What is the corresponding operation to open supportFetchAPI?

I need to use wasm but this does not seem to be supported. It seems that the fetch function does not support binary file requests.

![image](https://user-images.githubusercontent.com/9545458/134034795-7783e7a8-4ef6-45b3-a985-f248497f52d4.png)

**Comment by asticode** [comment]
Hi, to date this is not supported. Which function would you need in [this list](https://www.electronjs.org/docs/api/protocol)?

I won't have time to work on this anytime soon, are you willing to create a PR?

**Comment by dosgo** [comment]
I haven't understood how to work, and it seems that I haven't found any information on how to interact with electron, so I may not be able to do it for the time being! Wait for me to see. .

**Comment by dosgo** [comment]
Feel sorry! I found that supportFetchAPI is currently enabled by default, so this function seems to be temporarily unavailable. Wasm can't run because of the fs problem of wasm_exec.js, which has been fixed. .
