### ISSUE TITLE
How to solve pages more than one?

### ISSUE THREAD

**Issue by heliping** [asticode/go-astilectron#341]
Dear all,
I use this tool for desk app, very uesful.
but the demo only has one page as the index.html. actually, the normal app used more than one.
I guess the way is use menu to route for different pages.
But how to do? any ways?

**Comment by asticode** [comment]
The simplest solution is to add a menu directly in your HTML/JS app.

Otherwise you can use a `go-astilectron` [menu](https://github.com/asticode/go-astilectron#menus) and use the `OnClick` attribute to send a message to your JS so that it changes page.

**Comment by heliping** [comment]
Is there any demo for this function?

**Comment by heliping** [comment]
I used it with vue, can package successful. 
but when using sendmessage, vue report: "astilectron" not defined.
