### ISSUE TITLE
Auto-delete temporary zip files after downloading Electron?

### ISSUE THREAD

**Issue by koddr** [asticode/go-astilectron#347]
Hi,

How to auto-delete temporary files after downloading Electron?

![Screenshot 2022-01-06 at 23 15 49](https://user-images.githubusercontent.com/11155743/148445886-ea6ab113-b433-4ad3-b727-f73c6a035902.png)

For example, the file `electron-darwin-amd64-v16.0.5.zip` weighs as much as 83.4 Mb!

**Comment by asticode** [comment]
Right now there's no option to do so, but that's a really good idea.

I won't have time to work on this anytime soon, but I'm welcoming PRs.

**Comment by koddr** [comment]
Oh, I see. Okay, I'll try to add that, just please tell me where to look for the Electron source download call in your library?

**Comment by asticode** [comment]
Removing file located at `pathUnzipSrc` after finish [here](https://github.com/asticode/go-astilectron/blob/master/provisioner.go#L207) should make the trick

**Comment by CarsonSlovoka** [comment]
>  please tell me where to look for the Electron source download call in your library?

In the [provisionPackage](https://github.com/asticode/go-astilectron/blob/7c3f023/provisioner.go#L171) that provide the `finish`

where is a function `finish func() error`

And the [finish] function will only be executed when a download is required

so we can add `os.remove` on it.

- remove [Astilectron.zip](https://github.com/asticode/go-astilectron/blob/7c3f023c573a4bf64fc5d81692f071d7893c4e4a/provisioner.go#L149)
- remove [Electron.zip](https://github.com/asticode/go-astilectron/blob/7c3f023c573a4bf64fc5d81692f071d7893c4e4a/provisioner.go#L157-L167)
   `return os.Remove(paths.electronDownloadDst)`

I will add PRs. later. 

----

Hi @asticode

Is there a need to add some optional (that is, you can choose to keep or delete)? I think you should have considered this issue but finally chose to stay. I'm curious about why you chose to stay.

[finish]: https://github.com/asticode/go-astilectron/blob/7c3f023c573a4bf64fc5d81692f071d7893c4e4a/provisioner.go#L202-L206
