### ISSUE TITLE
How to use tray?

### ISSUE THREAD

**Issue by heary29** [asticode/go-astilectron#348]
Hello, I am trying to use go-astilectron project to make a gui program, I need to have a tray function, but I did not get how to deal with the tray mouse click, right click and other events when viewing the source code, just like the maximization or minimization of the window, the tray.go file only contains create, destroy, set the picture, please what should I do next to help my needs?

**Comment by asticode** [comment]
`Tray` inherits the [On](https://github.com/asticode/go-astilectron/blob/master/object.go#L30) method which you can use to react to [tray's events](https://github.com/asticode/go-astilectron/blob/master/tray.go#L14).

For instance:

```go
var t *astilectron.Tray
t.On(astilectron.EventNameTrayEventClicked, func(e astilectron.Event) (deleteListener bool) {
  log.Println("tray has been clicked!")
  return true
})
```

**Comment by heary29** [comment]
Okay, thank you very much!
