### ISSUE TITLE
One full example outside of this repo

### ISSUE THREAD

**Issue by rand99** [asticode/go-astilectron#35]
I think it would be good if you could provide one full example in a separate repo which uses this repo.

Basic needs:
1) Cross platform single binary building (but working - https://github.com/asticode/go-astilectron/issues/13)
2) real single binary as in -css, templates, html static files, icons, images or whatever included-
3) Full-Featured (everything that is currently implemented) included and working in the example.
maybe a simple crud with a sqlite-db, just so people have something they understand and can use right away. maybe copy some 
4) Updated & tested

If you have something that is ready to use for people I think this could be the one go-ui project.
It will grow and people will participate. You are so close, it would be really great.

Usually go ui projects die at some point and stay unfinished, but I think this one could be it.

murlocswarm only works on sierra, no windows (i'm using this at the moment) 
anlabs/ui - author currently not really motivated (according to him), limited on native ui
alexflint/gallium - osx only, no windows, last update march 
nelsam/gxui - one guy picking up and abandoned google go gui opengl repo
golang-ui/nuklear - c bindings , opengl - :-(

**Comment by veecue** [comment]
What about my GroupMatcher (listed in the examples)?

**Comment by asticode** [comment]
@rand99 I think you're right, I've the feeling that the readme is too long and few people logically don't read it all whereas a full example in a separate repo that people could run would make a huge difference.

@veecue your project is really nice but I think this full example should be less clever and have way less custom logic. And its sole purpose should be showing how to use all the features and produce a complete single binary.

All in all that's a great idea, I'll add it to the roadmap!

**Comment by asticode** [comment]
Btw, I've created the repo https://github.com/asticode/go-astilectron-quick-start if any of you want to lay the first stone :)

**Comment by asticode** [comment]
@rand99 I've updated the readme to point the the [demo](https://github.com/asticode/go-astilectron-demo) repo. I'm closing this issue but feel free to create an issue in the demo repo if you feel the demo is still not good enough (and it is :D)

**Comment by rand99** [comment]
Wow! Nice! Just tested it for Mac and Win. You did it!!!!
So from now on people can easily create multiplatform native apps with go.

Thank you!
