### ISSUE TITLE
Bundler build .exe

### ISSUE THREAD

**Issue by heary29** [asticode/go-astilectron#350]
Hello, when I use the bundler to compile the demo in the window, the compiled exe cannot be started by double-clicking, but the exe generated by the compilation of the bundler can be started normally. What may be the reason?

**Comment by asticode** [comment]
Is your antivirus blocking it since it's not signed ? 🤔

**Comment by heary29** [comment]
No, I checked the records related to the interception software and found no sign of being intercepted. After checking the double-click to run, it seems that electron is still decompressed to the specified directory. The json file only has the version of astilectron, and only the compression of astilectron. The package and decompression directory, the exe file compiled without bundler can run correctly, because the exe compiled by bundler can be started and run normally at first, so I am not sure if there is a problem with my bundler.

**Comment by heary29** [comment]
In addition, the Astilectron demo exe file compiled by bundler on other computers cannot be double-clicked to start and run normally on my computer, which confuses me

> Is your antivirus blocking it since it's not signed ? 🤔

**Comment by heary29** [comment]
> In addition, the Astilectron demo exe file compiled by bundler on other computers cannot be double-clicked to start and run normally on my computer, which confuses me
> 
> > Is your antivirus blocking it since it's not signed ? 🤔

Oh, thank you very much, the root cause of the problem I found is a parameter setting error in bootstrap, the problem is solved, thank you for your selfless help! good luck!

**Comment by heary29** [comment]
Oh, thank you very much, the root cause of the problem I found is a parameter setting error in bootstrap, the problem is solved, thank you for your selfless help! good luck!
