### ISSUE TITLE
How to operate the window after Wait() is executed

### ISSUE THREAD

**Issue by heary29** [asticode/go-astilectron#354]
Hello, maybe my method is wrong, but what I want to achieve is that after the astilectron is successfully created, after the Wait() function is executed, I want to hide a window created before to show it, I try to execute window.Show( ), unfortunately it has no effect. I know that after Wait is executed, it enters the block, so what can I do to make the previously hidden window show? Or how to make the operation of the window take effect after Wait()?

**Comment by asticode** [comment]
are you using the `bootstrap` or `astilectron` directly?

**Comment by heary29** [comment]
Yes, I use astilectron directly

**Comment by asticode** [comment]
if you want to execute something after `Wait()` I would suggest using a `goroutine`:

```go
// TODO Setup your window
var w *astilectron.Window

// Do your thing
go func() {
  w.Show()
}()

// Still wait here so that process is closed properly
a.Wait()
```

**Comment by heary29** [comment]
If not directly using astilen, how to operate the previously created window after wait()?

**Comment by asticode** [comment]
You can use the [OnWait](https://github.com/asticode/go-astilectron-demo/blob/master/main.go#L80) function of the bootstrap to store your `window` in a local variable and use it outside the `Wait()` loop
