### ISSUE TITLE
why do you nedd electron after package?

### ISSUE THREAD

**Issue by baerwang** [asticode/go-astilectron#355]

**Comment by baerwang** [comment]
after I pack it application , it is more than 100m, do still need 100m of electrons?

**Comment by asticode** [comment]
yes, astilectron needs Electron so that it can execute it

**Comment by baerwang** [comment]
> yes, astilectron needs Electron so that it can execute it

Is there a way to make the main program less compressed? it's too big

**Comment by asticode** [comment]
> Is there a way to make the main program less compressed? it's too big

if you're using the bundler no. your only other option is to use `astilectron` without the bundler but it will need to download electron on startup.

**Comment by baerwang** [comment]
me already fix question, use **-ldflags -H=windowsgui**, then use **upx compress**
