### ISSUE TITLE
Running multiple applications based on astilectron

### ISSUE THREAD

**Issue by maddie** [asticode/go-astilectron#356]
I have built two separate applications based on go-astilectron (using bootstrap), and it seems only one can be run at the same time, although they're two different applications.

Is there some kind of unique ID setting of the sorts that prevents them from running at the same time?

**Comment by packet-sent** [comment]
If remember correct changing this to false should fix it.

**Comment by packet-sent** [comment]
This should fix it by setting it to false. ![image](https://user-images.githubusercontent.com/72577411/157589636-e9cc244d-35cb-46d8-a034-f9b3fbb9ecae.jpeg)

**Comment by maddie** [comment]
@packet-sent Thanks. But I explicitly set this to `true`, because each of the applications can only have one running at a time. If I'm to set this to `false`, does that mean I have to achieve this per-application singleton goal by other means?

**Comment by asticode** [comment]
the way `astilectron` bundles apps, your 2 applications are not different to the OS and therefore you need to set `SingleInstance` to `false` in your situation. And yes, you'll need to achieve your per-application singleton goal by other means.

**Comment by maddie** [comment]
Understood. Thanks for your clarification!
