### ISSUE TITLE
I'm not quite sure how I can debug my program while developing, I build with Bootstrap

### ISSUE THREAD

**Issue by zichen8552** [asticode/go-astilectron#357]
I saw the example https://github.com/asticode/go-astilectron/tree/master/example You can use go run main.go directly to quickly run and see the effect
Bootstrap can only be viewed every time a file is generated using astilen-bundler?
If I use （go run main.go） directly, it prompts:
.\main.go:29:13: undefined: Asset
.\main.go:30:13: undefined: AssetDir
.\main.go:73:18: undefined: RestoreAssets

**Comment by asticode** [comment]
you need to run `go run *.go` so that it takes all `go` files (including bind file)

**Comment by zichen8552** [comment]
$ go run *.go
Running app built at

I can use 【astillen-bundlerastillen-bundler】 to generate exe files, but using【 go run *.go】 will prompt 【Running app built at】, and it’s over.

**Comment by zichen8552** [comment]
![QQ截图20220321104348](https://user-images.githubusercontent.com/44829696/159198835-c6d0b6f7-95a8-4fa7-b53d-fc95697ac6b7.jpg)

**Comment by asticode** [comment]
If you're looking to use `go run *.go` you need to use `astilectron-bundler bd` (note the `bd` at the end) to only bind data. Can you share all the output if you're still encountering issues ?

**Comment by zichen8552** [comment]
That's all the prompts, very few, so I'm not sure what's wrong
![QQ截图20220321175035](https://user-images.githubusercontent.com/44829696/159238033-f08cd279-8673-4e75-bcdb-f5ed4cc2642a.jpg)

**Comment by asticode** [comment]
Are you setting the logger [properly](https://github.com/asticode/go-astilectron-demo/blob/master/main.go#L56)?

Could you share your bootstrap options ?

**Comment by zichen8552** [comment]
bundler.json
`{
  "app_name": "Astilectron示例",
  "icon_path_darwin": "resources/icon.icns",
  "icon_path_linux": "resources/icon.png",
  "icon_path_windows": "resources/icon.ico"
}`

**Comment by zichen8552** [comment]
Running app built at
2022/03/21 18:13:16 astikit: starting worker...
2022/03/21 18:13:16 Skipping restoring resources...
2022/03/21 18:13:16 Starting...
2022/03/21 18:13:16 Provisioning...
2022/03/21 18:13:16 Provisioning Astilectron...
2022/03/21 18:13:16 Removing directory C:\Users\Administrator\AppData\Roaming\vendor\astilectron
2022/03/21 18:13:16 Disembedding vendor_astilectron_bundler\astilectron.zip into C:\Users\Administrator\AppData\Roaming\vendor\astilectron-v0.51.0.zip...
2022/03/21 18:13:16 C:\Users\Administrator\AppData\Roaming\vendor\astilectron-v0.51.0.zip already exists, skipping disembed...
2022/03/21 18:13:16 Creating directory C:\Users\Administrator\AppData\Roaming\vendor\astilectron
2022/03/21 18:13:16 Unzipping C:\Users\Administrator\AppData\Roaming\vendor\astilectron-v0.51.0.zip\astilectron-0.51.0 into C:\Users\Administrator\AppData\Roaming\vendor\astilectron
2022/03/21 18:13:16 Removing C:\Users\Administrator\AppData\Roaming\vendor\astilectron...
2022/03/21 18:13:16 Closing...
2022/03/21 18:13:16 astikit: stopping worker...

**Comment by zichen8552** [comment]
Thank you very much for your help, I solved it because the version of C:\Users\Administrator\AppData\Roaming\vendo\rastiletron-v0.51.0.zip is incorrect, it is version 0.49.0 in it.
