### ISSUE TITLE
Suddenly not working anymore

### ISSUE THREAD

**Issue by GameBurrow** [asticode/go-astilectron#366]
I have 2 computers, one running Windows 10 and one running Windows 11. Both are quite cleanly installed. When open my executables that have been built by astielectron, they look like this:

![image](https://user-images.githubusercontent.com/4341091/168282734-253eafea-e524-4ece-8af8-dd4ab960c30c.png)

The computer that is running Windows 10, was my main computer up until last week. The same version of the .exe worked just fine there both with Win 11 and Win 11.

Just incease tried to update all go packages and rebuild, still the same.

It should look like this:
![image](https://user-content.gitlab-static.net/01c30da199e8e24a82e3336bbcb765f37107f64f/68747470733a2f2f692e696d6775722e636f6d2f326e76514577702e706e67)

**Comment by asticode** [comment]
Mmmm it seems the `.html` is not loaded properly 🤔 And the icon next to the window title is the wrong one too...

Can you tell me if there's something at `C:\Users\kerts\AppData\Roaming\GO Group Virtual OMSI Tool\resources\icon.png` ?

**Comment by GameBurrow** [comment]
> Mmmm it seems the `.html` is not loaded properly 🤔 And the icon next to the window title is the wrong one too...
> 
> Can you tell me if there's something at `C:\Users\kerts\AppData\Roaming\GO Group Virtual OMSI Tool\resources\icon.png` ?


Not at all 
![image](https://user-images.githubusercontent.com/4341091/168293152-e2864a94-5491-4ecc-b384-d2a923b6f90e.png)

**Comment by asticode** [comment]
Are you using the [bundler](https://github.com/asticode/go-astilectron-bundler)?

**Comment by GameBurrow** [comment]
> Are you using the [bundler](https://github.com/asticode/go-astilectron-bundler)?

Yep. My entire project is open-sourced: https://gitlab.com/gogroupvirtual/omsi-map-overhaul-generator#data

**Comment by packet-sent** [comment]
I was having something like this so I just ended up using go embed to bundle the resources in the binary itself.

**Comment by asticode** [comment]
From which directory are you running the bundler ? And what are the ouput logs ?

I think what's happening is that you're not running the bundler from inside your `src` directory, therefore your `resources` are not binded to the binary.

**Comment by GameBurrow** [comment]
As I said, it worked before.

This .exe https://gitlab.com/gogroupvirtual/omsi-map-overhaul-generator/-/releases/0.7.1, built 2 months ago. Worked up just fine, starting from around last week. It no longer works. Same - already built .exe

**Comment by asticode** [comment]
This stopped working at [this commit](https://gitlab.com/gogroupvirtual/omsi-map-overhaul-generator/-/commit/3b6973a9dff4e5ab41fc96215589be10129eb0a8): without the `Asset` methods, the bootstrap has no way to disembed resources properly.

**Comment by GameBurrow** [comment]
Ah I see. I'm guessing it worked on the old computer because I already had the files there from previous runs.

Let me try to fix that.

**Comment by GameBurrow** [comment]
Indeed, that was the cause.
/close
