### ISSUE TITLE
How to open multiple app

### ISSUE THREAD

**Issue by zhou2ding** [asticode/go-astilectron#370]
Hello, I create two project and use coommand "astilectron-bundler" to bundle them, but I can only open one app, if I open another app, logs show error: "creating window failed: context canceled"

**Comment by asticode** [comment]
Can you share the whole log output for both apps ?

**Comment by zhou2ding** [comment]
The app that failed to open: 
![image](https://user-images.githubusercontent.com/26682497/170908790-e9d279aa-978b-4274-b65c-ff630b5ff91e.png)

The app that open successfully: 
![36048DD0-D887-4eaa-8C84-301D04671688](https://user-images.githubusercontent.com/26682497/170909432-33a8c026-f299-4117-9d1f-61055b9f1509.png)

**Comment by asticode** [comment]
Have tried setting [SingleInstance](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L72) to `false`?

**Comment by zhou2ding** [comment]
Oh, I set this field to false and it worked, thank you very much~
