### ISSUE TITLE
Can not relaunch window after w.Close()

### ISSUE THREAD

**Issue by Dontmindmes** [asticode/go-astilectron#371]
Hello,

I encounter an issue, when i create a window for example "w.Create()" and i display the window because it was created, and i close it so its no longer visible and attempt to call the same window "w" from one of my other windows it does not let me "w.Create()" or "w.Show()" the window after i run "w.Close()", how can i display the window again after closing it? 

Thank you

**Comment by asticode** [comment]
Once the window is closed, you can't reuse it. What you seem to be looking to do instead is hiding the windows instead of closing it.

**Comment by Dontmindmes** [comment]
But when i use hide and all windows are closed through the close button at the frame the program keeps running because the window is hidden

**Comment by asticode** [comment]
If you use the window [closed](https://github.com/asticode/go-astilectron/blob/master/window.go#L44) and [hide](https://github.com/asticode/go-astilectron/blob/master/window.go#L49) event, you can know which of your windows are closed and hidden. Then, based on this info, when you think the program should be closed, you can use the [Stop](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L377) method to stop the program.
