### ISSUE TITLE
 linux bundle failed

### ISSUE THREAD

**Issue by passerbyo** [asticode/go-astilectron#374]
2022/07/15 03:18:43 Building for os linux and arch amd64 astilectron: 0.51.0 electron: 11.4.3
2022/07/15 03:18:43 Executing go build -ldflags -X "main.AppName=Astilectron demo" -X "main.BuiltAt=2022-07-15 03:18:43.836555438 -0400 EDT m=+6.584818528" -X "main.VersionAstilectron=0.51.0" -X "main.VersionElectron=11.4.3" -o /root/go/GOCODE/src/github.com/asticode/go-astilectron-demo/output/linux-amd64/binary github.com/asticode/go-astilectron-demo
2022/07/15 03:19:18 bundling failed: bundling for environment linux/amd64 failed: building failed: # github.com/asticode/go-astilectron-demo
**/root/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: i386 architecture of input file `/tmp/go-link-4158473790/000000.o' is incompatible with i386:x86-64 output
collect2: error: ld returned 1 exit status**

**Comment by asticode** [comment]
Have you tried building other go binaries on this machine ?

**Comment by asticode** [comment]
Is your machine a 32 bits machine ?
