### ISSUE TITLE
require is not defined when injecting ipc interop on window intialization

### ISSUE THREAD

**Issue by joshLong145** [asticode/go-astilectron#378]
Currently on the latest version, after a window is created, there is always an observed error of `require is undefined` which has been observed to come from injected JS context upon window initialization. no combination of option flagging has been observed to fix the issue. this has been tested with go 1.18 and go 1.17

**Comment by asticode** [comment]
Which platform are you testing on?

**Comment by joshLong145** [comment]
> > Which platform are you testing on?
> 
> I am testing with latest version and version 1.18 of go using version 19 of electron. i have also tried numerous electron versions with the same result.

my operating system is MacOs (M1)

**Comment by asticode** [comment]
Did you try with the [demo](https://github.com/asticode/go-astilectron-demo), the [example](https://github.com/asticode/go-astilectron/tree/master/example) or custom code?

**Comment by joshLong145** [comment]
> Did you try with the [demo](https://github.com/asticode/go-astilectron-demo), the [example](https://github.com/asticode/go-astilectron/tree/master/example) or custom code?

I did not test the example. I was testing with a simple index.html with embedded javascript.

**Comment by asticode** [comment]
Can you reproduce the problem with the example ?

**Comment by joshLong145** [comment]
> Can you reproduce the problem with the example ?

I can try, i am curious if there is any required implementations within the client web contents that i am missing. I could be missing something but I am unsure as to why the options for node integration are not being respected as if i load the js defined as a string as a preload it does work as expected. but since those options are not exposed to go I feel there arent many options for devs to resolve this.

**Comment by asticode** [comment]
Thing is I'm not reproducing the problem either in the example or in the demo therefore I'm trying to find where the problem could be coming from. Since you're testing on a different machine than mine, I would like to eliminate the hypothesis that there are specific problems on arm64 (specifically Mac M1) machines. If both the example and the demo work fine on your machine, could you share a snippet of your code so that I see if there are any problems either with astilectron or with the way you're using it ?

**Comment by joshLong145** [comment]
> Thing is I'm not reproducing the problem either in the example or in the demo therefore I'm trying to find where the problem could be coming from. Since you're testing on a different machine than mine, I would like to eliminate the hypothesis that there are specific problems on arm64 (specifically Mac M1) machines. If both the example and the demo work fine on your machine, could you share a snippet of your code so that I see if there are any problems either with astilectron or with the way you're using it ?

I can share the test bench I was creating. from what i can tell it seems to be an issue with `WebPreference` option `nodeIntegration` not being set. it seems the go struct that implements these options does not allow for configuring it which makes sense with the way the project is written as it needs to have commonJS and NodeJS api's available. however it doesnt seem like the flag is being respected as this has been a non default option since Electron version 5 or so. I have tested with a variety of Electron releases and they all give the same issue. If this is not reproducible on your end. do you know if your wrappers require any special boilerplate in the renderer to support node runtime binding correctly?

**Comment by asticode** [comment]
Sharing the test bench you created would help 👍 

`nodeIntegration` is always [set to true](https://github.com/asticode/astilectron/blob/master/index.js#L461) in JS in astilectron. Which version of `astilectron` is it using by the way ?

**Comment by joshLong145** [comment]
I was targeting `0.29.0` and also tried a few version back with no successful outcome. We have decided to pivot our strategy to another design which no longer requires an electron binding layer in go. However, I am still curious from a high level if simply defining a `static` directory with a single `index.html` as the loaded content for a window should work out of the box. In the examples i see various helper files with this project's namespace for both `.css` and `.js` and wondering if they are required in someway. However, to my understanding this error is entirely due to NodeJS interoping through the chromium instance running within electron.

**Comment by asticode** [comment]
Defining a `static` directory with a single `index.html` is perfectly fine, and in most cases is the best solution.
