### ISSUE TITLE
BaseDirectoryPath does not work under windows

### ISSUE THREAD

**Issue by GavinTan** [asticode/go-astilectron#380]

**Comment by asticode** [comment]
Could you provide more information because I can't see how I could help you with the information you provided 😬

**Comment by GavinTan** [comment]
windows is always located under AppData\Roaming + AppName, I tested on linux and it works fine

![image](https://user-images.githubusercontent.com/10555093/183397015-57287f87-fad3-47b8-a6b3-bb297762fb69.png)

**Comment by asticode** [comment]
If you don't specify a `DataDirectoryPath` in the options, you're on Windows and there's an `APPDATA` environment variable, the lib will take the `APPDATA` environment variable as `dataDirectoryPath` (which is what is happening to you).

On Windows, if you want to specify a data directory path, you need to use the `DataDirectoryPath` with the `BaseDirectoryPath`.

**Comment by GavinTan** [comment]
Understood, thank you！
