### ISSUE TITLE
dock icon not invalid

### ISSUE THREAD

**Issue by baerwang** [asticode/go-astilectron#384]
setup appdetail title has effect,icon invalid,icon use absolute path
![image](https://user-images.githubusercontent.com/52104949/196040434-156a0968-3a95-49a5-8080-e54595214f60.png)

![image](https://user-images.githubusercontent.com/52104949/196040518-b531eaa0-1a5e-4aa0-a21c-e56eef3a5c3d.png)

link:https://github.com/asticode/go-astilectron/pull/171, No unit tests or test cases

**Comment by asticode** [comment]
Did you find what the problem was ?
