### ISSUE TITLE
tray how impl double click

### ISSUE THREAD

**Issue by baerwang** [asticode/go-astilectron#385]
link: https://github.com/asticode/go-astilectron/issues/31#issuecomment-318884362
**trayEventBalloonClicked** and tray **double-click** relation is it??

**Comment by baerwang** [comment]
need double click show windows,how impl

**Comment by asticode** [comment]
If you want to react when user double clicks on the tray, you should listen to `EventNameTrayEventDoubleClicked` event and do whatever you need to do in there.

**Comment by baerwang** [comment]
> If you want to react when user double clicks on the tray, you should listen to `EventNameTrayEventDoubleClicked` event and do whatever you need to do in there.

me use tray listener,tray  that do not the window control, such as display, minimize,need to change js code?

**Comment by asticode** [comment]
You need to find a way to share you `*astilectron.Window` in your `*astilectron.Tray`. If you're using the bootstrap, you can use the [OnWait](https://github.com/asticode/go-astilectron-demo/blob/master/main.go#L80) method.

**Comment by baerwang** [comment]
thx,impl success 🍻
