### ISSUE TITLE
getDisplayMedia not working

### ISSUE THREAD

**Issue by itroeix** [asticode/go-astilectron#386]
I am trying to use ```navigator.mediaDevices.getDisplayMedia``` (to view the desktop screen), when I use it I get this error:
```NotFoundError: Requested device not found```

**Comment by itroeix** [comment]
Now it gives this error ```NotAllowedError: Permission denied```

**Comment by asticode** [comment]
`navigator.mediaDevices` is not yet implemented in this lib.

I'm welcoming PRs to add support for this.
