### ISSUE TITLE
Tips of x11 Forwarding

### ISSUE THREAD

**Issue by roociferSonOfTheMorning** [asticode/go-astilectron#387]
Hello, 

I am looking for additional guidance to get x11 forwarding to work. 
I added --no-xshm to the ElectronSwitches but that didn't do it.  (based on this issue https://github.com/electron/electron/issues/22775#issuecomment-616023334 )

The application launches to a blank window and there is nothing significant in the logs:
```
Sending to Astilectron: [{\"name\":\"window.cmd.web.contents.open.dev.tools\",\"targetID\":\"1\"}]
astikit: received signal [urgent I/O condition]
astikit: received signal [child exited]
output/linux-amd64/vendor/electron-linux-amd64/electron -1]' exited with code: %!v(MISSING)
App has crashed[]

```
xeyes works fine

Any advice would be awesome.
Thank you!

**Comment by asticode** [comment]
Is that the only logs you're getting ? 🤔  There should be much more 🤔
