### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by spieglt** [asticode/go-astilectron#39]
I can't seem to build the examples because paths.go uses os.Executable() which does not work on Windows. Is this known behavior? Thanks.
```
$ go run examples/3.webserver_app/main.go
# github.com/asticode/go-astilectron
.\paths.go:64: undefined: os.Executable
```

**Comment by asticode** [comment]
@spieglt are you sure you're using Go 1.8+ ? This function only exists in Go 1.8+

**Comment by spieglt** [comment]
Ah, thanks. I won't be around the computer on which I was having the issue until later, but I've gotten it to work on another Windows machine now so that must have been it.

**Comment by spieglt** [comment]
Confirmed: I had been on Go 1.7.5. Thanks for the help.
