### ISSUE TITLE
Is it possible to use go-astilectron to open a URL that contains a WebSocket connection, and then retrieve the messages sent and received through this WebSocket connection?

### ISSUE THREAD

**Issue by oshellhahaha** [asticode/go-astilectron#390]

**Comment by asticode** [comment]
You need to parse the websocket messages in your JS and forward them to GO.

Take a look at [that section](https://github.com/asticode/go-astilectron#send-messages-from-javascript-to-go) in the README.

Let me know if you need some more info.
