### ISSUE TITLE
how to change icon for windows application

### ISSUE THREAD

**Issue by asdfsx** [asticode/go-astilectron#401]
I'm trying to build windows application on macOS, and I met a problem that the icon of the application can not change.

I build the application with the command `astilectron-bundler -c "bundler-win.json" -ldflags "-linkmode external -extldflags -static"`, and the `bundler.json` is like below

```json
{
  "app_name": "desktop",
  "icon_path_darwin": "resources/icon.icns",
  "icon_path_linux": "resources/icon.png",
  "icon_path_windows": "resources/icon.ico",
  "environments": [
    {
      "arch": "amd64", 
      "os": "windows",
      "env": {
        "CC": "x86_64-w64-mingw32-gcc",
        "CXX": "x86_64-w64-mingw32-g++",
        "CGO_ENABLED": "1"
      }
    }
  ]
}
```

But the icon always be ![image](https://github.com/asticode/go-astilectron/assets/2292716/b9400576-831d-4a1e-ba6b-3e773e386865) 
So I want to know how to update the icon for the windows application.

**Comment by asticode** [comment]
Did you change the icon located at `resources/icon.ico`?

**Comment by asdfsx** [comment]
yes, I have change the icon. 
When I use `regular icon` or `extra large icon` in file explorer, the application show as 
![image](https://github.com/asticode/go-astilectron/assets/2292716/018cc47d-7c5d-42ee-b0fc-619e7ea0ea16)
When I use `medium icon`, the application show as 
![image](https://github.com/asticode/go-astilectron/assets/2292716/01127bfa-e787-48b0-8b98-1ce89fac1b00) which is the icon I replaced.
Now I'm very confused about this

**Comment by asdfsx** [comment]
I think the problem is caused by the ico file I make. And the windows icon cache made the problem more confuse.
After I recreate the ico file and clean the cache, the problem solved.
