### ISSUE TITLE
Tray menu overwrites application menu

### ISSUE THREAD

**Issue by tehsphinx** [asticode/go-astilectron#45]
Hi!

I just started using go-astilectron. I had a look at the demo and realized that when adding TrayMenuOptions they seem to overwrite the menu options.

I then used the Run() as a sample and eliminated the bootstrap package from my test but the issue is the same.

Am I doing something wrong?

Note: I am working on MacOSX 10.12.6.

**Comment by asticode** [comment]
@tehsphinx can you post the full code that causes the problem ?

**Comment by tehsphinx** [comment]
Sure, I can describe more closely what I did.

Take a fresh copy of the demo:
`go get -u github.com/asticode/go-astilectron-demo`

Edit main.go by adding a TrayMenu:
```
		RestoreAssets: RestoreAssets,
		TrayOptions: &astilectron.TrayOptions{
			Image:   astilectron.PtrStr("resources/tray.png"),
			Tooltip: astilectron.PtrStr("Wow, what a beautiful tray!"),
		},
+		TrayMenuOptions: []*astilectron.MenuItemOptions{
+			{
+				Label: astilectron.PtrStr("foo"),
+				SubMenu: []*astilectron.MenuItemOptions{
+					{
+						Label: astilectron.PtrStr("bar1"),
+					}, {
+						Label: astilectron.PtrStr("bar2"),
+					},
+				},
+			},
+		},
		WindowOptions: &astilectron.WindowOptions{
			BackgroundColor: astilectron.PtrStr("#333"),
			Center:          astilectron.PtrBool(true),
			Height:          astilectron.PtrInt(600),
			Width:           astilectron.PtrInt(600),
		},
```

Use the bundler to build the app on Mac:
`astilectron-bundler -v`

Run the app:
`open output/darwin-amd64/Astilectron\ demo.app/`

Now the tray icon has a menu (yay!) but the application menu has been overwritten with the newly added tray menu structure (arrggh!). The application menu should be the original menu of the demo which is:

```
		MenuOptions: []*astilectron.MenuItemOptions{
			{
				Label: astilectron.PtrStr(AppName),
				SubMenu: []*astilectron.MenuItemOptions{
					{
						Role: astilectron.MenuItemRoleClose,
					},
				},
			},
			{
				Label: astilectron.PtrStr("Style"),
				SubMenu: []*astilectron.MenuItemOptions{
					{
						Checked: astilectron.PtrBool(true),
						Label:   astilectron.PtrStr("Dark"),
						OnClick: func(e astilectron.Event) (deleteListener bool) {
							// Send
							if err := window.Send(bootstrap.MessageOut{Name: "set.style", Payload: "dark"}); err != nil {
								astilog.Error(errors.Wrap(err, "setting dark style failed"))
								return
							}
							return
						},
						Type: astilectron.MenuItemTypeRadio,
					},
					{
						Label: astilectron.PtrStr("Light"),
						OnClick: func(e astilectron.Event) (deleteListener bool) {
							// Send
							if err := window.Send(bootstrap.MessageOut{Name: "set.style", Payload: "light"}); err != nil {
								astilog.Error(errors.Wrap(err, "setting dark style failed"))
								return
							}
							return
						},
						Type: astilectron.MenuItemTypeRadio,
					},
				},
			},
		},
```

But all that seems to have been replaced with the tray menu when running the app.

**Comment by asticode** [comment]
@tehsphinx I've fixed the problem. Here's what you need to do to fetch the changes:

- `cd /your/path/to/go-astilectron-bundler`
- `go get -u ./...`
- `cd /your/path/to/go-astilectron-demo`
- `go get -u ./...`

Does this fix your issue?

**Comment by asticode** [comment]
@tehsphinx Does this fix your issue?

**Comment by tehsphinx** [comment]
@asticode: Yes it does!

Thank you very much. I will play more with this project. I like it :)
