### ISSUE TITLE
application 'crashes' on window close

### ISSUE THREAD

**Issue by cj123** [asticode/go-astilectron#46]
Not sure if this is macOS only or not - I don't have any other information available.

When clicking the close button on a window (in the [asticode/go-astilectron-demo](https://github.com/asticode/go-astilectron-demo) application), the following sequence of events happens:

```
DEBU[0021] Astilectron says: {"name":"window.event.closed","targetID":"1"}
DEBU[0021] App has crashed
DEBU[0021] Stopping...
DEBU[0021] Closing...
```

In this case, the "crash" has no real negative affects since the application only has the one window anyway. However for my use case I need the main application to continue running after one window has closed, and this seems to be preventing that.

**Comment by asticode** [comment]
@cj123 it seems like electron closes the app when the users closes the window. However there seem to have ways to counter-act this behavior:

https://discuss.atom.io/t/how-to-catch-the-event-of-clicking-the-app-windows-close-button-in-electron-app/21425/8

I'll add an attribute to the WindowOptions so that when you click on the red cross it only hides the window. Meaning the user will never be able to close the window.

**Comment by asticode** [comment]
@cj123 in the meantime check out the `Closable` attribute in `WindowOptions`, I've not tested it but maybe if you set it to `true` it will do what you desire...

**Comment by cj123** [comment]
@asticode I believe that disables the close button on the window entirely. I can try work with that and use a "close" button in my HTML that performs the window close action for now, but i'd much rather the window controls be used for that purpose 😄

**Comment by asticode** [comment]
@cj123 ok good to know, I'll add the the attribute in WindowOptions anyway

**Comment by asticode** [comment]
@cj123 I've added 2 things:

- a `MinimizeOnClose` window Option. Just put it to `true` if you want to minimize the window when one tries to close it
- a `Quit()` method to `*Astilectron`. Indeed what I've experienced on Linux is that using the `Close` menu role, Electron simply closes the window without trying to quit the app, resulting on simply minimizing the window when the previous option is on. Therefore what you'll propably need to do is add the following menu item:

```go
Label: astilectron.PtrStr("Close"),
OnClick: func(e astilectron.Event) (deleteListener bool) {
    app.Quit()
    return
},
```

with `app` being your `*Astilectron`.

That way you have a way to really quit the app.

If you're using the bundler to bundle your app, you'll have to `go get -u` it as well as run the following command:

`$ cd /path/to/bundler && make`

Does that fix your issue ?

**Comment by tehsphinx** [comment]
My experience is that only a "close" on the main window actually closes the application. Other windows can be closed without the app being closed.

In my opinion a `MinimizeOnClose` option is a good option to have, regardless!

**Comment by lthibault** [comment]
@asticode On Mac, the `HideOnClose` option nevertheless shuts down the app.  I'm guessing this is a bug?

**Comment by asticode** [comment]
I've just tested it with the demo (I've added a `HideOnClose` option) and it's working. However, when I click on the Dock's icon, the window doesn't show which must be a Darwin-only behavior. I've created [this issue](https://github.com/asticode/go-astilectron/issues/255)
