### ISSUE TITLE
Can't use synchronousEvent inside a listener

### ISSUE THREAD

**Issue by tehsphinx** [asticode/go-astilectron#49]
Currently I am playing with minimize, maximize, resize events of a window. I realized that they are not triggered when minimizing (etc.) the window on my mac. (Put some debugs in the code to be sure but they are definitely not triggered.)

Not sure if this is a general issue with JS side events not correctly relayed to go or not.

**Comment by asticode** [comment]
@tehsphinx can you paste the code that you're using to catch those events?

**Comment by tehsphinx** [comment]
@asticode:

Just investigated another thing where I would close the window (fire `window.event.closed`) which in turn would bring "App has crashed" message and then try to fire `app.crash` -- but it cannot because the channel is still blocked since `window.event.closed` is still processing.

Here a suggestion to fix this in the Dispatcher:
```
 // start starts the dispatcher and listens to dispatched events
 func (d *Dispatcher) start() {
 	for {
 		select {
 		case e := <-d.c:
 			for id, l := range d.listeners(e.TargetID, e.Name) {
-				if l(e) {
-					d.delListener(e.TargetID, e.Name, id)
-				}
+				go func(l Listener, id int) {
+					if l(e) {
+						d.delListener(e.TargetID, e.Name, id)
+					}
+				}(l, id)
 			}
 		case <-d.cq:
 			return
 		}
 	}
 }
```

After applying that the minimize, maximize, resize events would trigger as expected.

Here my code base: https://github.com/tehsphinx/service_gui
It is basically a little interface for a locally running background service. I disabled the service start so you can test it without having the service.

Note: code is a bit of a mess right now... normally I don't push code like that.

**Comment by tehsphinx** [comment]
Probably better to pass `e` (Event) as a parameter to the go function as well...

**Comment by tehsphinx** [comment]
I've slept on this solution and have a few more thoughts on it:

1. I ran into a issue earlier on where I used a function that triggered an event inside a function that was triggered by another event. That did not work unless I started a new go routine. This solution would keep me from having to start a goroutine myself. Sample from my repo:
```
func showLogEvent(e astilectron.Event) (deleteListener bool) {
	go showLog()  \\ triggers another event, so the go routine is currently needed
	return
}
```

2. There might be some events at some point in the future where you want to make sure all functions have finished executing BEFORE the main function continues. Typical examples are events like `beforeClose` where we want to make sure everything executes before the object is closed. For this we would need another solution. Current solution (without the go routine in `Dispatcher.start()`) is not fit to handle this scenario either. Let me know if you want a proposition for this.

**Comment by asticode** [comment]
**Regarding your 2nd post**

the dispatcher was made to execute listeners sequentially, that's why I don't think this is a good idea to execute the listeners in a go routine.

The problem you're facing has to do with one of your listener blocking more than anything which is not a good thing to have. Do you know why your listener is blocking? Executing it in a go routine just hides the problem.

Once your listener won't block anymore, you'll be able to catch minimize, maximize events as well.

**Comment by asticode** [comment]
**Regarding your 4th post**

I do agree that there's a problem when an event is dispatched into a listener since as of now events are sent into a unique channel and the whole process is therefore blocked.

However the current solution was actually made to make sure all functions have finished BEFORE the main functions continues (check out the [synchronousEvent](https://github.com/asticode/go-astilectron/blob/master/helper.go#L167) method).

The problem the current solution has is that you can't call `synchronousEvent` inside a listener.

I'll update the title of the issue and try to think of a solution.

**Comment by tehsphinx** [comment]
> However the current solution was actually made to make sure all functions have finished BEFORE the main functions continues (check out the synchronousEvent method).

That is currently not the case. The main functions continue to execute as soon as the dispatcher STARTS to execute the listeners. If you want the main function to wait for the listeners to finish we need to pass a channel to the goroutine executing the listeners and pass a value back when it is done.

Current Code (not waiting for functions to finish)
```
// Dispatch dispatches an event
func (d *Dispatcher) Dispatch(e Event) {
	d.c <- e // continues as soon as event is read from the channel
}

// start starts the dispatcher and listens to dispatched events
func (d *Dispatcher) start() {
	for {
		select {
		case e := <-d.c: // as soon as this line gets the event, main function continues
			for id, l := range d.listeners(e.TargetID, e.Name) {
				if l(e) {
					d.delListener(e.TargetID, e.Name, id)
				}
			}
		case <-d.cq:
			return
		}
	}
}
```

Conceptual solution that actually waits for the listeners to finish
```
// Dispatch dispatches an event
func (d *Dispatcher) Dispatch(e Event) {
	d.c <- e
	<-d.done  // this works as long as we have no buffered channel 'd.c'. Otherwise we would need to create a new channel for every call to Dispatch and pass in with the event to d.c
}

// start starts the dispatcher and listens to dispatched events
func (d *Dispatcher) start() {
	for {
		select {
		case e := <-d.c:
			// if you want to keep the order events are executed in, just move the go func outside the for loop
			//go func(e Event) { 
			for id, l := range d.listeners(e.TargetID, e.Name) {
				if l(e) {
					d.delListener(e.TargetID, e.Name, id)
				}
			}
			d.done <- true  // tell Dispatch that we are done.
			//}(e)
		case <-d.cq:
			return
		}
	}
}
```

In the above sample I included a new suggestion for fixing the blocking listeners problem where the listeners are executed in order.

Generally:
I don't see a way around a goroutine here. Also I don't see any disadvantage as the main function already is in another goroutine than the listeners. Listeners are executed in the `start` function which is executed via `go start()` -- so different go routine.

**Comment by tehsphinx** [comment]
There is a disadvantage of my latest suggestion with the go func around the listeners loop:
There cannot be 2 listeners each triggering an event. It will block again.

**Comment by tehsphinx** [comment]
https://github.com/asticode/go-astilectron/pull/52
