### ISSUE TITLE
Clear Electron's HTTP cache

### ISSUE THREAD

**Issue by asticode** [asticode/go-astilectron#56]
Moving [this issue](https://github.com/asticode/astilectron/issues/2) to this repo

**Comment by asticode** [comment]
@HeavyHorst I've added a `Session` attribute to the `Window` object. You can then call `w.Session.ClearCache()` to clear the window's HTTP cache. The readme has also been updated.

Does this fix your issue?

**Comment by HeavyHorst** [comment]
Great, thanks!

Thats exactly what i needed.

Quentin Renard <notifications@github.com> schrieb am Sa., 25. Nov. 2017,
10:51:

**Comment by deepch** [comment]
Very good.


 I'm use custom http server

`go-astilectron + gorilla mux + r.Static("/static", "./web/static")  = no problem 
`
work ok



migrate to

`go-astilectron + gin + r.Static("/static", "./web/static")  = cache problem`

modify static js or css file not update to app


I recommend you use w.Session.ClearCache(). It helped me;)  

Perhaps this experience will help you.
