### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by JennyZmx** [asticode/go-astilectron#58]
I tried the demo and downloaded packages as required by step 1 and step2. However, when I run step 3 "$ astilectron-bundler -v", I got an error saying that "bundler: command not found". I'm really new to programming and have no idea why this happened. Do I need to install anything other than your packages?

**Comment by asticode** [comment]
@JennyZmx 3 things:

- on which OS are you working?
- can you paste the result of `cd $GOPATH/bin`
- are you sure you didn't forget the `/...` at the end of the command of `step 2`?

Cheers

**Comment by JennyZmx** [comment]
Thank you for the quick reply! 

I'm working on macOS High Sierra, version 10.13.1. I'm sure I didn't forget /...of step 2 as I downloaded it again just now and it still won't work. The following is what I got after `cd $GOPATH/bin`.
`Mengxins-MBP:go-astilectron-demo zhangmengxin$ cd $GOPATH/bin`
`Mengxins-MBP:bin zhangmengxin$ cd $GOPATH/bin`
`Mengxins-MBP:bin zhangmengxin$ `

**Comment by asticode** [comment]
@JennyZmx try those 2 commands and let me know how it goes:

- `cd $GOPATH/src/github.com/asticode/go-astilectron-bundler`
- `make`

**Comment by JennyZmx** [comment]
That's how it looks:
`Mengxins-MBP:~ zhangmengxin$ cd $GOPATH/src/github.com/asticode/go-astilectron-bundler`
`Mengxins-MBP:go-astilectron-bundler zhangmengxin$ make`
`go install ./astilectron-bundler`
`Mengxins-MBP:go-astilectron-bundler zhangmengxin$ `

**Comment by asticode** [comment]
and can you try again `astilectron-bundler -v` in the demo folder?

**Comment by JennyZmx** [comment]
Still, `-bash: astilectron-bundler: command not found`

**Comment by JennyZmx** [comment]
I looked at the post https://github.com/codegangsta/gin/issues/114 @kylerdanielster. So I tried 
`~/go/bin/astilectron-bundler -v` and it worked! But I still have no idea why...

**Comment by asticode** [comment]
ha got it, this is because you need to add $GOPATH/bin to your $PATH variable :)

After that, you'll be able to use `astilectron-bundler -v` right away with specifying the absolute path

**Comment by JennyZmx** [comment]
That's a really interesting lesson! Thank you for your help!
