### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by ericdgit** [asticode/go-astilectron#59]
When I run `go get -u github.com/asticode/go-astilectron`, I get an error: 

`package github.com/mattn/go-colorable: directory "c:\\[MyPath]\\GoLang\\src\\github.com\\mattn\\go-colorable" is not using a known version control system`

Using windows.

**Comment by asticode** [comment]
@ericdgit can you remove "c:\\[MyPath]\\GoLang\\src\\github.com\\mattn\\go-colorable" and try again?

**Comment by ericdgit** [comment]
Hmm... Now it says the following:

C:\>go get -u github.com/asticode/go-astilectron
# cd C:\\[MyPath]\GoLang\src\github.com\asticode\go-astitools; git pull --ff-only
From https://github.com/asticode/go-astitools
 + 1b26a93...8f6534c master     -> origin/master  (forced update)
fatal: Not possible to fast-forward, aborting.
package github.com/asticode/go-astitools/context: exit status 128

**Comment by asticode** [comment]
Hmmm this is weird, can you try again now ?

**Comment by ericdgit** [comment]
Repeated the command and got the same response at first, but then I emptied the directory `\asticode\` and then it seemed to work! Thanks!!

**Comment by asticode** [comment]
you're welcome :)
