### ISSUE TITLE
Build error?

### ISSUE THREAD

**Issue by fasilenko** [asticode/go-astilectron#6]
% go get -u github.com/asticode/go-astilectron  
# github.com/asticode/go-astilog
workspace/src/github.com/asticode/go-astilog/logger.go:42: not enough arguments in call to logrus.IsTerminal
	have ()
	want (io.Writer)
workspace/src/github.com/asticode/go-astilog/out_syslog.go:16: not enough arguments in call to logrus.IsTerminal
	have ()
	want (io.Writer)

**Comment by asticode** [comment]
@fasilenko thanks for filing the issue, I got mixed up there. It should be all good now.

Could you close the issue if that fixes your problem ?

Cheers

**Comment by fasilenko** [comment]
Thanx a lot! Now it's ok.
