### ISSUE TITLE
Add screenshot with code exemples

### ISSUE THREAD

**Issue by uepoch** [asticode/go-astilectron#60]
Everything is in the title, all of this looks nice but it would be better for advanced feature such as Trays and Menus,

otherwise, another great project 👍

**Comment by asticode** [comment]
@uepoch sounds like a good idea! for now you have 2 options to see examples:

- check out the README that contains small code samples
- check out the [demo](https://github.com/asticode/go-astilectron-demo) that shows how to use the [bootstrap](https://github.com/asticode/go-astilectron-bootstrap) and the [bundler](https://github.com/asticode/go-astilectron-bundler)

Cheers
bite
