### ISSUE TITLE
Is go-bindata can prevent decompile?

### ISSUE THREAD

**Issue by konding** [asticode/go-astilectron#63]
So we can protect the js, css source code.
I barely know Golang. Please tell me If you know the answer.

**Comment by asticode** [comment]
@konding decompiling an unstripped Golang binary is pretty straight forward. Decompiling a stripped Golang binary is a little bite more difficult but still pretty easy (astilectron's [bundler](https://github.com/asticode/go-astilectron-bundler) now builds stripped Golang binaries). As go-bindata stores the file's content in clear, it's pretty easy to retrieve the js/css source code as of now.

To top all that, the first thing astilectron's does is disembed the js/css source code therefore those files are actually created on disk and can be explored in clear very easily.

**Comment by konding** [comment]
yes, i see.
btw, the Golang source code is safe, right?

**Comment by asticode** [comment]
what do you mean by safe?

**Comment by konding** [comment]
i mean golang won't be decompiled, like java, c#.

**Comment by asticode** [comment]
nah people won't be able to decompiled it like java, but they will still be able to low level reverse engineer it (which is much harder to do and usually gives poorer results)

**Comment by konding** [comment]
now i know better, thank you.

**Comment by AlienRecall** [comment]
How can we protect the frontend source?

**Comment by asticode** [comment]
Right now there's no way to protect the frontend source

**Comment by runeimp** [comment]
Sorry, have to rant a bit. Why do you care about your front-end code so much? I used to see this all the time in the Flash community. Even for ActionScript prior to it looking like JavaScript which was less powerful than Bash. No one cares about your `for` loop! In this case why would HTML or CSS need to be secured? If you have secrets hidden in your HTML, CSS, or JS then don't do that. Use a secrets management system like HashiCorp Vault or Google's Secret Manager. If you're worried about protecting your API call structure then you're doing it wrong. What you're asking about is the same as DRM and DRM is a fantasy. If someone is desperate to see how special your for loop is they will get there. And they will learn all the secrets every decent front-end dev already knows. If you actually care about security DRM is not going to save you.

**Comment by AlienRecall** [comment]
Hi, is possible to use other packages like [goobfuscate](https://github.com/unixpickle/gobfuscate) to build the Golang part?

**Comment by asticode** [comment]
> Hi, is possible to use other packages like goobfuscate to build the Golang part?

If you're not using the [bundler](https://github.com/asticode/go-astilectron-bundler) you can pretty much use any build tool you want.

If you're using the `bundler`, you can try using the [go_binary_path](https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go#L41) to specify the path to `goobfuscate` and [build_flags](https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go#L56) to specify `goobfuscate`flags, all in your `bundler.json`, even though I'm not sure this will work at all since the `bundler` may add flags that will make `goobfuscate` crash.

**Comment by AlienRecall** [comment]
> > Hi, is possible to use other packages like goobfuscate to build the Golang part?
> 
> If you're not using the [bundler](https://github.com/asticode/go-astilectron-bundler) you can pretty much use any build tool you want.
> 
> If you're using the `bundler`, you can try using the [go_binary_path](https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go#L41) to specify the path to `goobfuscate` and [build_flags](https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go#L56) to specify `goobfuscate`flags, all in your `bundler.json`, even though I'm not sure this will work at all since the `bundler` may add flags that will make `goobfuscate` crash.

Thanks for the reply, yes I'm using the bundler and after modifying some lines of the butler source it worked fine, maybe when I'll have more time I can make a pr to hand different compilers better

**Comment by AlienRecall** [comment]
Thanks for the reply! Yes I'm using Astilectron-bundler and sadly It adds some flags that make the compiler crash, but I've changed some lines of the bundler source and now it works fine. Maybe when I'll have more time I'll make a pr to the bundler repo, to fix that issue

**Comment by packet-sent** [comment]
> Thanks for the reply! Yes I'm using Astilectron-bundler and sadly It adds some flags that make the compiler crash, but I've changed some lines of the bundler source and now it works fine. Maybe when I'll have more time I'll make a pr to the bundler repo, to fix that issue

Hi, would you be able to make the fork public as I wanted to a quick look at it if possible,
