### ISSUE TITLE
feature request control stack

### ISSUE THREAD

**Issue by rashwell** [asticode/go-astilectron#66]
Should we consider a controls stack and interface set.

Example: 
Go data bound control stack and interface set (go-asticontrols)

- control interface including child controls array
  - control button
  - control input
  - control tool button bar
  - control status bar
  - control container
  - control vertical flow, horizontal, grid etc.
  - control splitter
  - control data table

etc.

The idea is to build something api ish like C# Winforms, Xamarian Forms, SWT, etc. So that developer can quickly code out the application in go and have the comms between electron and go backed controls handled naturally.

It seems like quite a but of work, but if we outline just the project and some sort of control interface and maybe a single control or two then other developers could quickly PR up and entire control stack.

Later we could even include using go's built in generator to perhaps take as input something declarative like XAML and generate the go code for the controls.

Does this seem too ambitious?

**Comment by asticode** [comment]
@rashwell it sounds like a fair idea but not in this repo.

Indeed this repo is about communicating with Electron and shouldn't deal with the way the HTML/JS/CSS is built.

However, an HTML/JS/CSS generator (which is what you're proposing) could be a good idea in another repo. Maybe there are already some projects that achieve that very same feature?

**Comment by gedw99** [comment]
@rashwell  maybe you mean the underlying plumbing for the API, and not the actual GUI aspects ?

Then if the plumbing is there in the main package, anyone can add a GUI on top of it.
This woudl then make the package much easier to use and extend i think.
