### ISSUE TITLE
Error loading index.html

### ISSUE THREAD

**Issue by connorlurring** [asticode/go-astilectron#67]
I get the error `Not allowed to load local resource` when trying to load the `index.html`.

My file structure is `resources/app` containing my `index.html` and the `static` directory.

I declare the homepage in my boostrapper with `Homepage: "index.html"`

I'd appreciate any help resolving this.

**Comment by asticode** [comment]
@connorlurring on which OS/ARCH are you working? Can you paste the logs here when you run your app with the `-v` flag?

**Comment by connorlurring** [comment]
Running macOS High Sierra so it'll be darwin/x86.

The issue that's causing it is my resources file isn't being packaged into the exe.

The important line in the logs is:

`DEBU[0094] Sending to Astilectron: {"name":"window.cmd.create","targetID":"1","sessionId":"2","url":"file:///var/folders/42/4k7bfr3j6dz5__ydtksvbxth0000gn/T/go-build555941086/command-line-arguments/_obj/exe/resources/app/index.html","windowOptions":{"center":true,"height":700,"title":"Samurai","titleBarStyle":"hidden-inset","width":1400}}`

However when I navigate to the `exe` directory, there is only a folder called my application name and a folder called vendor, no `resources` folder.

**Comment by asticode** [comment]
@connorlurring are you using the [bundler](https://github.com/asticode/go-astilectron-bundler) and the [bootstrap](https://github.com/asticode/go-astilectron-bootstrap)? If so can you provide:

- your folders structure
- the content of your `bundler.json`
- the first lines of the log when you run your app with the `-v` flag

**Comment by connorlurring** [comment]
Bundler:
```json
{
  "app_name": "Samurai",
  "output_path": "output"
}
```

Folder structure:
```
├── resources
│   └── app
│       ├── index.html
│       └── static
│           ├── css
│           │   └── style.css
│           ├── img
│           └── js
├── vendor
│   ├── astilectron
│   │   ├── LICENSE
│   │   ├── main.js
│   │   ├── package.json
│   │   ├── readme.md
│   │   └── src
│   │       ├── client.js
│   │       └── consts.js
│   ├── astilectron-v0.14.0.zip
│   └── status.json
└── vendor_astilectron_bundler
    ├── astilectron.zip
    └── electron.zip
```

```
DEBU[0000] Starting...                                  
DEBU[0000] Provisioning...                              
DEBU[0000] Provisioning Astilectron...                  
DEBU[0000] Removing directory /var/folders/42/4k7bfr3j6dz5__ydtksvbxth0000gn/T/go-build573977524/command-line-arguments/_obj/exe/vendor/astilectron 
DEBU[0000] Downloading https://github.com/asticode/astilectron/archive/v0.14.0.zip into /var/folders/42/4k7bfr3j6dz5__ydtksvbxth0000gn/T/go-build573977524/command-line-arguments/_obj/exe/vendor/astilectron-v0.14.0.zip 
DEBU[0001] Creating directory /var/folders/42/4k7bfr3j6dz5__ydtksvbxth0000gn/T/go-build573977524/command-line-arguments/_obj/exe/vendor/astilectron 
DEBU[0001] Unzipping /var/folders/42/4k7bfr3j6dz5__ydtksvbxth0000gn/T/go-build573977524/command-line-arguments/_obj/exe/vendor/astilectron-v0.14.0.zip/astilectron-0.14.0 into /var/folders/42/4k7bfr3j6dz5__ydtksvbxth0000gn/T/go-build573977524/command-line-arguments/_obj/exe/vendor/astilectron 
DEBU[0001] Provisioning Electron...                     
DEBU[0001] Removing directory /var/folders/42/4k7bfr3j6dz5__ydtksvbxth0000gn/T/go-build573977524/command-line-arguments/_obj/exe/vendor/electron-darwin-amd64 
DEBU[0001] Downloading https://github.com/electron/electron/releases/download/v1.8.1/electron-v1.8.1-darwin-x64.zip into /var/folders/42/4k7bfr3j6dz5__ydtksvbxth0000gn/T/go-build573977524/command-line-arguments/_obj/exe/vendor/electron-darwin-amd64-v1.8.1.zip
```

**Comment by connorlurring** [comment]
Ok so I managed to resolve this.

GoLand was saying that Asset and RestoreAssets didn't exist (due to the nature of how the binds are generated). For this reason I removed them hoping that the library would fall back to default (the default folder structure). It appears that it does not and, as such, there was no ability to load the application due to the lack of access to assets.

I propose that when the Asset and RestoreAssets aren't specified the OS bindings are used as default as these are optional in the struct and shouldn't be required unless the user wishes to implement custom behaviour.

**Comment by asticode** [comment]
@connorlurring good to know you managed to resolve this :)

Unfortunately, what you're proposing is not possible. Indeed embedding assets in the binary happens at build time. At runtime, if you haven't specified an `Asset` or a `RestoreAssets` function, there's no way GO knows which function to execute to disembed your asset. You have to specify it at build time. There's no such things as `OS bindings` or I misunderstood what you meant by it.

If you don't specify those bootstrap options, the assumption is made that your `resources` files are already on disk and don't need to be disembedded.
