### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by wizarddewhite** [asticode/go-astilectron#68]
Hi, 

I am trying your go-astilectron-demo project. And willing to add a text box to let users input some content.

When I type in with keyboard, it looks good. If I want to paste some content into the text box, no effects.

The code I changed is in index.html.  I added below codes at the top of body

    <div class="form-group">
      <label>Name</label>
      <input id="uname" class="form-control" placeholder="Enter account" name="uname">
    </div>

Hmm... not sure which option should I change?

**Comment by asticode** [comment]
@wizarddewhite in Electron, all keyboard shortcuts are disabled by default. You have to add them manually in a `MenuItem` to enable them. There are 2 solutions for that:

- use the `Accelerator` attribute I've just added in the `MenuItem`:

```go
{
  Accelerator: astilectron.NewAccelerator("CommandOrControl", "A"),
  OnClick: func(e astilectron.Event) (deleteListener bool) {
    // Do stuff that will be executed when you press "CommandOrControl" + "A"
  }
}
```

- use the `Role` attribute of a `MenuItem` to enable mainstream shortcuts such as `Paste`:

```go
{
  Role: astilectron.MenuItemRolePaste,
}
```

Does that fix your issue?

**Comment by wizarddewhite** [comment]
Yep, I tried the second solution, and works fine for me.

Thanks!

**Comment by asticode** [comment]
Cheers
