### ISSUE TITLE
Enable plugins

### ISSUE THREAD

**Issue by jpmarr** [asticode/go-astilectron#69]
Is it possible to supply command line args to Electron when using astilectron? I need to enable the Widevine CDM plugin for the Spotify web player to work.

https://github.com/electron/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md

The above requires supplying path info for the plugin binaries via electron command line args.

**Comment by asticode** [comment]
@jpmarr I've just added an `ElectronSwitches` attribute to the go-astilectron's `Options` struct. You can achieve what you're looking for by setting it like this:

```go
ElectronSwitches: []string{
  "-widevine-cdm-path",
  "/path/to/widevinecdmadapter.plugin",
  "-widevine-cdm-version",
  "1.4.8.866",
}
```

And you can already set the `Plugins` attribute of the `BrowserOptions` to `true`.

Don't forget to `make` the bundler before testing if you're using it to bundle your astilectron app.

Does that fix your issue?

**Comment by jpmarr** [comment]
It does indeed. Many thanks for your help.
