### ISSUE TITLE
how to control z index in modaler? 

### ISSUE THREAD

**Issue by Jungmu** [asticode/go-astilectron#71]
![image](https://user-images.githubusercontent.com/10569683/34990582-fc248a20-fb09-11e7-9588-5310a863d560.png)
how to fix it?

**Comment by asticode** [comment]
@Jungmu FYI the modaler is can be found in [this repo](https://github.com/asticode/js-toolbox). I've updated it with a `z-index` to `1`. Therefore 2 solutions for you:

- copy/paste [this content](https://github.com/asticode/js-toolbox/tree/master/astimodaler) in `go-astilectron-demo/resources/app/static/lib/astimodaler/`
- update manually the `.astimodaler` class in `go-astilectron-demo/resources/app/static/lib/astimodaler/astimodaler.css`

Does that fix your issue?

**Comment by asticode** [comment]
@Jungmu does it work?

**Comment by Jungmu** [comment]
sorry...
I was too busy yesterday so, i'm not try yet...
I'll try it tonight and let you know.

**Comment by Jungmu** [comment]
oh! it work!
![image](https://user-images.githubusercontent.com/10569683/35097235-a2842554-fc92-11e7-974a-54607a90b038.png)

but as notifier has same issues
you need fix that too.

![image](https://user-images.githubusercontent.com/10569683/35097257-b76476d6-fc92-11e7-9809-86951d9053ac.png)
like this

Thank you for your consideration

**Comment by asticode** [comment]
Thanks for the tip, will do

Cheers
