### ISSUE TITLE
fyi. reddit posting re: go-bindata 404 Not Found / removed from github?

### ISSUE THREAD

**Issue by githubfanster** [asticode/go-astilectron#75]
https://www.reddit.com/r/golang/comments/7vv9zz/popular_lib_gobindata_removed_from_github_or_why/

doesnt the astilectron-bundler project have a dependency on that package?

**Comment by asticode** [comment]
@githubfanster yes it does, nice catch

**Comment by asticode** [comment]
Hard forked the repo myself and updated the dependency.

Cheers.

**Comment by Noofbiz** [comment]
Actually that repo was not maintained or updated for years before this happened. Ann up to date and actively maintained fork of the repo is here https://github.com/shuLhan/go-bindata
