### ISSUE TITLE
tray.setImage() API support 

### ISSUE THREAD

**Issue by txthinking** [asticode/go-astilectron#77]
Update tray icon after init.

API https://github.com/electron/electron/blob/master/docs/api/tray.md#traysetimageimage

Thanks

**Comment by asticode** [comment]
@txthinking I won't have a lot of time to tackle that issue in the coming months but I'd be happy to review a PR. If you're interested, I can point you in the right directions :)

**Comment by asticode** [comment]
@txthinking I've added the Tray's [SetImage](https://github.com/asticode/go-astilectron/blob/master/tray.go#L74) method.

I'll close this issue for now, do reopen it if it doesn't fix your issue.

Cheers
