### ISSUE TITLE
Can direct use local electron binary?

### ISSUE THREAD

**Issue by MiyamuraMiyako** [asticode/go-astilectron#79]
Because I use it in offline environment.

**Comment by MiyamuraMiyako** [comment]
And can I choose the electron version myself?

**Comment by asticode** [comment]
@MiyamuraMiyako you can't choose the electron version yourself but you can use the local electron binary. 

By the way if your goal is to use the local electron binary directly without using GO, maybe this project is not the best tool for your project :)

**Comment by MiyamuraMiyako** [comment]
@asticode Thank you for reply. I used local electron now. Problem solved.
