### ISSUE TITLE
App crashes in Ubuntu 17.10

### ISSUE THREAD

**Issue by MiyamuraMiyako** [asticode/go-astilectron#80]
```shell
2018/02/26 22:59:42 debugger.go:497: continuing
FATA[0000] running bootstrap failed: creating window failed: canceller.cancelled
```

**Comment by MiyamuraMiyako** [comment]
May be It's Ubuntu17.10's ploblem, I will try solve it.

**Comment by asticode** [comment]
@MiyamuraMiyako `canceller.cancelled` means the context has been cancelled at some point. There are several ways a context can be cancelled. Did you paste all the logs you received?

**Comment by MiyamuraMiyako** [comment]
@asticode yes,That's all info output from console.

It's ubuntu17.10's xhost problem. When I use ubuntu16.04, everything is ok.

**Comment by asticode** [comment]
@MiyamuraMiyako unfortunately I don't have a 17.10 ubuntu OS to test on, did you manage to make work ultimately?

**Comment by MiyamuraMiyako** [comment]
@asticode Due to the time, I can not solve the problem temporarily. I will take the time to deal with the problem in the future.

**Comment by asticode** [comment]
@MiyamuraMiyako sure, let me know if you manage to solve this at some point, I'm really interested in a solution for this.

**Comment by MiyamuraMiyako** [comment]
@asticode In ubuntu17 and later, need to execute ```xhost +```(not need root privileges) command to allow other users use gui.

**Comment by asticode** [comment]
@MiyamuraMiyako that's good to know. Could you give us the full command line that you execute so that it helps other that may have the problem?

**Comment by MiyamuraMiyako** [comment]
@asticode Yes.

If I use user A login, then I need exec ```xhost +``` in user A's shell. Then switch to root or other users, It can run electron normally.

**Comment by asticode** [comment]
@MiyamuraMiyako thanks for reporting the solution back here. 

Closing this issue now.

**Comment by wallnutkraken** [comment]
I get the same issue on w.Create() (from readme) on Manjaro (Linux 4.18.9)

**Comment by asticode** [comment]
@wallnutkraken can you paste the logs when you run your binary with the `-v` flag ?

**Comment by wallnutkraken** [comment]
-v? Am I missing something here? As far as I understood from the readme I just launched my program via `go run`

**Comment by asticode** [comment]
You're right indeed, but as `astilectron` uses `astilog`, the flag `-v` exists by default to print debug logs. Therefore if you run `go run -v`, it will print debug logs I'm interested in.

**Comment by Guillaume695** [comment]
Just ran into the same issue a few hours ago. I'm posting here the solution to my problem as it might help someone :smile:

Adding `-v` as @asticode suggested, I realized that the version of the astilectron archive downloaded by the bundler and the version of the archive uncompressed at run time didn't match. The reason for that is that I built `astilectron-bundler` a few weeks ago while dep keeps pulling the latest version of the `go-astilectron` repo. Therefore the `astilectron-bundler` binary was downloading the `0.28.0' version to build the app while my app was trying to unzip the `0.29.0` version at run time.

### Solution
Delete and rebuild `astilectron-bundler`.

### Suggestions
It would be great to give the versions of electron and astilectron to the bundler as a parameter. Or even better, if those 2 values were determined at build time by the bundler, according to the version of the `go-astilectron` code used by the project.

Anyway I hope this will be helpful to someone out there :smiley: Thanks for this awesome project !!

**Comment by bright-light-in-the-night** [comment]
I had the same issue (Ubuntu 16), but my problem was the missing `libnss3` library. Installing it solved the issue.

**Comment by asticode** [comment]
Thanks for the heads-up @bright-light-in-the-night !
