### ISSUE TITLE
View .js Errors in App

### ISSUE THREAD

**Issue by deranjer** [asticode/go-astilectron#82]
Is there a way to view the javascript console in the application while it is running?

**Comment by asticode** [comment]
@deranjer sure, you have to use the [DevTools](https://github.com/asticode/go-astilectron/blob/master/window.go#L131) attribute, or, if you're using the bootstrap, you can simply use the [Debug](https://github.com/asticode/go-astilectron-bootstrap/blob/master/options.go#L11) attribute.

Does that answer your question?
