### ISSUE TITLE
How to do logging during development?

### ISSUE THREAD

**Issue by rcholic** [asticode/go-astilectron#85]
is there a way to do logging and see the logging messages?

**Comment by asticode** [comment]
@rcholic in GO you can use `astilog.Debug` or any other methods `astilog` is providing, and in javascript you can use the good old `console.log` method. To see the messages you'll have to enable the Dev Tools in your window (https://github.com/asticode/go-astilectron/blob/master/window.go#L131 or https://github.com/asticode/go-astilectron/blob/master/window.go#L330).

Also you can use the GO `Log` window method (https://github.com/asticode/go-astilectron/blob/master/window.go#L265) which will send an event to javascript and will log your message in javascript.

Does that fix your problem?
