### ISSUE TITLE
undefined: os.Executable

### ISSUE THREAD

**Issue by zabuTNT** [asticode/go-astilectron#9]
I've an error when I get your package. 
I think it's related to this commit on path.go

[Default base directory path is now the executable directory path ](https://github.com/asticode/go-astilectron/commit/5ad600fa13fb2f2eec28b2988b177c66f811055b)

` go get -u github.com/asticode/go-astilectron`
`# github.com/asticode/go-astilectron`
`../github.com/asticode/go-astilectron/paths.go:64: undefined: os.Executable`

OS: linux
Go version: go1.8.1 linux/amd64

there are some dependencies for this function?

**Comment by asticode** [comment]
mmm this is weird, it uses the "os" package in the standard library so it should be defined at any time and shouldn't need any dependencies...

do you have another "os" package available in your "$GOPATH/src"?

can you copy/paste the import section of the paths.go file?

**Comment by zabuTNT** [comment]
I resolved... it was true that my go version is 1.8.1 BUT $GOROOT referred to a folder with the old 1.7 version, Executable() was introduced only in go1.8, I change the path of GOROOT to the updated version and now it's all ok.
