### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by AlinaSt** [asticode/go-astilectron#93]
Hello! This happens when I'm trying to run app
{"level":"fatal","msg":"running bootstrap failed: starting astilectron failed: provisioning failed: provisioning electron failed: unzipping C:\\Users\\xxx\\AppData\\Roaming\\vendor\\electron-windows-amd64-v1.8.1.zip into C:\\Users\\xxx\\AppData\\Roaming\\vendor\\electron-windows-amd64 failed: unzipping C:\\Users\\xxx\\AppData\\Roaming\\vendor\\electron-windows-amd64-v1.8.1.zip into C:\\Users\\xxx\\AppData\\Roaming\\vendor\\electron-windows-amd64 failed: opening overall zip reader on C:\\Users\\xxx\\AppData\\Roaming\\vendor\\electron-windows-amd64-v1.8.1.zip failed: read C:\\Users\\xxx\\AppData\\Roaming\\vendor\\electron-windows-amd64-v1.8.1.zip: The handle is invalid.","time":"2018-04-03T15:53:37+04:00"}

Please, can you help solving this problem?

**Comment by asticode** [comment]
@AlinaSt 

- are you trying to run the [demo](https://github.com/asticode/go-astilectron-demo)?
- could you make sure you execute `go get -u ./...` on your project to make sure all the projects are up to date?
- could you paste the logs when you execute the bundler with the `-v` flag ? (`astilectron-bundler -v`)
- could you paste the logs when you execute the app with the `-v` flag ?

**Comment by AlinaSt** [comment]
Now, I am trying to run demo. This happens when I'm executing the bundler with the -v flag (astilectron-bundler -v)
$ astilectron-bundler -v
{"level":"debug","msg":"Resetting","time":"2018-04-03T16:45:17+04:00"}
{"level":"debug","msg":"Creating C:\\Users\\xxx\\AppData\\Local\\Temp\\asti                                                                                                                                                                                               bundler","time":"2018-04-03T16:45:17+04:00"}
{"level":"debug","msg":"Creating C:\\Users\\xxx\\go\\src\\github.com                                                                                                                                                                                               \\asticode\\go-astilectron-demo\\output","time":"2018-04-03T16:45:17+04:00"}
{"level":"debug","msg":"Bundling for environment windows/amd64","time":"2018-04-                                                                                                                                                                                               03T16:45:17+04:00"}
{"level":"debug","msg":"Removing C:\\Users\\xxx\\go\\src\\github.com                                                                                                                                                                                               \\asticode\\go-astilectron-demo\\output\\windows-amd64","time":"2018-04-03T16:45                                                                                                                                                                                               :17+04:00"}
{"level":"debug","msg":"Creating C:\\Users\\xxx\\go\\src\\github.com                                                                                                                                                                                               \\asticode\\go-astilectron-demo\\output\\windows-amd64","time":"2018-04-03T16:45                                                                                                                                                                                               :17+04:00"}
{"level":"debug","msg":"Binding data","time":"2018-04-03T16:45:17+04:00"}
{"level":"debug","msg":"Removing C:\\Users\\xxx\\go\\src\\github.com                                                                                                                                                                                               \\asticode\\go-astilectron-demo\\vendor_astilectron_bundler","time":"2018-04-03T                                                                                                                                                                                               16:45:17+04:00"}
{"level":"debug","msg":"Creating C:\\Users\\xxx\\go\\src\\github.com                                                                                                                                                                                               \\asticode\\go-astilectron-demo\\vendor_astilectron_bundler","time":"2018-04-03T                                                                                                                                                                                               16:45:17+04:00"}
{"level":"debug","msg":"C:\\Users\\xxx\\AppData\\Local\\Temp\\astibundler\\                                                                                                                                                                                               astilectron-0.17.0.zip already exists, skipping download of https://github.com/a                                                                                                                                                                                               sticode/astilectron/archive/v0.17.0.zip","time":"2018-04-03T16:45:17+04:00"}
{"level":"debug","msg":"Copying C:\\Users\\xxx\\AppData\\Local\\Temp\\astib                                                                                                                                                                                               undler\\astilectron-0.17.0.zip to C:\\Users\\xxx\\go\\src\\github.co                                                                                                                                                                                               m\\asticode\\go-astilectron-demo\\vendor_astilectron_bundler\\astilectron.zip","                                                                                                                                                                                               time":"2018-04-03T16:45:17+04:00"}
{"level":"fatal","msg":"bundling failed: bundling for environment windows/amd64                                                                                                                                                                                                failed: binding data failed: provisioning the vendor failed: provisioning astile                                                                                                                                                                                               ctron vendor failed: copying C:\\Users\\xxx\\AppData\\Local\\Temp\\astibund                                                                                                                                                                                               ler\\astilectron-0.17.0.zip to C:\\Users\\xxx\\go\\src\\github.com\\                                                                                                                                                                                               asticode\\go-astilectron-demo\\vendor_astilectron_bundler\\astilectron.zip faile                                                                                                                                                                                               d: chmod C:\\Users\\xxx\\go\\src\\github.com\\asticode\\go-astilectr                                                                                                                                                                                               on-demo\\vendor_astilectron_bundler\\astilectron.zip: not supported by windows",                                                                                                                                                                                               "time":"2018-04-03T16:45:17+04:00"}

**Comment by AlinaSt** [comment]
Now, I am trying to run my app. This happens when I'm executing the bundler with the -v flag (astilectron-bundler -v)

$ astilectron-bundler -v
{"level":"debug","msg":"Resetting","time":"2018-04-03T16:53:55+04:00"}
{"level":"debug","msg":"Creating C:\\Users\\xxx\\AppData\\Local\\Temp\\astibundler","time":"2018-04-03T16:53:55+04:00"}
{"level":"debug","msg":"Creating C:\\Users\\xxx\\go\\src\\exchservice\\output","time":"2018-04-03T16:53:55+04:00"}
{"level":"debug","msg":"Bundling for environment windows/amd64","time":"2018-04-03T16:53:55+04:00"}
{"level":"debug","msg":"Removing C:\\Users\\xxx\\go\\src\\exchservice\\output\\windows-amd64","time":"2018-04-03T16:53:55+04:00"}
{"level":"debug","msg":"Creating C:\\Users\\xxx\\go\\src\\exchservice\\output\\windows-amd64","time":"2018-04-03T16:53:55+04:00"}
{"level":"debug","msg":"Binding data","time":"2018-04-03T16:53:55+04:00"}
{"level":"debug","msg":"Removing C:\\Users\\xxx\\go\\src\\exchservice\\vendor_astilectron_bundler","time":"2018-04-03T16:53:55+04:00"}
{"level":"debug","msg":"Creating C:\\Users\\xxx\\go\\src\\exchservice\\vendor_astilectron_bundler","time":"2018-04-03T16:53:55+04:00"}
{"level":"debug","msg":"C:\\Users\\xxx\\AppData\\Local\\Temp\\astibundler\\astilectron-0.17.0.zip already exists, skipping download of https://github.com/asticode/astilectron/archive/v0.17.0.zip","time":"2018-04-03T16:53:55+04:00"}
{"level":"debug","msg":"Copying C:\\Users\\xxx\\AppData\\Local\\Temp\\astibundler\\astilectron-0.17.0.zip to C:\\Users\\xxx\\go\\src\\exchservice\\vendor_astilectron_bundler\\astilectron.zip","time":"2018-04-03T16:53:55+04:00"}
{"level":"fatal","msg":"bundling failed: bundling for environment windows/amd64 failed: binding data failed: provisioning the vendor failed: provisioning astilectron vendor failed: copying C:\\Users\\xxx\\AppData\\Local\\Temp\\astibundler\\astilectron-0.17.0.zip to C:\\Users\\xxx\\go\\src\\exchservice\\vendor_astilectron_bundler\\astilectron.zip failed: chmod C:\\Users\\xxx\\go\\src\\exchservice\\vendor_astilectron_bundler\\astilectron.zip: not supported by windows","time":"2018-04-03T16:53:55+04:00"}

**Comment by asticode** [comment]
which go version are you using?

**Comment by asticode** [comment]
I've pushed a fix. Could you do the following commands and let me know whether it's working?

- `go get -u github.com/asticode/go-astitools`
- `cd $GOPATH/src/github.com/asticode/go-astilectron-bundler`
- `make`
- `cd /path/to/your/project`
- `astilectron-bundler -v`

Does it work now?

**Comment by AlinaSt** [comment]
make: command not found

**Comment by asticode** [comment]
run `go install ./astilectron-bundler` instead

**Comment by AlinaSt** [comment]
{"level":"debug","msg":"Resetting","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"Creating C:\\Users\\xxx\\AppData\\Local\\Temp\\astibundler","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"Creating C:\\Users\\xxx\\go\\src\\github.com\\asticode\\go-astilectron-demo\\output","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"Bundling for environment windows/amd64","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"Removing C:\\Users\\xxx\\go\\src\\github.com\\asticode\\go-astilectron-demo\\output\\windows-amd64","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"Creating C:\\Users\\xxx\\go\\src\\github.com\\asticode\\go-astilectron-demo\\output\\windows-amd64","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"Binding data","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"Removing C:\\Users\\xxx\\go\\src\\github.com\\asticode\\go-astilectron-demo\\vendor_astilectron_bundler","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"Creating C:\\Users\\xxx\\go\\src\\github.com\\asticode\\go-astilectron-demo\\vendor_astilectron_bundler","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"C:\\Users\\xxx\\AppData\\Local\\Temp\\astibundler\\astilectron-0.17.0.zip already exists, skipping download of https://github.com/asticode/astilectron/archive/v0.17.0.zip","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"Copying C:\\Users\\xxx\\AppData\\Local\\Temp\\astibundler\\astilectron-0.17.0.zip to C:\\Users\\xxx\\go\\src\\github.com\\asticode\\go-astilectron-demo\\vendor_astilectron_bundler\\astilectron.zip","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"C:\\Users\\xxx\\AppData\\Local\\Temp\\astibundler\\electron-windows-amd64-1.8.1.zip already exists, skipping download of https://github.com/electron/electron/releases/download/v1.8.1/electron-v1.8.1-win32-x64.zip","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"Copying C:\\Users\\xxx\\AppData\\Local\\Temp\\astibundler\\electron-windows-amd64-1.8.1.zip to C:\\Users\\xxx\\go\\src\\github.com\\asticode\\go-astilectron-demo\\vendor_astilectron_bundler\\electron.zip","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"Generating C:\\Users\\xxx\\go\\src\\github.com\\asticode\\go-astilectron-demo\\bind_windows_amd64.go","time":"2018-04-04T09:27:38+04:00"}
{"level":"debug","msg":"Running rsrc for icon C:\\Users\\xxx\\go\\src\\github.com\\asticode\\go-astilectron-demo\\resources\\icon.ico into C:\\Users\\xxx\\go\\src\\github.com\\asticode\\go-astilectron-demo\\windows.syso","time":"2018-04-04T09:27:41+04:00"}
{"level":"debug","msg":"Building for os windows and arch amd64","time":"2018-04-04T09:27:41+04:00"}
{"level":"debug","msg":"Executing go build -ldflags -s -X \"main.AppName=Astilectron demo\" -X \"main.BuiltAt=2018-04-04 09:27:41.4769677 +0400 +04 m=+2.841244201\" -H windowsgui -o C:\\Users\\xxx\\go\\src\\github.com\\asticode\\go-astilectron-demo\\output\\windows-amd64\\binary ","time":"2018-04-04T09:27:41+04:00"}
{"level":"fatal","msg":"bundling failed: bundling for environment windows/amd64 failed: building failed: message.go:12:2: cannot find package \"github.com/asticode/go-astichartjs\" in any of:\n\tC:\\Go\\src\\github.com\\asticode\\go-astichartjs (from $GOROOT)\n\t($GOPATH not set. For more details see: 'go help gopath')\nmain.go:9:2: cannot find package \"github.com/asticode/go-astilectron\" in any of:\n\tC:\\Go\\src\\github.com\\asticode\\go-astilectron (from $GOROOT)\n\t($GOPATH not set. For more details see: 'go help gopath')\nmain.go:10:2: cannot find package \"github.com/asticode/go-astilectron-bootstrap\" in any of:\n\tC:\\Go\\src\\github.com\\asticode\\go-astilectron-bootstrap (from $GOROOT)\n\t($GOPATH not set. For more details see: 'go help gopath')\nmain.go:11:2: cannot find package \"github.com/asticode/go-astilog\" in any of:\n\tC:\\Go\\src\\github.com\\asticode\\go-astilog (from $GOROOT)\n\t($GOPATH not set. For more details see: 'go help gopath')\nmain.go:12:2: cannot find package \"github.com/pkg/errors\" in any of:\n\tC:\\Go\\src\\github.com\\pkg\\errors (from $GOROOT)\n\t($GOPATH not set. For more details see: 'go help gopath')\n: exit status 1","time":"2018-04-04T09:27:41+04:00"}

My $GOPATH is C:/Users/xxx/go

I am using Goland IDE be JetBrains. And when I'm trying to run app in IDE this still happens:
{"level":"fatal","msg":"running bootstrap failed: starting astilectron failed: provisioning failed: provisioning electron failed: unzipping C:\\Users\\xxx\\AppData\\Roaming\\vendor\\electron-windows-amd64-v1.8.1.zip into C:\\Users\\xxx\\AppData\\Roaming\\vendor\\electron-windows-amd64 failed: unzipping C:\\Users\\xxx\\AppData\\Roaming\\vendor\\electron-windows-amd64-v1.8.1.zip into C:\\Users\\xxx\\AppData\\Roaming\\vendor\\electron-windows-amd64 failed: opening overall zip reader on C:\\Users\\xxx\\AppData\\Roaming\\vendor\\electron-windows-amd64-v1.8.1.zip failed: read C:\\Users\\xxx\\AppData\\Roaming\\vendor\\electron-windows-amd64-v1.8.1.zip: The handle is invalid.","time":"2018-04-04T09:28:26+04:00"}

**Comment by asticode** [comment]
It seems your $GOPATH is not set in your IDE (I can see `$GOPATH not set` in the error message). Since you can't build the binary properly, the final error is normal.
