### ISSUE TITLE
Moving window when TitleBarStyle = astilectron.TitleBarStyleHidden

### ISSUE THREAD

**Issue by rcholic** [asticode/go-astilectron#94]
On the main window,  I set the windowOptions `TitleBarStyle:   astilectron.TitleBarStyleHidden`, because I want to have a titlebar that has embedded Mac-style icons and search field. After doing this, however, the window is no longer draggable and I cannot move it with my mouse. 

I could add drag & move events to my UI in JavaScript, but I am not sure how to send the message to Go with the window's new coordinate (x, y), because the `astilectron.sendMessage()` function does not seem to take a third parameter. 

any ideas can make this work when **TitleBarStyle = astilectron.TitleBarStyleHidden**?

**Comment by asticode** [comment]
@rcholic have you tried using the [Move](https://github.com/asticode/go-astilectron/blob/master/window.go#L293) method?

**Comment by rcholic** [comment]
@asticode I did take a look at the `Move` method, but I don't know how I should pass the mouse's new (x, y) coordinate to the `Move` method from my UI in HTML + JS.

**Comment by rcholic** [comment]
@asticode 

Thanks very much for the information. Just a quote in case other people need to do something similar:

```
-webkit-app-region: drag in CSS to tell Electron which regions are draggable (like the OS's standard titlebar), and apps can also use -webkit-app-region: no-drag to exclude the non-draggable area from the draggable region. 
```
Note that the window is still NOT draggable with the css applied if the developer console is open.

**Comment by asticode** [comment]
Cheers
